force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateVOIDetail.cls
public class GenerateVOIDetail {
	
    @AuraEnabled 
    public static string GenerateVOI(id recId){
       
        VOI_status__c voiS = [Select id,Contact__c,Opportunity__c, name,VOI_Detail__c from VOI_status__c WHERE id =: recId];
        
        if(voiS.VOI_Detail__c != null){
            return 'Error';
        }
        else{
            VOI_detail__c obj = new VOI_detail__c();
            obj.Contact__c = vois.Contact__c;
			insert obj;    
            voiS.VOI_Detail__c = obj.id;
            update vois;
            return '';
        }
        
        
    }
    
}