force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Current_in_use__c.field-meta.xml
<CustomField>
    <fullName>Current_in_use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current (in use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Current_in_use__c.field-meta.xml
<CustomField>
    <fullName>Current_in_use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current in use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHandlerTest.cls
@isTest
public class ContentDocumentTriggerHandlerTest {
    @isTest
    static void testBeforeDelete() {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName ='Quote';
        opp.CloseDate = System.Today();
        insert opp;  
        
        Document_Requested__c dc = new Document_Requested__c();
        dc.Category__c = 'Purchase Invoice';
        dc.Opportunity__c = Opp.Id;
        Insert dc;
        
        List<ContentVersion> cnvList = new List<ContentVersion>();
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Cv';
        cv.PathOnClient = 'TestPath';
        cv.FirstPublishLocationId = opp.Id;
        cv.VersionData = Blob.valueOf('Test Data');
        cv.Current_in_use__c = true;
        cv.Document_Requested__c = dc.Id;
        insert cv;
        
        ContentVersion cv1 = new ContentVersion();
        cv1.Title = 'Test Cv1';
        cv1.PathOnClient = 'TestPath1';
        cv1.FirstPublishLocationId = opp.Id;
        cv1.VersionData = Blob.valueOf('Test Data 1');
        cv1.Current_in_use__c = false;
        cv1.Document_Requested__c = dc.Id;
        insert cv1;
        
        ContentVersion cv2 = [SELECT Id,ContentDocumentId From ContentVersion WHERE Id=: cv.id];
        List<ContentDocument> cntList = [SELECT Id From ContentDocument WHERE Id =: cv2.ContentDocumentId];
        ContentDocumentTriggerHandler handler = new ContentDocumentTriggerHandler();
        test.startTest();
        handler.beforeDelete(cntList);
        test.stopTest();
    }
    
}