force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Current_in_use__c.field-meta.xml
<CustomField>
    <fullName>Current_in_use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current (in use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Current_in_use__c.field-meta.xml
<CustomField>
    <fullName>Current_in_use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current in use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Status__c</fullName>
    <label>Customer Authorisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request sent to customer(s)</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 2</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 1</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment requested by supplier</fullName>
            </value>
            <value>
                <fullName>Payment requested by supplier (pending contract)</fullName>
            </value>
            <value>
                <fullName>Variation requested by customer</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer (pending contract)</fullName>
            </value>
            <value>
                <fullName>Payment authorised by customer</fullName>
            </value>
            <value>
                <fullName>Funding handover call completed</fullName>
            </value>
            <value>
                <fullName>Payment funded</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerHandlerTest.cls
@isTest
public class ContentVersionTriggerHandlerTest {
    @isTest
    static void testAfterUpdate() {
        Id custSupPersonId = [select id,username from user where username=: System.Label.customerSite].id;
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName ='Quote';
        opp.CloseDate = System.Today();
        insert opp;  
        
        Document_Requested__c dc = new Document_Requested__c();
        dc.Category__c = 'Purchase Invoice';
        dc.Opportunity__c = Opp.Id;
        Insert dc;
        
        Document_Requested__c dc2 = new Document_Requested__c();
        dc2.Category__c = 'Lender Credit Contract';
        dc2.Opportunity__c = Opp.Id;
        Insert dc2;
        
        List<ContentVersion> cnvList = new List<ContentVersion>();
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Cv';
        cv.PathOnClient = 'TestPath';
        cv.FirstPublishLocationId = opp.Id;
        cv.VersionData = Blob.valueOf('Test Data');
        cv.Current_in_use__c = true;
        cv.Document_Requested__c = dc.Id;
        cv.OwnerId = custSupPersonId;
        insert cv;
        
        ContentVersion cv1 = new ContentVersion();
        cv1.Title = 'Test Cv1';
        cv1.PathOnClient = 'TestPath1';
        cv1.FirstPublishLocationId = opp.Id;
        cv1.VersionData = Blob.valueOf('Test Data 1');
        cv1.Current_in_use__c = false;
        cv1.OwnerId = custSupPersonId;
        insert cv1;
        
        ContentVersion cv2 = new ContentVersion();
        cv2.Title = 'Test Cv1';
        cv2.PathOnClient = 'TestPath1';
        cv2.FirstPublishLocationId = opp.Id;
        cv2.VersionData = Blob.valueOf('Test Data 1');
        cv2.Current_in_use__c = true;
        cv2.OwnerId = custSupPersonId;
        insert cv2;
        
        Funding_Request__c fr = new Funding_Request__c();
        fr.Opportunity__c = opp.Id;
        fr.Request_Status__c = 'Payment requested by customer (pending contract)';
        fr.Customer_Authorisation_Status__c = 'Authorised';
        insert fr;
        
        Funding_Request__c fr2 = new Funding_Request__c();
        fr2.Opportunity__c = opp.Id;
        fr2.Request_Status__c = 'Payment requested by supplier (pending contract)';
        fr2.Customer_Authorisation_Status__c = 'Authorised';
        insert fr2;
          
        Test.startTest();
        cv1.Document_Requested__c = dc.Id;
        cv2.Document_Requested__c = dc2.id;
        list<ContentVersion> cvlist = new list<ContentVersion>{cv1,cv2};
            update cvlist;
        Test.stopTest();
    }
}