force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/isComplete__c.field-meta.xml
<CustomField>
    <fullName>isComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Packs_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Packs_Out_Date__c</fullName>
    <label>Packs Out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Code_Match_Status__c</fullName>
    <label>Code Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Match(Success)</fullName>
            </value>
            <value>
                <fullName>Not-Match(Failed)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>Code_Not_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Code Not Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Identity_Certified_By__c.field-meta.xml
<CustomField>
    <fullName>Identity_Certified_By__c</fullName>
    <formula>IF(ISBLANK(verified_by__c) , $User.FirstName + &apos; &apos; + $User.MiddleName + &apos; &apos; + $User.LastName, verified_by__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identity Certified By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Identity_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Identity_Verification_Status__c</fullName>
    <label>Identity Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not-Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/matchVerification__c.field-meta.xml
<CustomField>
    <fullName>matchVerification__c</fullName>
    <formula>IF(ISPICKVAL(Code_Match_Status__c, &apos;Not-Match(Failed)&apos;), &apos;Not required&apos;, &apos;Verified&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>matchVerification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code__c</fullName>
    <label>Secure Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code_Orignal__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code_Orignal__c</fullName>
    <label>Secure Code Orignal</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/verified_by__c.field-meta.xml
<CustomField>
    <fullName>verified_by__c</fullName>
    <label>verified by</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/verified_by_selfie_ID__c.field-meta.xml
<CustomField>
    <fullName>verified_by_selfie_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>verified by selfie ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Video_and_Photo_ID_of_the_same_person__c.field-meta.xml
<CustomField>
    <fullName>Video_and_Photo_ID_of_the_same_person__c</fullName>
    <label>Video and Photo ID of the same person</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facial match (success)</fullName>
            </value>
            <value>
                <fullName>Not facial match (failed)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Show_Video_controller.cls
public class Show_Video_controller {
    public static final string voiId = ApexPages.currentPage() != null ? ApexPages.currentPage().getParameters().get('id') : '';
    public static String VideoDataToVf {get; set;}
    public static String VideoURL {get; set;}
    
    public Show_Video_controller(){
        VideoDataToVf = sendVideoDataToComponent(voiId);
        
        System.debug('VideoDataToVf'+VideoDataToVf);
        VideoURL = '/sfc/servlet.shepherd/version/download/'+VideoDataToVf;
    }
    
    
    
    public static String sendVideoDataToComponent(string RecId){
        System.debug('================================='+RecId);
        
        
        list<ContentVersion> CVList = new List<ContentVersion>();
        list<String> VersionDataList = new List<String>();
        String Temp;
        Set<Id> CDId = new Set<Id>();
        for(ContentDocumentLink Cd : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: RecId]){
            CDId.add(Cd.ContentDocumentId);
        }
        System.debug('CDId--->'+CDId);
        
        CVList = [SELECT Id FROM ContentVersion WHERE ContentDocumentId = : CDId AND Title = 'video' order by createddate DESC LIMIT 1];
        //System.debug('CVListCVList'+CVList);
        
        for(ContentVersion Cd : CVList){
            VersionDataList.add(Cd.Id);
        }
        System.debug('VersionDataList'+VersionDataList);
        if(VersionDataList != null){
            if(VersionDataList.size() > 0){
                Temp = VersionDataList[0];
            }    
        }
        return Temp;
    }
    
    @AuraEnabled
    public static VOI_Detail__c FetchVoiDetail(Id recId){
        system.debug('recId'+recId);
        VOI_Detail__c voi = [select Id,verified_by__c,Secure_Code__c,contact__c,verified_by_selfie_ID__c,matchVerification__c,contact__r.Name,contact__r.AccountID, Code_Not_Required__c,Code_Match_Status__c,Identity_Certified_By__c,Secure_Code_Orignal__c,Video_and_Photo_ID_of_the_same_person__c,Identity_Verification_Status__c From VOI_Detail__c WHERE Id = : recId];
        return voi;
    }
    
    @AuraEnabled
    public static VOI_Detail__c UpdateVOI(VOI_Detail__c voiDt){
        System.debug('video id : '+voiDt.verified_by_selfie_ID__c);
        boolean isWantPDF = false;
        System.debug('Video_and_Photo_ID_of_the_same_person__c----'+voiDt.Video_and_Photo_ID_of_the_same_person__c);
        if(string.isBlank(voiDt.verified_by__c)){
         	voiDt.verified_by__c = voiDt.Identity_Certified_By__c;   
        }        
        if(voiDt.Secure_Code__c == voiDt.Secure_Code_Orignal__c){
            voiDt.Code_Match_Status__c = 'MATCH(Success)';
        }
        else {
            voiDt.Code_Match_Status__c = 'NOT-MATCH(Failed)';
        }
        
        if((voiDt.Secure_Code__c == voiDt.Secure_Code_Orignal__c || voiDt.Code_Not_Required__c == true || voiDt.verified_by_selfie_ID__c == true) && voiDt.Video_and_Photo_ID_of_the_same_person__c == 'Facial match (success)') {
            
            voiDt.Identity_Verification_Status__c = 'Verified';
            
        }
        else{
            
            voiDt.Identity_Verification_Status__c = 'Not-Verified';
        }
        update voiDt;
        
        return voiDt;
    }
    
    @AuraEnabled
    public static void GenrateIdentityCertificate(VOI_Detail__c voiDt){
        
        Voi_status__c vois = [select id, name,Opportunity__c,Opportunity__r.id, VOI_detail__c from VOI_Status__c WHERE VOI_detail__r.id = : voidt.id LIMIT 1];
        opportunity opp = [select id, name,Packs_Out_Date__c from opportunity WHERE id =: vois.Opportunity__r.id LIMIT 1];
        contact cnt = [select id, Name from contact where id=: voidt.Contact__c LImit 1];
        
        
        string name = 'Identity Certificate for '+cnt.Name;
        
        Document_Requested__c dc = new Document_Requested__c();
        dc.Category__c = 'Identification';
        dc.Person_Account__c = voiDt.Contact__r.AccountId;
        dc.Opportunity__c = opp.Id;
        insert dc;
        
        PageReference pdf = Page.IdentityVerificationCertificatePDF;
        pdf.getParameters().put('id',voiDt.Id);
        pdf.setRedirect(true);
        Blob bPDF;
        
        if (Test.IsRunningTest())
        {
            bPDF=Blob.valueOf('UNIT.TEST');
        }
        else
        {
            System.debug('pdf.getContent()'+pdf.getContent());
            bPDF = pdf.getContent();
        }
       
        System.debug('voi.Contact__r'+cnt.Name);
        System.debug('voi.Contact__r.name'+cnt.Name);
        ContentVersion ContVerFile = new ContentVersion();
        ContVerFile.VersionData = bPDF;
        ContVerFile.Title = name; 
        ContVerFile.PathOnClient= name+'.pdf'; 
        ContVerFile.Document_Requested__c = dc.Id;
        insert ContVerFile;
        
        SYstem.debug('ContVerFile id '+ContVerFile.Id);
        List<ContentVersion> conDocId = new List<ContentVersion>();
        
        conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ContVerFile.Id];
        System.debug('conDocId : '+conDocId[0].ContentDocumentId);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = opp.id;
        cdl.ContentDocumentId = conDocId[0].ContentDocumentId;
        
        cdl.shareType = 'V';
        
        Insert cdl;
        System.debug('content+'+cdl.Id);
        
        if(cdl != null){
            Document_Requested__c doc = new Document_Requested__c();
            doc.id = dc.Id;
            doc.isComplete__c = true;
            update doc;
        }
    }    
    
}