force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Send_to_Lender__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Lender__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Lender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Supporting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Application_Supporting_Notes__c</fullName>
    <label>Application Supporting Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Lender_Application_ID__c</fullName>
    <label>Lender Application ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preferred_repayment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Preferred_repayment_frequency__c</fullName>
    <label>Preferred repayment frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EzeeAPIWithDocTest.cls
@isTest
public class EzeeAPIWithDocTest {

    @isTest
    public static void methodOne(){
        opportunity op1 = new Opportunity()	;
        op1.Name = 'testing';
        op1.Preferred_repayment_frequency__c = 'Monthly';  
        op1.Loan_Amount__c = 560;
        op1.StageName = 'Working';
        op1.Lender_Application_ID__c = '12345678dgy4567';
        op1.Application_Supporting_Notes__c = 'hello';
        op1.CloseDate = System.today();
        insert op1;      
        
        
        EzeeAPIWithDOc.makeCallout(op1.Id);
        
        Document_Requested__c dc1 = new Document_Requested__c();
        dc1.Category__c = 'Credit Report';
        dc1.Opportunity__c = op1.Id;
      	insert dc1;  
        
        
        
        List<ContentVersion> cvList = new List<ContentVersion>();
        
        ContentVersion cvv=new Contentversion();
        cvv.title='text';
        cvv.PathOnClient ='text.png';
        cvv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cvv.IsMajorVersion = false;
        cvv.Document_Requested__c = dc1.id;
        cvv.Send_to_Lender__c = true;
       	insert cvv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument LImit 5];
        
        System.debug('documents_+'+documents);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = op1.id;
        
        cdl.ContentDocumentId = documents[0].Id;
        
        cdl.shareType = 'V';
        
        Insert cdl;        

        EzeeAPIWithDoc.uploadDocu(op1.Id);
    }
    
    @isTest
    public static void methodTwo(){
        opportunity op1 = new Opportunity()	;
        op1.Name = 'testing';
        op1.Preferred_repayment_frequency__c = 'Monthly';  
        op1.Loan_Amount__c = 560;
        op1.StageName = 'Working';
        op1.Lender_Application_ID__c = '12345678dgy4567';
        op1.Application_Supporting_Notes__c = 'hello';
        op1.CloseDate = System.today();
        insert op1;      
        
        
        
        Document_Requested__c dc1 = new Document_Requested__c();
        dc1.Category__c = 'Identification';
        dc1.Opportunity__c = op1.Id;
      	insert dc1;  
        
        
        
        List<ContentVersion> cvList = new List<ContentVersion>();
        
        ContentVersion cvv=new Contentversion();
        cvv.title='text';
        cvv.PathOnClient ='text.png';
        cvv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cvv.IsMajorVersion = false;
        cvv.Document_Requested__c = dc1.id;
        cvv.Send_to_Lender__c = true;
       	insert cvv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument LImit 5];
        
        System.debug('documents_+'+documents);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = op1.id;
        
        cdl.ContentDocumentId = documents[0].Id;
        
        cdl.shareType = 'V';
        
        Insert cdl;        

        EzeeAPIWithDoc.uploadDocu(op1.Id);
    }
    
    
    @isTest
    public static void methodThree(){
        opportunity op1 = new Opportunity()	;
        op1.Name = 'testing';
        op1.Preferred_repayment_frequency__c = 'Monthly';  
        op1.Loan_Amount__c = 560;
        op1.StageName = 'Working';
        op1.Lender_Application_ID__c = '12345678dgy4567';
        op1.Application_Supporting_Notes__c = 'hello';
        op1.CloseDate = System.today();
        insert op1;      
        
        contact con = new Contact();
        con.FirstName = 'test';
        con.LastName = 'test';
        insert con;
        
        try{
        	EzeeAPIWithDOc.makeCallout(con.Id);    
        }Catch(Exception ex){
            System.debug('mesage '+ex.getMessage());
        }
        
        
        Document_Requested__c dc1 = new Document_Requested__c();
        dc1.Category__c = 'Assets';
        dc1.Opportunity__c = op1.Id;
      	insert dc1;  
        
        
        
        List<ContentVersion> cvList = new List<ContentVersion>();
        
        ContentVersion cvv=new Contentversion();
        cvv.title='text';
        cvv.PathOnClient ='text.png';
        cvv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cvv.IsMajorVersion = false;
        cvv.Document_Requested__c = dc1.id;
        cvv.Send_to_Lender__c = true;
       	insert cvv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument LImit 5];
        
        System.debug('documents_+'+documents);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = op1.id;
        
        cdl.ContentDocumentId = documents[0].Id;
        
        cdl.shareType = 'V';
        
        Insert cdl;        

        EzeeAPIWithDoc.uploadDocu(op1.Id);
    }
    
    
}