force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Government_ID__c.field-meta.xml
<CustomField>
    <fullName>Government_ID__c</fullName>
    <label>Government ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>driving licence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Govt_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Govt_Id_Number__c</fullName>
    <label>Govt Id Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Residential_Address__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address__c</fullName>
    <label>Residential Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code_Orignal__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code_Orignal__c</fullName>
    <label>Secure Code Orignal</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/link_Expire_code__c.field-meta.xml
<CustomField>
    <fullName>link_Expire_code__c</fullName>
    <label>link Expire code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Digital_ID_Sign_For_Reffer_Test.cls
@isTest
public class Digital_ID_Sign_For_Reffer_Test {
    @isTest
    public static void TestForDigital(){
        
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();        
        
        contact con = new contact();
        con.firstname = 'qwert';
        con.lastName = 'testing';
        con.Email = 'tazeem.khan@chazecloud.com';
        insert con;
        
        Account Accnew = new Account();
        Accnew.Name = 'testing';
        Accnew.RecordTypeId = accRTId;
        insert Accnew;
        
        Test.setCurrentPageReference(new PageReference('Page.Digital_ID_Sign')); 
        System.currentPageReference().getParameters().put('id', Accnew.id);
        System.currentPageReference().getParameters().put('conId', con.id);
        System.currentPageReference().getParameters().put('SecureCode', '12345');
        
        
        
        VOI_Status__c voiS = new VOI_Status__c();
        voiS.link_Expire_code__c = '12345';
        voiS.Contact__c = con.Id;
        insert voiS;
        
        
         
        Digital_ID_Sign_For_Reffer.securecode();
        Digital_ID_Sign_For_Reffer.VOIDetailID();
        
        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        Blob b=Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        
        
        PageReference pageRef = Page.DIgitalSignReferrer; // Add your VF page Name here
        pageRef.getParameters().put('imageDeta', String.valueOf(cv.Id));
        pageRef.getParameters().put('sign1', String.valueOf(cv.Id));
        pageRef.getParameters().put('videoData', String.valueOf(cv.Id));
        Test.setCurrentPage(pageRef);
        
        Digital_ID_Sign_For_Reffer.ImageDataforClass();
        
        Digital_ID_Sign_For_Reffer.Sign1DataforClass();
        Digital_ID_Sign_For_Reffer.videoDataforClass();
        Digital_ID_Sign_For_Reffer.generateLog();
        
        
        
        VOI_Detail__c obj  = new VOI_Detail__c();
        obj.Secure_Code_Orignal__c = '1234';
        obj.Contact__c = con.Id;
        insert obj;
        
        Digital_ID_Sign_For_Reffer.FetchContact(obj.id);
        Digital_ID_Sign_For_Reffer.sendImageDataToComponent(obj.id);
        
        contact cont = new contact();
        cont.LastName = 'testing';
        cont.AccountId = Accnew.id;
        cont.Birthdate = system.today();
        cont.Government_ID__c = 'card';
        cont.Govt_Id_Number__c = '32417239';
        cont.FinServ__Gender__c = 'male';
        cont.Residential_Address__c = 'testing';
        insert cont;
        
        
        Digital_ID_Sign_For_Reffer.UpdateOppCon(cont);
        
        Digital_ID_Sign_For_Reffer.insertPdf();
        
        Digital_ID_Sign_For_Reffer obj54 = new Digital_ID_Sign_For_Reffer();
        Digital_ID_Sign_For_Reffer.sendEmail();
        
    }
}