force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_View__c.field-meta.xml
<CustomField>
    <fullName>Portal_View__c</fullName>
    <label>Portal View</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin View</fullName>
            </value>
            <value>
                <fullName>Referrer View</fullName>
                <default>true</default>
                <label>Referrer View</label>
            </value>
            <value>
                <fullName>Agent View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Lead/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Referrals</relationshipLabel>
    <relationshipName>Referral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Lead Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/SolarLoanHomeControllerTest.cls
@istest
public class SolarLoanHomeControllerTest {
    @testsetup
    static void setUpData(){
        String recordTypeRefId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recid = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Green Loan').getRecordTypeId();
        String LeadRecordType = Schema.getGlobalDescribe().get('Lead').getDescribe().getRecordTypeInfosByName().get('Green Loan').getRecordTypeId();
        
        Account testAcc = new Account();
        testAcc.RecordTypeId  = recordTypeRefId;
        testAcc.Name = 'TestRef Account'; 
        insert testAcc;
        
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'Test';
        testAcc1.LastName = 'Opportunity 1';
        testAcc1.Phone = '1234567890';
        testAcc1.PersonEmail = 'opp1@test.com';
        
        insert testAcc1;
        
        Contact testCon = new Contact();
        testCon.FirstName = 'TestRef';
        testCon.LastName = 'Contact';
        testCon.AccountId = testAcc.Id;
        testCon.Admin__c = true;
        testCon.Portal_View__c = 'Admin View';
        testCon.Phone ='0412568868';
        insert testCon;
        
        Opportunity testOpp1 = new Opportunity();
        testOpp1.Name = 'Test Opportunity 1';
        testOpp1.FinServ__ReferredByContact__c = testCon.Id;
        testOpp1.StageName ='Approved';
        testOpp1.CloseDate = System.Today();
        testOpp1.Applicant_1__c = testAcc1.Id;
        testOpp1.Loan_Amount__c = 22000;
        insert testOpp1;
    }
    @istest
    public static void Test1(){
        String testLbl = Label.Credit_analyst;
        Profile pf= [Select Id from profile where Name='System Administrator'];
        /*User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = 'test@gmail.com', 
                         Username =  ' john@accc.com',  
                         ProfileId = pf.Id
                        ); 
        insert uu;*/
        Opportunity Opp = [SELECT Id,Name From Opportunity where name ='Test Opportunity 1' LIMIT 1];
        apexpages.currentpage().getparameters().put('id', Opp.Id);
        SolarLoanHomeController sl = new SolarLoanHomeController();
        SolarLoanHomeController.getOpponPriorties(Opp.id);
    }
}