force-app/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/A1_Funding_Call_Handover__c.field-meta.xml
<CustomField>
    <fullName>A1_Funding_Call_Handover__c</fullName>
    <label>A1 Funding Call Handover</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/A2_Funding_Call_Handover__c.field-meta.xml
<CustomField>
    <fullName>A2_Funding_Call_Handover__c</fullName>
    <label>A2 Funding Call Handover</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_1_A1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_A1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 1 (A1)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_2_A2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_A2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2 (A2)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Applicant 2 (A2))</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 1)</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 2)</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Support Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public class TaskTriggerHandler {
    public void UpdateFundingHandOverTasks(List<Task> newTasks){ 
        List<Funding_Request__c> frListToUpdate = new List<Funding_request__c>();
        map<Id,Id> mapOfTaskFunding = new Map<Id,Id>();
        String FundingHandoverTskDesc = 'IMPORTANT: If the funding handover call is successful, you must mark ‘Sales outcome’ fields = Successful. An SMS will automatically be sent if you save this task as successful with instructions to call the lender back and to let you know if the call was successful.';
        for(Task tk : newTasks){
            system.debug('tkDescription'+tk.Description);
            if(tk.Description != null && FundingHandoverTskDesc.contains(tk.Description) && tk.Status == 'Completed' && tk.Outcome__c == 'Successful'){
                mapOfTaskFunding.put(tk.WhatId,tk.WhoId);
            }  
        } 
        
        if(!mapOfTaskFunding.isEmpty()){
            List<Funding_Request__c> frList = [SELECT Id,Opportunity__c,Applicant_1_A1__r.Name,Applicant_2_A2__r.Name,Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId,A1_Funding_Call_Handover__c,
                                               Opportunity__r.Customer_Support_Person__r.Name,A2_Funding_Call_Handover__c,Opportunity__r.SyncedQuote.Product__r.Lender_phone_number__c,Applicant_1_A1__r.Phone,
                                               Opportunity__r.Contact_1__c,Opportunity__r.Contact_2__c,Applicant_2_A2__r.Phone FROM Funding_Request__c WHERE Id IN: mapOfTaskFunding.keySet()];
            if(!frList.isEmpty()){
                for(Funding_Request__c fr : frList){
                    if(mapOfTaskFunding.get(fr.Id) == fr.Applicant_1_A1__r.PersonContactId){
                        fr.A1_Funding_Call_Handover__c = System.now();
                        frListToUpdate.add(fr);
                        String smsTextforApp1 = 'Hi '+fr.Applicant_1_A1__r.Name+', '+fr.Opportunity__r.Customer_Support_Person__r.Name+ ' here at Parker Lane.';
                        smsTextforApp1 += ' As promised here the number to call back in case the call gets disconnected ';
                        smsTextforApp1 += fr.Opportunity__r.SyncedQuote.Product__r.Lender_phone_number__c+'. Please shoot me a reply once you’ve ';
                        smsTextforApp1 += 'authorised payment so you don’t receive anymore reminders. And have a great day! ';
                        String SenderId = system.label.SMS_Sender_Id;
                        SMSController.sendApproveExpireMessage('Contact', SenderId,fr.Applicant_1_A1__r.Name,fr.Applicant_1_A1__r.Phone, smsTextforApp1,fr.Opportunity__c,fr.Opportunity__r.Contact_1__c );
                    }  
                    if(fr.Applicant_2_A2__c != null && mapOfTaskFunding.get(fr.Id) == fr.Applicant_2_A2__r.PersonContactId){
                        system.debug('Heloooo2');
                        fr.A2_Funding_Call_Handover__c = System.now();
                        frListToUpdate.add(fr);
                        String smsTextforApp2 = 'Hi '+fr.Applicant_2_A2__r.Name+', '+fr.Opportunity__r.Customer_Support_Person__r.Name+ ' here at Parker Lane.';
                        smsTextforApp2 += ' As promised here the number to call back in case the call gets disconnected ';
                        smsTextforApp2 += fr.Opportunity__r.SyncedQuote.Product__r.Lender_phone_number__c+'. Please shoot me a reply once you’ve ';
                        smsTextforApp2 += 'authorised payment so you don’t receive anymore reminders. And have a great day! ';
                        String SenderId = system.label.SMS_Sender_Id;
                        SMSController.sendApproveExpireMessage('Contact', SenderId,fr.Applicant_2_A2__r.Name,fr.Applicant_2_A2__r.Phone, smsTextforApp2,fr.Opportunity__c,fr.Opportunity__r.Contact_2__c );
                    }  
                }
            }
        }
        
        if(!frListToUpdate.isEmpty()){
            Update frListToUpdate;
        } 
    }
}