force-app/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Loan_Fees__c/Loan_Fees__c.object-meta.xml
<CustomObject>
    <label>Loan Fees</label>
    <nameField>
        <label>Loan Fees</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fees__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Exit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product_Loan_Fees__c.field-meta.xml
<CustomField>
    <fullName>Product_Loan_Fees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Loan Fees</label>
    <referenceTo>Loan_Fees__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/Loan_Rate__c.object-meta.xml
<CustomObject>
    <label>Loan Rate</label>
    <nameField>
        <label>Loan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Rate__c/fields/Comparison_rate__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/From_amount__c.field-meta.xml
<CustomField>
    <fullName>From_amount__c</fullName>
    <label>From amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/Interest_rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_rate__c</fullName>
    <label>Interest rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Rates</relationshipLabel>
    <relationshipName>Loan_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/To_amount__c.field-meta.xml
<CustomField>
    <fullName>To_amount__c</fullName>
    <label>To amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Default_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Default_Loan_Term__c</fullName>
    <label>Default Loan Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestUpdateQuotesByProductBatch.cls
@isTest
public class TestUpdateQuotesByProductBatch {
    
    static testMethod void testUpdateQuotesByProduct() {
        Product2 product = new product2();   
        product.Name='Test Product';
        product.Interest_Rate__c=3.5; 
        product.Actual_Comparison_Rate__c=4.0;
        product.Commission_Amount__c=100.0;
        product.Brokerage_Amount__c=200;
        product.Default_Loan_Term__c = 8;
        product.Lender__c='Test Lender';
        
        insert product;
        
        Loan_Fees__c loanFeeq = new Loan_Fees__c();
        loanFeeq.Amount__c=5000;
        loanFeeq.Fee_Type__c='Account Keeping';
        loanFeeq.Frequency__c='Setup';
        loanFeeq.Product__c = product.id;
        insert loanFeeq;
        
        
        Opportunity opp = new Opportunity();
        opp.Name='Test Opportunity';
        opp.StageName='Working';
        opp.CloseDate=System.today();  
        insert opp;
        
        Quote quote = new Quote();
        quote.Name='Test Quote';
        quote.Customer_Amount__c=8000;
        quote.OpportunityId=opp.Id;
        quote.Product__c=product.Id;
        quote.Loan_Term__c = 80;
        
        insert quote;
        
        Loan_Rate__c loanRate = new Loan_Rate__c();
        loanRate.Interest_rate__c=3.0;
        loanRate.From_amount__c=1000; 
        loanRate.To_amount__c=10000; 
        loanRate.Comparison_rate__c=3.5;
        loanRate.Product__c=product.Id;
        insert loanRate;
        
        Loan_Fees__c loanFee = new Loan_Fees__c();
        loanFee.Amount__c=5000;
        loanFee.Fee_Type__c='Account Keeping';
        loanFee.Frequency__c='Setup';
        loanFee.Quote__c = quote.id;
        loanFee.Product_Loan_Fees__c = loanFeeq.Id;
        insert loanFee;
        
        test.startTest();
        updateQuotesByProductBatch obj = new updateQuotesByProductBatch(product.Id);
        database.executeBatch(obj,50);
        test.stopTest();
        
        Quote updatedQuote = [SELECT Id,Name,product__r.Name, Actual_Comparison_Rate__c, Interest_Rate__c,
                              Loan_Term__c, Commission_Amount__c, Brokerage_Amount__c, Lender__c 
                              FROM Quote WHERE Id=:quote.Id  ];
        
    }
    
}