force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Anticipate_intro_finance_to_customer__c.field-meta.xml
<CustomField>
    <fullName>Anticipate_intro_finance_to_customer__c</fullName>
    <label>Anticipate intro finance to customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Frequently</fullName>
            </value>
            <value>
                <fullName>Occasionally</fullName>
            </value>
            <value>
                <fullName>Only when asked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Are_you_Clean_Energy_Council_Accredited__c.field-meta.xml
<CustomField>
    <fullName>Are_you_Clean_Energy_Council_Accredited__c</fullName>
    <label>Are you Clean Energy Council Accredited</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Legal_Name__c</fullName>
    <label>Company Legal Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/General_Business_Description__c.field-meta.xml
<CustomField>
    <fullName>General_Business_Description__c</fullName>
    <label>General Business Description</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/How_do_you_conduct_your_appointment__c.field-meta.xml
<CustomField>
    <fullName>How_do_you_conduct_your_appointment__c</fullName>
    <label>How do you conduct your appointment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to face</fullName>
            </value>
            <value>
                <fullName>Phone call</fullName>
            </value>
            <value>
                <fullName>Video call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/How_many_new_sales_appointments_per_week__c.field-meta.xml
<CustomField>
    <fullName>How_many_new_sales_appointments_per_week__c</fullName>
    <label>How many new sales appointments per week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-10</fullName>
            </value>
            <value>
                <fullName>10-50</fullName>
            </value>
            <value>
                <fullName>50-100</fullName>
            </value>
            <value>
                <fullName>100+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Find_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_Find_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Find Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_1__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_1__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_2__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_2__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_3__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_3__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Listing_URL__c.field-meta.xml
<CustomField>
    <fullName>Listing_URL__c</fullName>
    <label>Listing URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Business_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Other_Business_Type_Description__c</fullName>
    <label>Other Business Type Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Business_Type__c</fullName>
    <label>Referrer Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar Installer</fullName>
            </value>
            <value>
                <fullName>Solar Retailer</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Builder Referrer</fullName>
            </value>
            <value>
                <fullName>Website Referrer</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Home improvement retailer</fullName>
            </value>
            <value>
                <fullName>Home improvement installer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Aggregator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_1__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_1__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_2__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_2__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_3__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_3__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Company Secretary</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferrerOnboardingFormControllerTest.cls
@istest
public class ReferrerOnboardingFormControllerTest {
	@testsetup
    static void setUpData(){
       
        Account acc= new Account(
            Name='Test Name',
            phone='1234567890',
            ABN__c = 'qwerty'
        );
        
        insert acc;
        
        Contact con = New Contact(
            FirstName = 'first',
            LastName = 'last',
            phone = '1234567890',
            email = 'first@last.com',
            Position__c ='Sales',
            AccountId = acc.Id
        );
        insert con;
    }
    
    static testmethod void getReferrerOnboardingFormTest(){
        Account accList = [SELECT Id FROM Account Where Name = 'Test Name'];
        apexpages.currentpage().getparameters().put('id', accList.Id);
        ReferrerOnboardingFormController rofCtrl = New ReferrerOnboardingFormController();
        
        System.assertEquals(rofCtrl.acc.Id, accList.Id, 'value should be same');
    }
    
    static testmethod void getSaveReferrer(){
        Account acc= new Account(
            Name='Test Name',
            phone='1234567890',
            ABN__c = 'qwerty'
        );
        
        Contact con = New Contact(
            FirstName = 'first',
            LastName = 'last',
            phone = '1234567890',
            email = 'first@last.com',
            Position__c ='Sales'
        );
        Account accResult = ReferrerOnboardingFormController.saveReferrer(acc, con);
        System.assertEquals(accResult.Contacts.size(), 1, 'value should be same');
    }
    
    static testmethod void getSubmitReferrer(){
        Account acctr= new Account(
            Name='Test Name',
            phone='1234567890',
            ABN__c = 'qwerty'
        );
        Contact con = New Contact(
			Account = acctr,
            FirstName = 'first',
            LastName = 'last',
            phone = '1234567890',
            email = 'first@last.com',
            Position__c ='Sales'
        );
        
		Account acc = [SELECT Id, Name, ABN__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Company_Legal_Name__c,
                   Referrer_Business_Type__c, Other_Business_Type_Description__c, Is_Find_Billing_Address__c, Website, Are_you_Clean_Energy_Council_Accredited__c,
                   Listing_URL__c,How_many_new_sales_appointments_per_week__c,How_do_you_conduct_your_appointment__c, Anticipate_intro_finance_to_customer__c,
                   General_Business_Description__c, Unique_Value_Proposition_1__c, Unique_Value_Proposition_2__c, Unique_Value_Proposition_3__c,
                   Key_Accreditations_1__c, Key_Accreditations_2__c, Key_Accreditations_3__c,
                   (SELECT Id, FirstName, LastName, Email, Phone, Position__c FROM Contacts)
                   FROM Account WHERE Name ='Test Name'];
        Account accResult = ReferrerOnboardingFormController.submitReferrer(acc, acc.Contacts, false);
        ReferrerOnboardingFormController.createEnvelope(acc.Id);
    }
}