force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Company Secretary</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Current_in_use__c.field-meta.xml
<CustomField>
    <fullName>Current_in_use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current (in use)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Referral_AgreementTest.cls
@istest
public class Referral_AgreementTest {
    @testsetup
    static void setUpData(){
        
        Account acc= new Account(
            Name='Test Name',
            phone='1234567890',
            ABN__c = 'qwerty'
        );        
        insert acc;
        
        Contact con = New Contact(
            FirstName = 'first',
            LastName = 'last',
            phone = '1234567890',
            email = 'first@last.com',
            Position__c ='Sales',
            AccountId = acc.Id
        );
        insert con;
        
        ContentVersion testContentVersion = new ContentVersion(
            Title = 'Sign',
            VersionData = Blob.valueOf('Test Content Data'),
            PathOnClient = 'TestContent.txt',
            ContentLocation = 'S',
            Current_in_use__c = true
        ); 
        insert testContentVersion;
        
        ContentDocumentLink link = new ContentDocumentLink(
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContentVersion.Id].ContentDocumentId,
            LinkedEntityId = con.Id,
            ShareType = 'I'
        );
        insert link;
    }
    
    static testmethod void getReferral_Agreement(){
        Contact ConData = [SELECT Id,Name,AccountId FROM Contact where email =: 'first@last.com' order by createddate DESC LIMIT 1];        
        Account accList = [SELECT Id FROM Account Where id =: ConData.AccountId];
        apexpages.currentpage().getparameters().put('id', accList.Id);
        apexpages.currentpage().getparameters().put('ConId', ConData.Id);
        Referral_Agreement rofCtrl = New Referral_Agreement();
        Referral_Agreement.generateImageURL();
    }
}