force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Legal_Name__c</fullName>
    <label>Company Legal Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Age_Child_1__c.field-meta.xml
<CustomField>
    <fullName>Age_Child_1__c</fullName>
    <label>Age Child 1</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_Child_2__c.field-meta.xml
<CustomField>
    <fullName>Age_Child_2__c</fullName>
    <label>Age Child 2</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_Child_3__c.field-meta.xml
<CustomField>
    <fullName>Age_Child_3__c</fullName>
    <label>Age Child 3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age_Child_4__c.field-meta.xml
<CustomField>
    <fullName>Age_Child_4__c</fullName>
    <label>Age Child 4</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>Citizenship_Status__c</fullName>
    <label>Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australian Citizen</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>NZ Citizen</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Does_your_spouse_earn_an_income__c.field-meta.xml
<CustomField>
    <fullName>Does_your_spouse_earn_an_income__c</fullName>
    <label>Does your spouse earn an income</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/FinServ__MaritalStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__MaritalStatus__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Married / defacto</fullName>
            </value>
            <value>
                <fullName>Married / Defacto (to applicant 2)</fullName>
            </value>
            <value>
                <fullName>Married / Defacto (to applicant 1)</fullName>
            </value>
            <value>
                <fullName>Married / defacto (non-applicant)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Name_Child_1__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Child_1__c</fullName>
    <label>First Name Child 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Name_Child_2__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Child_2__c</fullName>
    <label>First Name Child 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Name_Child_3__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Child_3__c</fullName>
    <label>First Name Child 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Name_Child_4__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Child_4__c</fullName>
    <label>First Name Child 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_Name_Child_5__c.field-meta.xml
<CustomField>
    <fullName>First_Name_Child_5__c</fullName>
    <label>First Name Child 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Government_ID__c.field-meta.xml
<CustomField>
    <fullName>Government_ID__c</fullName>
    <label>Government ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>driving licence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Govt_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Govt_Id_Number__c</fullName>
    <label>Govt Id Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Authorised_Signatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Authorised Signatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Medicare_Reference__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Reference__c</fullName>
    <label>Medicare Reference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Company Secretary</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Employer_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Employer_Job_Title__c</fullName>
    <label>Primary Employer Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rental_Amount__c</fullName>
    <label>Rental Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Rental_Frequency__c</fullName>
    <label>Rental Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_Managed_via__c.field-meta.xml
<CustomField>
    <fullName>Rental_Managed_via__c</fullName>
    <label>Rental Managed via</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real estate agent</fullName>
            </value>
            <value>
                <fullName>Privately</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Rental_or_Board_paid__c.field-meta.xml
<CustomField>
    <fullName>Rental_or_Board_paid__c</fullName>
    <label>Rental or Board paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Residential_Address__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address__c</fullName>
    <label>Residential Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spouse_s_approximate_annual_income__c.field-meta.xml
<CustomField>
    <fullName>spouse_s_approximate_annual_income__c</fullName>
    <label>spouse’s approximate annual income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Visa_Details__c.field-meta.xml
<CustomField>
    <fullName>Visa_Details__c</fullName>
    <label>Visa Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>Exceptions</relationshipLabel>
    <relationshipName>Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code_Orignal__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code_Orignal__c</fullName>
    <label>Secure Code Orignal</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/link_Expire_code__c.field-meta.xml
<CustomField>
    <fullName>link_Expire_code__c</fullName>
    <label>link Expire code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Digital_ID_Sign_For_Reffer.cls
global without sharing class Digital_ID_Sign_For_Reffer {
    
    public static final string ConId = ApexPages.currentPage() != null ? ApexPages.currentPage().getParameters().get('conId') : '';
    public static final string SecureCode = ApexPages.currentPage() != null ? ApexPages.currentPage().getParameters().get('r') : '';
    public static final string accId = ApexPages.currentPage() != null ? apexpages.currentpage().getparameters().get('id') : '';
    
    
    public Account acc{get;Set;}
    public static string ApplicantName{get;set;}
    
    public static string Amount{get; set;}
    public static Boolean IsApplicantTwo {get;set;}
    public static String SecureCodeOriginal {get; set;}
    public static string FolderId {get; set;}
    //public static string ApplicantsToSign {get; set;}
    public static String signId {get; set;} 
    public static String ImageSrc {get; set;}
    public static boolean redirectToError {get; set;}
    public static string secApplicantName {get; set;}
     public static string message {get;set;}
    
    
    //upload video to drive
    
    
    public Digital_ID_Sign_For_Reffer(){
        try{
            
            acc = New Account();
            if(String.isNotBlank(accId)){
                acc = [SELECT Id, ABN__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Company_Legal_Name__c, 
                       (SELECT Id, FirstName, LastName, Name, Position__c FROM Contacts WHERE Is_Authorised_Signatory__c =true LIMIT 1)
                       FROM Account WHERE id =: accId];
            }
            showError();
            IsApplicantTwo = false;
            
        }catch(Exception ex){
        	System.debug('exception>>>'+ex.getMessage() + ' ' + ex.getLineNumber());
        }
    }
    
    public static void securecode(){
        System.debug('SecureCodeSecureCode --------'+SecureCodeOriginal);
        //opportunity opp = [select id, Name, Applicant_1__r.PersonContactId from opportunity where Id = : OppId];
        
        VOI_Detail__c obj  = new VOI_Detail__c();
        obj.Secure_Code_Orignal__c = SecureCodeOriginal;
        obj.Contact__c = ConId;
        insert obj;
        
        VOI_Status__c temp = [select Id, name,link_Expire_code__c, contact__c from VOI_Status__c WHERE Contact__r.Id =: ConId order by createddate DESC LIMIT 1];
        
        temp.VOI_Detail__c = obj.id;
        
        update temp;
    }
    
    
    public static void showError(){
        
        List<VOI_Status__c> temp = [select Id, name,link_Expire_code__c, contact__c from VOI_Status__c WHERE Contact__r.Id =: ConId order by createddate DESC LIMIT 1];
        
        if(temp != null){
            if(temp.size() > 0){
                if(SecureCode != temp[0].link_Expire_code__c){
                    redirectToError = true;
                }
                else{
                    redirectToError = false;
                }        
            }
        }
        
        
    }
    
    
    
    
    public static id VOIDetailID(){
        VOI_Detail__c obj = [SELECT Id, Name, Contact__r.Id from VOI_Detail__c WHERE Contact__r.Id = : ConId order by createddate DESC LIMIT 1];
        
        return obj.Id;
    }
    
    
    
    
    public static PageReference ImageDataforClass(){
        string Imagedata = Apexpages.currentPage().getParameters().get('imageDeta');	
        Imagedata = Imagedata.substring(Imagedata.indexOf(',')+1,Imagedata.length());
        System.debug('Image Dtaa'+Imagedata);
        Set<Id> CDId = new Set<Id>();
        
        for(ContentDocumentLink Cd : [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :VOIDetailID() AND ContentDocument.Title = 'DlFront' LIMIT 1]){
            CDId.add(Cd.ContentDocumentId);
        }
        System.debug('CDId--->'+CDId);
        if(CDId != null && CDId.size() > 0){
            ContentVersion Cd = [SELECT ContentDocumentId,VersionData FROM ContentVersion WHERE ContentDocumentId IN: CDId AND Title = 'DlFront' LIMIT 1];
            cd.VersionData = EncodingUtil.base64Decode(Imagedata);
            System.debug('inside the IF');
            update cd;			
        }else{
            ContentVersion ContVerFile = new ContentVersion();
            ContVerFile.VersionData = EncodingUtil.base64Decode(Imagedata);
            ContVerFile.Title = 'DlFront'; 
            ContVerFile.PathOnClient='DlFront.jpeg';
            ContVerFile.IsMajorVersion = false;
            insert ContVerFile;
            SYstem.debug('ContVerFile id '+ContVerFile.Id);
            List<ContentVersion> conDocId = new List<ContentVersion>();
            
            
            conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ContVerFile.Id];
            System.debug('conDocId : '+conDocId[0].ContentDocumentId);
            
            ContentDocumentLink cdl = New ContentDocumentLink();
            
            
            cdl.LinkedEntityId = VOIDetailID();
            
            cdl.ContentDocumentId = conDocId[0].ContentDocumentId;
            
            cdl.shareType = 'V';
            cdl.Visibility = 'AllUsers';
            
            Insert cdl;
            
        }
        return null;
    }
    
    public static PageReference videoDataforClass(){
       try{
            string videoData = Apexpages.currentPage().getParameters().get('videoData');
            system.debug('+++++++++++'+videoData);
            videoData = videoData.substring(videoData.indexOf(',')+1,videoData.length());
            System.debug('Image Dtaa'+videoData);
            Set<Id> CDId = new Set<Id>();
            
            for(ContentDocumentLink Cd : [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = : VOIDetailID() AND ContentDocument.Title = 'video' LIMIT 1]){
                CDId.add(Cd.ContentDocumentId);
            }
            System.debug('CDId--->'+CDId);
            if(CDId != null && CDId.size() > 0){
                ContentVersion Cd = [SELECT ContentDocumentId,VersionData FROM ContentVersion WHERE ContentDocumentId IN: CDId AND Title = 'video' LIMIT 1];
                cd.VersionData = EncodingUtil.base64Decode(videoData);
                System.debug('inside the IF');
                update cd;			
            }else{
                ContentVersion ContVerFile = new ContentVersion();
                ContVerFile.VersionData = EncodingUtil.base64Decode(videoData);
                ContVerFile.Title = 'video'; 
                ContVerFile.PathOnClient='video.mp4';
                ContVerFile.IsMajorVersion = false;
                insert ContVerFile;
                SYstem.debug('ContVerFile id '+ContVerFile.Id);
                List<ContentVersion> conDocId = new List<ContentVersion>();
                
                
                conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ContVerFile.Id];
                System.debug('conDocId : '+conDocId[0].ContentDocumentId);
                
                ContentDocumentLink cdl = New ContentDocumentLink();
                
                
                cdl.LinkedEntityId = VOIDetailID();
                
                cdl.ContentDocumentId = conDocId[0].ContentDocumentId;
                
                cdl.shareType = 'V';
                cdl.Visibility = 'AllUsers';
                
                Insert cdl; 
            }
        }catch(Exception e){
             message = e.getMessage() + ' ' + e.getLineNumber() + ' ' + e.getTypeName();
        }
        
        return null;
    }
    
    public static PageReference Sign1DataforClass(){
        string Imagedata = Apexpages.currentPage().getParameters().get('sign1');	
        Imagedata = Imagedata.substring(Imagedata.indexOf(',')+1,Imagedata.length());
        ContentVersion ContVerFile = new ContentVersion();
        ContVerFile.VersionData = EncodingUtil.base64Decode(Imagedata);
        ContVerFile.Title = 'Sign1'; 
        ContVerFile.PathOnClient='Sign1.jpeg';
        insert ContVerFile;
        SYstem.debug('ContVerFile id '+ContVerFile.Id);
        List<ContentVersion> conDocId = new List<ContentVersion>();
        
        conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ContVerFile.Id];
        System.debug('conDocId : '+conDocId[0].ContentDocumentId);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = VOIDetailID();
        
        cdl.ContentDocumentId = conDocId[0].ContentDocumentId;
        
        cdl.shareType = 'V';
        cdl.Visibility = 'AllUsers';
        
        Insert cdl;
        
        return null;
    }
    
    
    @AuraEnabled 
    public static String sendImageDataToComponent(string RecId){
        System.debug('================================='+RecId);
        string temp;
        list<String> VersionDataList = new List<String>();
        Set<Id> CDId = new Set<Id>();
        
        for(ContentDocumentLink Cd : [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = : RecId AND ContentDocument.Title = 'title' LIMIT 1]){
            CDId.add(Cd.ContentDocumentId);
        }
        System.debug('CDId--->'+CDId);
        
        for(ContentVersion Cd : [SELECT ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN : CDId AND Title = 'title' order by createddate DESC LIMIT 1]){
            VersionDataList.add(Cd.ContentDocumentId);
        }
        System.debug('VersionDataList'+VersionDataList);
        if(VersionDataList != null){
            if(VersionDataList.size() > 0){
                temp = VersionDataList[0];
            }
        }
        
        
        return temp;
    }
    
    
    
    @AuraEnabled 
    public static Contact FetchContact(Id recordId){
        system.debug('recordId'+recordId);
        
        VOI_Detail__c voi = [select Id, Name, contact__r.Id From VOI_Detail__c WHERE Id = : recordId];
        
        system.debug('recordId'+voi.contact__r.Id);
        
        Contact con = [SELECT Name, Medicare_Reference__c, FirstName,AccountId, LastName,Govt_Id_Number__c, MiddleName,Does_your_spouse_earn_an_income__c,spouse_s_approximate_annual_income__c, Email, Phone, Title, Birthdate,FinServ__Occupation__c,Account.Industry,Primary_Employer_Job_Title__c, 
                       OtherPhone, FinServ__Gender__c,Rental_or_Board_paid__c, FinServ__MaritalStatus__c, Government_ID__c,
                       Rental_Amount__c, Rental_Frequency__c, Rental_Managed_via__c, Citizenship_Status__c, Visa_Details__c,
                       First_Name_Child_1__c, Residential_Address__c,First_Name_Child_2__c, First_Name_Child_3__c, First_Name_Child_4__c, First_Name_Child_5__c,
                       Age_Child_1__c, Age_Child_2__c, Age_Child_3__c, Age_Child_4__c, Age_Child_5__c,Medicare_Card_Colour__c,
                       Medicare_Expiry_Date__c,Medicare_Number__c,Monthly_Rental_Payments__c,Other_Regular_Expenditure__c
                       FROM Contact WHERE id =: voi.contact__r.Id];
        con.birthdate = null;
        con.Government_ID__c = '';
        con.Govt_Id_Number__c = '';
        con.FinServ__Gender__c = '';
        
        return con;
    }
    
    @AuraEnabled 
    public static void UpdateOppCon(Contact cont){
        System.debug('contId : ::::'+cont.AccountId);
        System.debug('contId : ::::'+cont.Government_ID__c);
        Contact con = new Contact();
        con.Id = cont.Id;
        con.Birthdate = cont.Birthdate;
        con.Government_ID__c = cont.Government_ID__c;
        con.Govt_Id_Number__c = cont.Govt_Id_Number__c;
        con.FinServ__Gender__c = cont.FinServ__Gender__c;
        con.Residential_Address__c = cont.Residential_Address__c;
        con.Driver_s_licence_state_Territory__c = cont.Driver_s_licence_state_Territory__c;
        update con;
    }
    
    public static void insertPdf(){
        PageReference pdf = Page.Digital_Reffer_PDF;
        pdf.getParameters().put('id',accId);
        pdf.getParameters().put('ConId',ConId);
        pdf.setRedirect(true);
        Blob bPDF;
        
        if (Test.IsRunningTest())
        {
            bPDF=Blob.valueOf('UNIT.TEST');
        }
        else
        {
            bPDF = pdf.getContent();
        }
        
        ContentVersion ContVerFile = new ContentVersion();
        ContVerFile.VersionData = bPDF;
        ContVerFile.Title = 'Signed Referral Agreement'; 
        ContVerFile.PathOnClient='Signed Referral Agreement.Pdf';
        insert ContVerFile;
        SYstem.debug('ContVerFile id '+ContVerFile.Id);
        List<ContentVersion> conDocId = new List<ContentVersion>();
        
        conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ContVerFile.Id];
        System.debug('conDocId : '+conDocId[0].ContentDocumentId);
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        
        cdl.LinkedEntityId = accId;
        
        cdl.ContentDocumentId = conDocId[0].ContentDocumentId;
        
        cdl.shareType = 'V';
        
        Insert cdl;
      
        
        VOI_Status__c temp = [select Id, name,link_Expire_code__c, contact__c from VOI_Status__c WHERE contact__r.Id =: ConId order by createddate DESC LIMIT 1];
        
        temp.link_Expire_code__c = '';
        temp.Case_Status__c = 'Submitted';
        
        update temp;
        
        System.debug('pdf data : '+bPDF);
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();    
        
        Account acount = [select Id, Name, Onboarded_referrer__c from Account WHERE Id=: accId AND RecordTypeId =: recordTypeId];
        acount.On_Board_Referral__c = true;
        update acount;
        
    }
    
    public static void sendEmail(){
         
        try{
            contact con = [select Id,Email, FirstName, AccountId from contact WHERE Id =: ConId LIMIT 1];
            Account acc = [select id, name from Account WHERE id =: con.AccountId LIMIT 1];
            List<ContentDocumentLink> CDLList = [Select Id,ContentDocumentId from ContentDocumentLink WHERE LinkedEntityId =: accId LIMIT 1];        
            
            Blob b;
            if(CDLList != null){
                if(CDLList.size() > 0){
                    String cdId = CDLList[0].ContentDocumentId;
                    List<ContentVersion> conVerList = [SELECT Id, Title,VersionData FROM ContentVersion WHERE ContentDocumentId = : cdId order by createddate LIMIT 1];
                    b = conVerList[0].VersionData;
                }
            }
            
            
            EmailTemplate emailTemplate = [SELECT Id,Subject, Body FROM EmailTemplate WHERE DeveloperName = 'VOI_referrer_Email' ];
            System.debug('Email template ID::'+emailTemplate);
            //Get templete id for set the templete.
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setFileName('Signed Compliance Documents.pdf');
            efa.setContentType('application/pdf');
            efa.setBody(b);
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
            email.setTemplateId(emailTemplate.id);         
            email.setTargetObjectId(con.id);
          	email.setWhatId(acc.id);
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'personalapplications@parkerlane.com.au'];
            if(owea != null){
                if ( owea.size() > 0 ) {
                    email.setOrgWideEmailAddressId(owea.get(0).Id);
                }
            }
            email.setReplyTo('personalapplications@parkerlane.com.au');
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
            email.saveAsActivity = true;
            string[] to = new string[] {con.Id};  
                email.setToAddresses(to);
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }catch(Exception ex){
            Exception__c eror = new Exception__c();
            eror.Class_Name__c = 'Digital ID Sign for Referrer';
            eror.Method_Name__c = 'Email sending';
            eror.Error_Message__c = ex.getMessage() + '' + ex.getLineNumber();
            eror.VOI_Detail__c = VOIDetailID();
            insert eror;
        }
    }
    
    
    public static void generateLog(){
        String startTime = Apexpages.currentPage().getParameters().get('startTime');
        String endTime = Apexpages.currentPage().getParameters().get('endTime');
        System.debug('startTime ++'+startTime);
        System.debug('endTime ++'+endTime);
        
        Exception__c eror = new Exception__c();
        eror.Class_Name__c = 'Digital ID Sign';
        eror.Method_Name__c = 'video Upload from page';
        eror.start_time__c = startTime;
        eror.end_time__c = endTime;
        eror.Error_Message__c = message;
        eror.VOI_Detail__c = VOIDetailID();
        eror.Account__c = accId;
        insert eror;
        
        system.debug('id+++'+eror.Id);
    }
    
}