force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Anticipate_intro_finance_to_customer__c.field-meta.xml
<CustomField>
    <fullName>Anticipate_intro_finance_to_customer__c</fullName>
    <label>Anticipate intro finance to customer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Frequently</fullName>
            </value>
            <value>
                <fullName>Occasionally</fullName>
            </value>
            <value>
                <fullName>Only when asked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Are_you_Clean_Energy_Council_Accredited__c.field-meta.xml
<CustomField>
    <fullName>Are_you_Clean_Energy_Council_Accredited__c</fullName>
    <label>Are you Clean Energy Council Accredited</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Legal_Name__c</fullName>
    <label>Company Legal Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/General_Business_Description__c.field-meta.xml
<CustomField>
    <fullName>General_Business_Description__c</fullName>
    <label>General Business Description</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/How_do_you_conduct_your_appointment__c.field-meta.xml
<CustomField>
    <fullName>How_do_you_conduct_your_appointment__c</fullName>
    <label>How do you conduct your appointment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to face</fullName>
            </value>
            <value>
                <fullName>Phone call</fullName>
            </value>
            <value>
                <fullName>Video call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/How_many_new_sales_appointments_per_week__c.field-meta.xml
<CustomField>
    <fullName>How_many_new_sales_appointments_per_week__c</fullName>
    <label>How many new sales appointments per week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-10</fullName>
            </value>
            <value>
                <fullName>10-50</fullName>
            </value>
            <value>
                <fullName>50-100</fullName>
            </value>
            <value>
                <fullName>100+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Find_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_Find_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Find Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_1__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_1__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_2__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_2__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_Accreditations_3__c.field-meta.xml
<CustomField>
    <fullName>Key_Accreditations_3__c</fullName>
    <label>Key Accreditations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Listing_URL__c.field-meta.xml
<CustomField>
    <fullName>Listing_URL__c</fullName>
    <label>Listing URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Other_Business_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Other_Business_Type_Description__c</fullName>
    <label>Other Business Type Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Business_Type__c</fullName>
    <label>Referrer Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar Installer</fullName>
            </value>
            <value>
                <fullName>Solar Retailer</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Builder Referrer</fullName>
            </value>
            <value>
                <fullName>Website Referrer</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Home improvement retailer</fullName>
            </value>
            <value>
                <fullName>Home improvement installer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Aggregator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_1__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_1__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_2__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_2__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Value_Proposition_3__c.field-meta.xml
<CustomField>
    <fullName>Unique_Value_Proposition_3__c</fullName>
    <label>Unique Value Proposition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Authorised_Signatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Authorised Signatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Company Secretary</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/link_Expire_code__c.field-meta.xml
<CustomField>
    <fullName>link_Expire_code__c</fullName>
    <label>link Expire code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferrerOnboardingFormController.cls
public without sharing class ReferrerOnboardingFormController {
    public Account acc{get;Set;}
    public ReferrerOnboardingFormController(){
        String accId = apexpages.currentpage().getparameters().get('id');
		acc = New Account();
        if(String.isNotBlank(accId)){
            acc = [SELECT Id, ABN__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Company_Legal_Name__c, 
                   (SELECT Id, FirstName, LastName, Name, Position__c FROM Contacts WHERE Is_Authorised_Signatory__c =true LIMIT 1)
                   FROM Account WHERE id =: accId];
        }
    }
    
    @auraEnabled
    public static Account saveReferrer(Account acc, Contact con){
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        Id conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referrer').getRecordTypeId();
        Savepoint sp = Database.setSavepoint();
        try{
            acc.RecordTypeId = accRTId;
            upsert acc;
            con.AccountId = acc.Id;
            con.RecordTypeId = conRTId;
            con.Status__c = 'Active';
            con.Admin__c = true;
            upsert con;
            acc = [SELECT Id, Name, ABN__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Company_Legal_Name__c,
                   Referrer_Business_Type__c, Other_Business_Type_Description__c, Is_Find_Billing_Address__c, Website, Are_you_Clean_Energy_Council_Accredited__c,
                   Listing_URL__c,How_many_new_sales_appointments_per_week__c,How_do_you_conduct_your_appointment__c, Anticipate_intro_finance_to_customer__c,
                   General_Business_Description__c, Unique_Value_Proposition_1__c, Unique_Value_Proposition_2__c, Unique_Value_Proposition_3__c,
                   Key_Accreditations_1__c, Key_Accreditations_2__c, Key_Accreditations_3__c, Phone,
                   (SELECT Id, FirstName, LastName, Email, Phone, Position__c FROM Contacts)
                   FROM Account WHERE Id =: acc.Id];
            return acc;
            
        }catch(exception e){
            UtilityClass.createException(acc.Id, 'ReferrerOnboardingFormController', 'submitReferrer', e.getMessage(), e.getStackTraceString(), ''+e.getLineNumber(),
                                         e.getTypeName(), ''+e.getCause());
            System.debug('@@@@'+ e.getMessage());
            Database.rollback(sp);
            return Null;
        }
    }  
    
    @auraEnabled
    public static void createEnvelope(String accId){
        try{
			DocuSignRESTUtility.createEnvelopeForAccount(accId);
        }catch(exception e){
            UtilityClass.createException(accId, 'ReferrerOnboardingFormController', 'createEnvelope', e.getMessage(), e.getStackTraceString(), ''+e.getLineNumber(),
                                         e.getTypeName(), ''+e.getCause());
        }
    }
    
    @auraEnabled
    public static Account submitReferrer(Account acc, List<Contact> conList, Boolean isNext){
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        Id conRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referrer').getRecordTypeId();
        Savepoint sp = Database.setSavepoint();
        try{
            List<Contact> conListToInsert = New List<Contact>();
            update acc;
            
            
            for(Contact con: conList){
                con.AccountId = acc.Id;
                con.RecordTypeId = conRTId;
                con.Status__c ='Active';
                conListToInsert.add(con);
            }
            upsert conListToInsert;
            
            System.debug('isnext ++'+isNext);
            if(conListToInsert != null && !isNext){
                if(conListToInsert.size() > 0){
                    List<Contact> con = [select Id,Phone, name from Contact WHERE AccountId =: acc.id AND Is_Authorised_Signatory__c = true LIMIT 1];
                    
                    string IntrandomNumber = string.valueOf(Math.round((Math.random() * (900000) + 100000)));
                    Set<id> vioIdSet = new Set<id>();
                    for(VOi_status__c vois : [select Id,link_Expire_code__c, Name,Case_Status__c, contact__c, contact__r.name from VOi_status__c WHERE contact__r.id IN: con AND Case_Status__c != 'Verified' AND Case_Status__c != 'Rejected' order by createddate DESC LIMIT 1]){
                        if(vois.Case_Status__c == 'Delivered' || vois.Case_Status__c == 'Sent'){
                            string msg = vois.Contact__r.name + ' has already completed the VOI. To send again, you must first update the status of the current VOI record to either Verified or Rejected.';
                            System.debug('mesgae+'+msg);
                        }else{
                            vioIdSet.add(vois.id);            
                        }
                    }
                    List<string> smsText = new List<string>();
                    string voiSId= '';
                    for(smagicinteract__smsMagic__c obj : [select ID, name,VOI_Status__c,VOI_Status__r.id,smagicinteract__SMSText__c, smagicinteract__Contact__c from smagicinteract__smsMagic__c WHERE VOI_Status__r.id IN: vioIdSet order by createddate DESC LIMIT 1]){
                        smsText.add(obj.smagicinteract__SMSText__c);
                        voiSId = obj.VOI_Status__r.id;
                    }
                    
                    if(smsText != null && smsText.size() > 0){
                        SMSController.SendMessageToReferr('Contact', 'Parkerlane', con[0].id, acc.id, IntrandomNumber, smsText[0], voisId);
                        System.debug('firstSuccess');
                    }	
                    else{
                        VOI_Status__c obj = new VOI_Status__c();
                        obj.Account__c = acc.id;
                        obj.Contact__c = con[0].id;
                        obj.Case_Status__c = 'Sent';
                        obj.link_Expire_code__c = IntrandomNumber;
                        
                        insert obj;     
                        
                        SMSController.SendMessageToReferr('Contact', 'Parkerlane', con[0].id, acc.id, IntrandomNumber, '', obj.id);
                        
                        System.debug('secSuccess');
                    }   
                   
                }
            }
            acc = [SELECT Id, Name, ABN__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Company_Legal_Name__c,
                   Referrer_Business_Type__c, Other_Business_Type_Description__c, Is_Find_Billing_Address__c, Website, Are_you_Clean_Energy_Council_Accredited__c,
                   Listing_URL__c,How_many_new_sales_appointments_per_week__c,How_do_you_conduct_your_appointment__c, Anticipate_intro_finance_to_customer__c,
                   General_Business_Description__c, Unique_Value_Proposition_1__c, Unique_Value_Proposition_2__c, Unique_Value_Proposition_3__c,
                   Key_Accreditations_1__c, Key_Accreditations_2__c, Key_Accreditations_3__c, Phone,
                   (SELECT Id, FirstName, LastName, Email, Phone, Position__c FROM Contacts)
                   FROM Account WHERE Id =: acc.Id];
            return acc;
        }catch(exception e){
            UtilityClass.createException(acc.Id, 'ReferrerOnboardingFormController', 'submitReferrer', e.getMessage(), e.getStackTraceString(), ''+e.getLineNumber(),
                                         e.getTypeName(), ''+e.getCause());
            Database.rollback(sp);
            return null;
        }
    }   
    
    
}