force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Referred by Company)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/A1_Funding_Call_Handover__c.field-meta.xml
<CustomField>
    <fullName>A1_Funding_Call_Handover__c</fullName>
    <label>A1 Funding Call Handover</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/A2_Funding_Call_Handover__c.field-meta.xml
<CustomField>
    <fullName>A2_Funding_Call_Handover__c</fullName>
    <label>A2 Funding Call Handover</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_1_A1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_A1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 1 (A1)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_2_A2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_A2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2 (A2)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Applicant 2 (A2))</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/BusinessDays__c.field-meta.xml
<CustomField>
    <fullName>BusinessDays__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BusinessDays</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Status__c</fullName>
    <label>Customer Authorisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request sent to customer(s)</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 2</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 1</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Type__c</fullName>
    <label>Customer Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Either to sign</fullName>
            </value>
            <value>
                <fullName>Both to sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Date_Last_Request_Status_Changes__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Request_Status_Changes__c</fullName>
    <label>Date Last Request Status Changes</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Funding_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Funding_On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment requested by supplier</fullName>
            </value>
            <value>
                <fullName>Payment requested by supplier (pending contract)</fullName>
            </value>
            <value>
                <fullName>Variation requested by customer</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer (pending contract)</fullName>
            </value>
            <value>
                <fullName>Payment authorised by customer</fullName>
            </value>
            <value>
                <fullName>Funding handover call completed</fullName>
            </value>
            <value>
                <fullName>Payment funded</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Expire_Date__c</fullName>
    <formula>DATEVALUE(Approved_Date__c) + 90</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Support_Person__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Support Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred by Company)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/BatchForFundingTasks.cls
global class BatchForFundingTasks implements Database.Batchable<sObject>,Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) { 
        String query = 'SELECT Id, Opportunity__c,Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c,Funding_On_Hold__c,Request_Status__c,';
        query += 'Applicant_1_A1__c,Applicant_2_A2__c,Opportunity__r.Customer_Support_Person__c,Date_Last_Request_Status_Changes__c,Customer_Authorisation_Type__c,Opportunity__r.Lender__c, ';
        query += 'Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId, Customer_Authorisation_Status__c,BusinessDays__c,Opportunity__r.Approved_Expire_Date__c, A1_Funding_Call_Handover__c,A2_Funding_Call_Handover__c,';
        query += 'Opportunity__r.FinServ__ReferredByContact__c,Opportunity__r.Referred_by_Company__c,Opportunity__r.Referred_by_Company__r.Account_manager__c, Opportunity__r.Name FROM Funding_Request__c WHERE Opportunity__c != null';
        return Database.getQueryLocator(query); 
        //Opportunity__c = \'0069h000004awuPAAQ\''
    } 
    
    global void execute(Database.BatchableContext bc, List<Funding_Request__c> frList) {
        boolean managed = false;
        boolean unmanaged = false;
        Datetime today = System.Now();
        String Description1 = 'Contact the applicant to assist them with funding. Ensure they are aware that they may face interest and penalties from the supplier if they delay payment. If there is a reason, place the funding on hold and notify the referrer immediately.';
        String Description2 = 'Make contact with the referrer to inform them of our activity and suggest what they can do to assist with funding.';
        String Description3 = 'Call to the referrer (contact or account contact) to give them an update and explain what they can do to assist.';
        //Kunal Sir Code for Business Days logic Starts.
        DateTime myDateTime = DateTime.now();
        String dayOfWeek = myDateTime.format('EEEE');
        List<Funding_Request__c> frListToUpdate = new List<Funding_Request__c>();
        for(Funding_Request__c fundReq : frList){
            Integer days = (fundReq.Date_Last_Request_Status_Changes__c.Date()).daysBetween(system.today());
            Datetime dt = fundReq.Date_Last_Request_Status_Changes__c;
            fundReq.BusinessDays__c = 0;
            for(integer i=1; i<=days; i++){
                Datetime diff = dt + i;
                if(diff.format('EEEE') != 'Saturday' && diff.format('EEEE') != 'Sunday'){
                    fundReq.BusinessDays__c += 1;
                }
            }
            frListToUpdate.add(fundReq);
        }
        if(!frListToUpdate.isEmpty()){
            update frListToUpdate; 
        }
        
        map<id,decimal> fundMap = new map<id,decimal>();
        for(Funding_Request__c fReq : frList){
            fundMap.put(fReq.id,fReq.BusinessDays__c);   
        }
        // Kunal Sir Code End.
        
        map<Id,Id> mapOfFundingandOppCsmtrSupport = new map<Id,Id>();
        map<Id,Id> mapofAppandFundingForManaged = new map<Id,Id>();
        map<Id,String> mapOfFundingandTaskTitle = new map<Id,String>();
        map<Id,String> mapOfFundingandTaskDesc = new map<Id,String>();
        map<Id,String> mapforUnManagedTask = new Map<Id,String>();
        map<Id,Id> mapofAppandFunding = new Map<Id,Id>();
        map<Id,Id> mapOfAppandappPersonContact = new Map<Id,Id>();
        
        for(Funding_Request__c fr :frList){
            integer daysBtwnnTdyAndLstReqSts = integer.valueOf(fundMap.get(fr.Id));
            if(fr.Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c == 'Managed via Parker Lane' && !fr.Funding_On_Hold__c 
               && (fr.Request_Status__c == 'Payment requested by supplier' || fr.Request_Status__c == 'Payment requested by customer') && fr.Opportunity__r.Approved_Expire_Date__c > today.Date() 
               && fr.Customer_Authorisation_Status__c != 'Authorised' && fr.Customer_Authorisation_Status__c != null && fr.Opportunity__r.Customer_Support_Person__c != null){
                   managed = true;
                   mapOfFundingandOppCsmtrSupport.put(fr.Id,fr.Opportunity__r.Customer_Support_Person__c);
                   List<Integer> daysForTasks1 = new List<Integer>{1,2,3,4,5};
                       if(fr.Customer_Authorisation_Type__c == 'Either to sign' && fr.Customer_Authorisation_Status__c != 'Authorised'){
                           if(daysForTasks1.Contains(daysBtwnnTdyAndLstReqSts)){
                               mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                               mapOfFundingandTaskDesc.put(fr.Id,Description1);  
                               Integer i = daysBtwnnTdyAndLstReqSts; 
                               String taskTitle = 'Day '+i+' Funding Authorisation Outstanding A1';
                               mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle);
                           }
                       }
                   else if (fr.Customer_Authorisation_Type__c == 'Both to sign'){
                       if(daysForTasks1.Contains(daysBtwnnTdyAndLstReqSts)){
                           mapOfFundingandTaskDesc.put(fr.Id,Description1);
                           Integer i = daysBtwnnTdyAndLstReqSts; 
                           if(fr.Customer_Authorisation_Status__c == 'Request sent to customer(s)'){ 
                               if(fr.Applicant_2_A2__c == null){
                                   mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                                   String taskTitle = 'Day '+i+' Funding Authorisation Outstanding A1';
                                   mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle);
                               } 
                               else if(fr.Applicant_2_A2__c != null){
                                   mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                                   mapofAppandFundingForManaged.put(fr.Applicant_2_A2__c, fr.Id);
                                   String taskTitle = 'Day '+i+' Funding Authorisation Outstanding A1';
                                   mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle);
                                   String taskTitleForapp2 = 'Day '+i+' Funding Authorisation Outstanding A2';
                                   mapOfFundingandTaskTitle.put(fr.Applicant_2_A2__c,taskTitleForapp2);
                               }
                           }
                           else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 1'){
                               String taskTitle = 'Day '+i+' Funding Authorisation Outstanding A1';
                               mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                               mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle);
                           }
                           else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 2'){
                               String taskTitleForapp2 = 'Day '+i+' Funding Authorisation Outstanding A2';
                               mapofAppandFundingForManaged.put(fr.Applicant_2_A2__c, fr.Id);
                               mapOfFundingandTaskTitle.put(fr.Applicant_2_A2__c,taskTitleForapp2);
                           }
                       }    
                   }
                   
               }
            if(fr.Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c == 'Managed via Parker Lane' && !fr.Funding_On_Hold__c && fr.Opportunity__r.Customer_Support_Person__c != null
               && (fr.Request_Status__c == 'Payment requested by supplier' || fr.Request_Status__c == 'Payment requested by customer') && fr.Opportunity__r.Approved_Expire_Date__c > today.Date()){
                   managed = true;
                   mapOfFundingandOppCsmtrSupport.put(fr.Id,fr.Opportunity__r.Customer_Support_Person__c);
                   List<Integer> daysForTasks2 = new List<Integer>{6,7,8,9,10};
                       if(daysForTasks2.Contains(daysBtwnnTdyAndLstReqSts)){
                           Integer i = daysBtwnnTdyAndLstReqSts;
                           String taskTitle = 'Day '+i+' Funding Outstanding Referrer Update Call';
                           mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                           mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle); 
                           mapOfFundingandTaskDesc.put(fr.Id,Description2);
                       }
               }
            
            //Unmanaged Tasks.
            if(fr.Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c == 'Direct with lender' && !fr.Funding_On_Hold__c && fr.Opportunity__r.Customer_Support_Person__c != null
               && (fr.Request_Status__c == 'Payment requested by supplier' || fr.Request_Status__c == 'Payment requested by customer') && fr.Opportunity__r.Approved_Expire_Date__c > today.Date()){
                   List<Integer> daysForTasks3 = new List<Integer>{0,1,2,4,6,8,10,13,16,19,22,25,30,40,50,60};
                       mapOfFundingandOppCsmtrSupport.put(fr.Id,fr.Opportunity__r.Customer_Support_Person__c);
                   if(fr.Customer_Authorisation_Type__c == 'Either to sign'){
                       if(daysForTasks3.Contains(daysBtwnnTdyAndLstReqSts)){
                           unmanaged = true;
                           Integer i = daysBtwnnTdyAndLstReqSts;
                           String ttl =  'Day '+i+' Funding Handover Call '+fr.Opportunity__r.Lender__c;
                           if(fr.A1_Funding_Call_Handover__c == null && fr.A2_Funding_Call_Handover__c == null){
                               mapforUnManagedTask.put(fr.Applicant_1_A1__c,ttl); 
                               mapofAppandFunding.put(fr.Applicant_1_A1__c,fr.Id);
                               mapOfAppandappPersonContact.put(fr.Applicant_1_A1__c,fr.Applicant_1_A1__r.PersonContactId);
                           } 
                       }
                   }
                   
                   else if(fr.Customer_Authorisation_Type__c == 'Both to sign'){
                       if(daysForTasks3.Contains(daysBtwnnTdyAndLstReqSts)){
                           unmanaged = true;
                           Integer i = daysBtwnnTdyAndLstReqSts;
                           String ttl =  'Day '+i+' Funding Handover Call '+fr.Opportunity__r.Lender__c;
                           if(fr.Applicant_2_A2__c != null){
                               if(fr.A1_Funding_Call_Handover__c == null){
                                   mapforUnManagedTask.put(fr.Applicant_1_A1__c,ttl); 
                                   mapofAppandFunding.put(fr.Applicant_1_A1__c,fr.Id);
                                   mapOfAppandappPersonContact.put(fr.Applicant_1_A1__c,fr.Applicant_1_A1__r.PersonContactId);
                               } 
                               if(fr.A2_Funding_Call_Handover__c == null){
                                   mapforUnManagedTask.put(fr.Applicant_2_A2__c,ttl); 
                                   mapofAppandFunding.put(fr.Applicant_2_A2__c,fr.Id);
                                   mapOfAppandappPersonContact.put(fr.Applicant_2_A2__c,fr.Applicant_2_A2__r.PersonContactId);
                               }
                           }
                           else if(fr.Applicant_2_A2__c == null && fr.A1_Funding_Call_Handover__c == null){
                               mapforUnManagedTask.put(fr.Applicant_1_A1__c,ttl); 
                               mapofAppandFunding.put(fr.Applicant_1_A1__c,fr.Id);
                               mapOfAppandappPersonContact.put(fr.Applicant_1_A1__c,fr.Applicant_1_A1__r.PersonContactId);
                           }
                           
                       }  
                   }
               }
            
            //Unmanaged 4th.
            if(fr.Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c == 'Direct with lender' && fr.Opportunity__r.FinServ__ReferredByContact__c != null 
               && (fr.Request_Status__c == 'Payment requested by supplier' || fr.Request_Status__c == 'Payment requested by customer') && fr.Opportunity__r.Approved_Expire_Date__c > today.Date()){
                   managed = true;
                   List<Integer> daysForTasks4 = new List<Integer>{5,10,20,30,40,50,60};
                       if(daysForTasks4.Contains(daysBtwnnTdyAndLstReqSts)){
                           Integer i = daysBtwnnTdyAndLstReqSts; 
                           mapOfFundingandTaskDesc.put(fr.Id,Description3);
                           mapofAppandFundingForManaged.put(fr.Applicant_1_A1__c, fr.Id);
                           String taskTitle = 'Day '+i+' call to referrer - funding not authorised';
                           mapOfFundingandTaskTitle.put(fr.Applicant_1_A1__c,taskTitle);
                           if(fr.Opportunity__r.Referred_by_Company__c != null && fr.Opportunity__r.Referred_by_Company__r.Account_manager__c != null){
                               mapOfFundingandOppCsmtrSupport.put(fr.Id,fr.Opportunity__r.Referred_by_Company__r.Account_manager__c);
                           }
                           else if(fr.Opportunity__r.Customer_Support_Person__c != null){
                               mapOfFundingandOppCsmtrSupport.put(fr.Id,fr.Opportunity__r.Customer_Support_Person__c );
                           }  
                       }
               }
        }
        
        
        List<Task> tasksToInsert = new List<Task>();
        //Managed Tasks.
        if(!mapofAppandFundingForManaged.isEmpty() && !mapOfFundingandTaskTitle.isEmpty() && !mapOfFundingandOppCsmtrSupport.isEmpty() && managed == true){
            for (Id appId : mapofAppandFundingForManaged.keySet()) {
                Id Funding_reqId = mapofAppandFundingForManaged.get(appId);
                Task tk = new Task();
                tk.WhatId = mapofAppandFundingForManaged.get(appId); 
                tk.Subject = mapOfFundingandTaskTitle.get(appId); 
                tk.Description = mapOfFundingandTaskDesc.get(Funding_reqId);  
                tk.OwnerId = mapOfFundingandOppCsmtrSupport.get(Funding_reqId);
                tk.ActivityDate =  Date.today();
                tk.Type = 'Call';
                tk.Priority = 'Medium';
                tasksToInsert.add(tk);
            }
        }
        //Unmanaged Tasks.
        if(!mapforUnManagedTask.isEmpty() && !mapOfFundingandOppCsmtrSupport.isEmpty() && unmanaged == true){
            for (Id appId : mapforUnManagedTask.keySet()) {
                Id Funding_reqId = mapofAppandFunding.get(appId);
                Task tk = new Task();
                tk.WhatId = mapofAppandFunding.get(appId); 
                tk.WhoId = mapOfAppandappPersonContact.get(appId);
                tk.Subject = mapforUnManagedTask.get(appId); 
                /* Task trigger is depends on Description for the functionality */
                tk.Description = 'IMPORTANT: If the funding handover call is successful, you must mark ‘Sales outcome’ fields = Successful. An SMS will automatically be sent if you save this task as successful with instructions to call the lender back and to let you know if the call was successful.';  
                tk.OwnerId = mapOfFundingandOppCsmtrSupport.get(Funding_reqId);
                tk.ActivityDate =  Date.today();
                tk.Type = 'Call';
                tk.Priority = 'Medium';
                tasksToInsert.add(tk);
            }
        } 
        
        if (!tasksToInsert.isEmpty()){ 
            insert tasksToInsert; 
        } 
    }  
    
    
    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients,
        // give a call to another batch class
        // Can give to another batch class
        // Can give callout request
    }
}