force-app/main/default/objects/Account/fields/BackgroundImage__c.field-meta.xml
<CustomField>
    <fullName>BackgroundImage__c</fullName>
    <label>Background Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LogoImage__c.field-meta.xml
<CustomField>
    <fullName>LogoImage__c</fullName>
    <label>Logo Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Related__c.field-meta.xml
<CustomField>
    <fullName>Related__c</fullName>
    <formula>IF(ISBLANK(Document_Requested__r.Person_Account__c),&quot;General&quot;,Document_Requested__r.Person_Account__r.FirstName+&apos; &apos;+Document_Requested__r.Person_Account__r.MiddleName+&apos; &apos;+Document_Requested__r.Person_Account__r.LastName)</formula>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/isComplete__c.field-meta.xml
<CustomField>
    <fullName>isComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <description>IF(  IsJoint__c  = true , &quot;General&quot; , IF(Person_Account__c  = Opportunity__r.Applicant_1__c, &quot;Applicant 1&quot; ,  IF( Person_Account__c  =  Opportunity__r.Applicant_2__c  , &quot;Applicant 2&quot; , &quot;&quot; ) ) )</description>
    <formula>IF(  IsJoint__c  = true , &quot;General&quot; ,IF(NOT(ISBLANK(Person_Account__c)), IF(Person_Account__c  = Opportunity__r.Applicant_1__c, &quot;Applicant 1&quot; ,  IF( Person_Account__c  =  Opportunity__r.Applicant_2__c  , &quot;Applicant 2&quot; , &quot;&quot; ) ),&quot;&quot; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( isAlready_provided__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/green.png&quot;, &quot;Already Provided&quot;, 20, 20)&amp; &quot; Already Provided&quot;,
IF( isApplicable__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/yellow.png&quot;, &quot;Not Applicable&quot;, 20, 20) &amp; &quot; Not Applicable&quot;,
IF( isComplete__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/darkgreen.png&quot;, &quot;Submitted&quot;, 20, 20) &amp; &quot; Submitted&quot;,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/red.png&quot;, &quot;Requested&quot;, 20, 20) &amp; &quot; Requested&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Current_Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Current_Application_Sections__c</fullName>
    <label>Current Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
                <default>true</default>
                <label>Priorities</label>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Docs_Last_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Docs_Last_Uploaded__c</fullName>
    <label>Docs Last Uploaded</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isActivityCheck__c.field-meta.xml
<CustomField>
    <fullName>isActivityCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActivityCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Customer_Action__c.field-meta.xml
<CustomField>
    <fullName>Last_Customer_Action__c</fullName>
    <label>Last Customer Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application received</fullName>
            </value>
            <value>
                <fullName>Documents received</fullName>
            </value>
            <value>
                <fullName>Identity verified</fullName>
            </value>
            <value>
                <fullName>Credit proposal signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Customer_Activity__c.field-meta.xml
<CustomField>
    <fullName>Last_Customer_Activity__c</fullName>
    <label>Last Customer Activity</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( AND( OR( ISPICKVAL( StageName , &apos;Quote&apos;) , ISPICKVAL( StageName , &apos;CPA Started&apos;))  , OR( ISPICKVAL( Current_Application_Sections__c ,&apos;Priorities&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Loan Recommendation&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Getting Started&apos;) ) )  ,&apos;Quote-#fd636b&apos;,
 
IF(ISPICKVAL( StageName , &apos;CPA Started&apos;),&apos;Applying-#ffb902&apos;,
    
IF( AND( OR( ISPICKVAL(StageName,  &apos;Packs Out&apos;),ISPICKVAL( StageName, &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;CPA Done&apos;)), NOT(Funding_Variation_Request__c)), &apos;Verifying-#FFDF8F&apos;,

IF( AND( OR( ISPICKVAL(StageName, &apos;Application&apos;) ,ISPICKVAL(StageName, &apos;Conditional&apos;)), NOT(Funding_Variation_Request__c)), &apos;Credit-#b4f6e0&apos;, 

IF(  AND(ISPICKVAL(StageName, &apos;Approved&apos;), TODAY()- DATEVALUE( Approved_Date__c )&lt; 90 )   , &apos;Approved-#3be8b0&apos;,
IF(  OR(AND (ISPICKVAL(StageName, &apos;Funding&apos;), (TODAY()- DATEVALUE( Approved_Date__c )&lt; 90)),(AND (OR(ISPICKVAL(StageName,  &apos;CPA Done&apos;),ISPICKVAL( StageName, &apos;Packs Out&apos;),ISPICKVAL( StageName , &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;Application&apos;),
ISPICKVAL( StageName , &apos;Conditional&apos;)) ,Funding_Variation_Request__c ))), &apos;Funding-#d063d3&apos;,
IF( ISPICKVAL(StageName, &apos;Settled (closed won)&apos;) , &apos;Funded-#4a154b&apos;,
IF( AND( OR(ISPICKVAL(StageName, &apos;Approved&apos;),ISPICKVAL(StageName, &apos;Funding&apos;)) ,TODAY()- DATEVALUE( Approved_Date__c )&gt; 90) , &apos;Expired-#FFFF00&apos;, 
IF( OR( ISPICKVAL(StageName, &apos;Closed Lost&apos;) ,ISPICKVAL(StageName, &apos;Nurturing&apos;),ISPICKVAL(StageName, &apos;Working&apos;)) , &apos;Closed-#f2f2f2&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentRequestedController.cls
public without sharing class DocumentRequestedController{

    @AuraEnabled
    public static List<Document_Requested__c> fetchDocumentRequested(String oppId){
        List<Document_Requested__c> drList = [SELECT Id,Name,Document__c, CreatedDate,isComplete__c, Details__c,Related_To__c,Description__c,Status__c,Category__c FROM Document_Requested__c WHERE Opportunity__c =: oppId AND Document__c != '' ORDER BY Name ASC];
       	system.debug('drListdrList'+drList);
        
        return drList;
    }
    
    @AuraEnabled
    public static void updateDocRequested(String docId, List<String> cdIds){
        Id dr = (Id)docId;
        System.debug(cdIds);
        List<ContentVersion> cv  = new List<ContentVersion>();
        for(ContentVersion c: [select Id, related__c, Category__c, Document_Requested__c, ContentDocumentId from ContentVersion where contentDocumentId In :cdIds]){
            c.Document_Requested__c = dr;
        	cv.add(c);
        }
        update cv;
        Document_Requested__c doc = new Document_Requested__c();
        doc.id = docId;
        doc.isComplete__c = true;
        update doc;        
    }
    
    @AuraEnabled
    public static Account getAccountDetails(String recordId){
        Account acc = [Select id,BackgroundImage__c,LogoImage__c from Account where id =: recordId];
        return acc;
    }
    
    @AuraEnabled
    public static Account addAccountPhotos(List<String> cdIds, String recordId, String name){
        List<ContentDistribution> cd = new List<ContentDistribution>();
        ContentDistribution distribution;
        String distributionLink = '';
        for(ContentVersion c: [select Id, related__c, Category__c, Document_Requested__c, ContentDocumentId from ContentVersion where contentDocumentId In :cdIds]){
             distribution = new ContentDistribution();
            distribution.ContentVersionId = c.Id;
            distribution.Name = 'PublicShare';
            distribution.PreferencesAllowOriginalDownload = true; 
            distribution.PreferencesAllowPDFDownload = true;
            distribution.PreferencesPasswordRequired = false;
            distribution.PreferencesAllowViewInBrowser = true;
            distribution.PreferencesNotifyOnVisit=false;
            distribution.PreferencesLinkLatestVersion = true;
            cd.add(distribution);
        }
        insert cd;
        ContentDistribution cdUrl = [Select Id,ContentDocumentId,ContentDownloadUrl,DistributionPublicUrl from ContentDistribution where ContentDocumentId In: cdIds];
        String picUrl = '';
        picUrl =  cdUrl.ContentDownloadUrl.replace('download/?' , 'renditionDownload?rendition=ORIGINAL_Jpg&');
        picUrl = picUrl.replace('&ids' , '&versionId');
        Account acc = [Select id,BackgroundImage__c,LogoImage__c from Account where id =: recordId];
        if(name == 'Logo'){
            acc.LogoImage__c = '<p>'+picUrl+'</p>';
        }
        else if(name == 'Background'){
            acc.BackgroundImage__c = '<p>'+picUrl+'</p>';
        }
        update acc;
        return acc;
    }
    
    @AuraEnabled
    public static void updateCustomerActivity(string recId){
        Opportunity opp = [select id,Last_Customer_Action__c,isActivityCheck__c,Last_Customer_Activity__c/*,Docs_Last_Uploaded__c*/ from opportunity where id =: recId];
        opp.Last_Customer_Activity__c = system.now(); 
        opp.isActivityCheck__c = false;
        update opp;
        opp.isActivityCheck__c = true;
        opp.Last_Customer_Action__c = 'Documents received';
        opp.Docs_Last_Uploaded__c = System.now();
        update opp;
    }
    
    @AuraEnabled
    public static string sendEmailToCust(string oppId){
       List<Document_Requested__c> drList = [SELECT id,isComplete__c,Details__c,Document__c,Related_To__c,Status__c FROM Document_Requested__c WHERE Opportunity__c =: oppId AND isComplete__c = false AND Document__c != ''];
        
        System.debug('finalList'+drList.size());
        if(drList != null && drList.size() > 0){
            System.debug('in list');    
            Opportunity oppUpdate = [SELECT Id, Application_Sections__c, Current_Application_Sections__c, AccountId, Applicant_1__c,
                                     Applicant_1__r.PersonContactId, Applicant_1__r.PersonContact.Email, StageName, RecordTypeId,
                                     Number_of_applicants__c,
                                     (SELECT Id, Lead__c, Lender__c, Purpose__c  FROM Quotes WHERE Application__c = TRUE)
                                     FROM Opportunity WHERE Id =: oppId];
            
            System.debug('oppUpdate'+oppUpdate);
            System.debug('oppUpdate'+oppUpdate.Applicant_1__r.PersonContact.Email);
            ParkerLaneLoanController.sendApplication(oppId, oppUpdate.Applicant_1__r.PersonContactId, oppUpdate.Quotes[0].id, New List<String>{oppUpdate.Applicant_1__r.PersonContact.Email}, 'Application Form Completion Remainder', false);
            return 'success';
        }else{
            return 'error';
        }
        
    }
    
}