force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Document__c/Manage_Document__c.object-meta.xml
<CustomObject>
    <label>Manage Document</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>Manage Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Document__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manage_Document__c/fields/IsJoint__c.field-meta.xml
<CustomField>
    <fullName>IsJoint__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsJoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Identification</fullName>
    </customValue>
    <customValue>
        <fullName>Income</fullName>
    </customValue>
    <customValue>
        <fullName>Business Income</fullName>
    </customValue>
    <customValue>
        <fullName>Rental Income</fullName>
    </customValue>
    <customValue>
        <fullName>Liabilities Being Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Liabilities Remaining</fullName>
    </customValue>
    <customValue>
        <fullName>Living Expenses</fullName>
    </customValue>
    <customValue>
        <fullName>Assets</fullName>
    </customValue>
    <customValue>
        <fullName>Loan Purpose</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Standard If Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Proof of Ownership</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Report</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Lender Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Proposal</fullName>
    </customValue>
    <customValue>
        <fullName>Lender Credit Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Preliminary Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Debit Form</fullName>
    </customValue>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UtilityClass_Test.cls
@isTest
public class UtilityClass_Test {
    @isTest
    static void getRequest(){
        UserRole r = new UserRole(DeveloperName = 'Advisor', Name = 'Advisor');
        insert r;
        User u = new User(
             ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
             LastName = 'last',
             Email = 'bala@parkerlane.com',
             Username = 'bala@parkerlane.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             UserRoleId = r.Id
        );
        insert u;
        System.runAs(u){
            Account ac = new Account(Name='Test Ac');
            insert ac;
            Opportunity opp = new Opportunity( Applicant_1__c = ac.Id,Applicant_2__c = ac.Id, Name='Test', StageName='open', CloseDate= Date.today(), Owner = u);
            Insert opp;
            List<Manage_Document__c> dmList = new List<Manage_Document__c>();
            dmList.add(new Manage_Document__c(Category__c = 'Income',Document__c = 'Payslips',IsJoint__c = false,isDefault__c = true));
            dmList.add(new Manage_Document__c(Category__c = 'Standard If Documents',Document__c = 'Centrelink Statements',IsJoint__c = true,isDefault__c = true));
            insert dmList;
            UtilityClass.createDefualtRequest(opp.Id);
            UtilityClass.sendEmail(opp);
        }
    }
    
    @isTest
    static void createException(){
        UtilityClass.createException( 'recordId',  'className',  'methodName',  'ErrorMessage',  'stackTrace',  'lineNo',
                                        'errorType',  'errorCause');
    }
    
    @isTest
    static void getPicklistValues(){
        List<String> appStagesList = UtilityClass.getPicklistValues('Opportunity', 'StageName'); 
        System.assertNotEquals(0, appStagesList.size(), 'should not be Zero');
    }
}