force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT( Document_Requested__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Requested__c.field-meta.xml
<CustomField>
    <fullName>Document_Requested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Requested</label>
    <referenceTo>Document_Requested__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/isComplete__c.field-meta.xml
<CustomField>
    <fullName>isComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( isAlready_provided__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/green.png&quot;, &quot;Already Provided&quot;, 20, 20)&amp; &quot; Already Provided&quot;,
IF( isApplicable__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/yellow.png&quot;, &quot;Not Applicable&quot;, 20, 20) &amp; &quot; Not Applicable&quot;,
IF( isComplete__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/darkgreen.png&quot;, &quot;Submitted&quot;, 20, 20) &amp; &quot; Submitted&quot;,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/red.png&quot;, &quot;Requested&quot;, 20, 20) &amp; &quot; Requested&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( AND( OR( ISPICKVAL( StageName , &apos;Quote&apos;) , ISPICKVAL( StageName , &apos;CPA Started&apos;))  , OR( ISPICKVAL( Current_Application_Sections__c ,&apos;Priorities&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Loan Recommendation&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Getting Started&apos;) ) )  ,&apos;Quote-#fd636b&apos;,
 
IF(ISPICKVAL( StageName , &apos;CPA Started&apos;),&apos;Applying-#ffb902&apos;,
    
IF( AND( OR( ISPICKVAL(StageName,  &apos;Packs Out&apos;),ISPICKVAL( StageName, &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;CPA Done&apos;)), NOT(Funding_Variation_Request__c)), &apos;Verifying-#FFDF8F&apos;,

IF( AND( OR( ISPICKVAL(StageName, &apos;Application&apos;) ,ISPICKVAL(StageName, &apos;Conditional&apos;)), NOT(Funding_Variation_Request__c)), &apos;Credit-#b4f6e0&apos;, 

IF(  AND(ISPICKVAL(StageName, &apos;Approved&apos;), TODAY()- DATEVALUE( Approved_Date__c )&lt; 90 )   , &apos;Approved-#3be8b0&apos;,
IF(  OR(AND (ISPICKVAL(StageName, &apos;Funding&apos;), (TODAY()- DATEVALUE( Approved_Date__c )&lt; 90)),(AND (OR(ISPICKVAL(StageName,  &apos;CPA Done&apos;),ISPICKVAL( StageName, &apos;Packs Out&apos;),ISPICKVAL( StageName , &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;Application&apos;),
ISPICKVAL( StageName , &apos;Conditional&apos;)) ,Funding_Variation_Request__c ))), &apos;Funding-#d063d3&apos;,
IF( ISPICKVAL(StageName, &apos;Settled (closed won)&apos;) , &apos;Funded-#4a154b&apos;,
IF( AND( OR(ISPICKVAL(StageName, &apos;Approved&apos;),ISPICKVAL(StageName, &apos;Funding&apos;)) ,TODAY()- DATEVALUE( Approved_Date__c )&gt; 90) , &apos;Expired-#FFFF00&apos;, 
IF( OR( ISPICKVAL(StageName, &apos;Closed Lost&apos;) ,ISPICKVAL(StageName, &apos;Nurturing&apos;),ISPICKVAL(StageName, &apos;Working&apos;)) , &apos;Closed-#f2f2f2&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Repayment_Frequency_Options__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency_Options__c</fullName>
    <label>Repayment Frequency Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Interest in Advance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDocumentRequestedController.cls
@isTest
public class TestDocumentRequestedController{
    @isTest
    private static void testFetchDR(){
        Opportunity opp = new Opportunity(Name='Test', StageName='open', CloseDate= Date.today());
        insert opp;
        
        ManageDocumentController.createDocumentRequest('[{"label":"ApplicantOne","value":[{"categry":"Income","selectedItem":[{"label":"Payslips : 2 recent consecutive (no older than 6 weeks)","value":"Payslips","Discription":"","isBankStatment":false}]},{"categry":"Identification","selectedItem":[{"label":"Driver’s license (front and back)","value":"Driver’s license (front and back)","Discription":"","isBankStatment":false},{"label":"Medicare Card","value":"Medicare Card","Discription":"","isBankStatment":false}]}]},{"label":"JointApp","value":[{"categry":"Assets","selectedItem":[{"label":"Recent council rates notice","value":"Recent council rates notice","Discription":"","isBankStatment":false}]},{"categry":"Living Expenses","selectedItem":[{"label":"Last 3 months transaction bank statements","value":"Last 3 months transaction bank statements","Discription":"","isBankStatment":true}]}]}]',true, opp.Id,true);
        
        List<Document_Requested__c> drList = DocumentRequestedController.fetchDocumentRequested(opp.Id);
        System.assert(drList.size() == 5);
    }
    
    @isTest
    private static void testUpdateDR(){
        Opportunity opp = new Opportunity(Name='Test', StageName='open', CloseDate= Date.today());
        insert opp;
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = Opp.id;
        cdl.ContentDocumentId = [select contentdocumentid from contentversion where id =: contentVersion.id].contentdocumentid;
        cdl.shareType = 'V';
        insert cdl;
        List<String> cv = new List<String>{cdl.ContentDocumentId};
        ManageDocumentController.createDocumentRequest('[{"label":"ApplicantOne","value":[{"categry":"Income","selectedItem":[{"label":"Payslips : 2 recent consecutive (no older than 6 weeks)","value":"Payslips","Discription":"","isBankStatment":false}]},{"categry":"Identification","selectedItem":[{"label":"Driver’s license (front and back)","value":"Driver’s license (front and back)","Discription":"","isBankStatment":false},{"label":"Medicare Card","value":"Medicare Card","Discription":"","isBankStatment":false}]}]},{"label":"JointApp","value":[{"categry":"Assets","selectedItem":[{"label":"Recent council rates notice","value":"Recent council rates notice","Discription":"","isBankStatment":false}]},{"categry":"Living Expenses","selectedItem":[{"label":"Last 3 months transaction bank statements","value":"Last 3 months transaction bank statements","Discription":"","isBankStatment":true}]}]}]',true, opp.Id,true);
        
        Document_Requested__c dr = [SELECT Id,Name,isComplete__c,Status__c,Category__c FROM Document_Requested__c WHERE Opportunity__c =: opp.Id ORDER BY Name ASC][0];
        
        DocumentRequestedController.updateDocRequested(dr.id,cv);
        Document_Requested__c dr1 = [SELECT Id,Name,isComplete__c,Status__c,Category__c FROM Document_Requested__c WHERE Id =: dr.Id ];
        ContentVersion cvId =  [select contentdocumentid, Document_Requested__c from contentversion where ContentDocumentid =: cdl.contentdocumentid];
        System.assert(dr1.isComplete__c == true);
        System.assert(dr1.Id == cvId.Document_Requested__c);
    }
    
    @isTest
    public static void mothodForDocReq(){
        contact con = new Contact(LastName = 'qwer', Email = 'test@gmail.com');
        insert con;
        Account acc = new Account(name = 'test', FinServ__PrimaryContact__c = con.Id);
        insert acc;
        opportunity opp = new  opportunity(Name='Test', StageName='open', CloseDate= Date.today(), Applicant_1__c = acc.id, contact_1__c = con.Id);
        insert opp;
        Quote Q1 = new Quote();
        Q1.Name = 'tesst';
        Q1.Application__c = true;
        Q1.OpportunityId = opp.Id;
        Q1.Loan_Term__c = 60;
        Q1.Repayment_Frequency_Options__c  = 'Monthly';
        Q1.Application__c = true;
        insert Q1;
        
        Document_Requested__c dc = new Document_Requested__c(Opportunity__c = opp.Id, isComplete__c = false, Document__c = 'test');
        insert dc;
        DocumentRequestedController.sendEmailToCust(opp.Id);
        
    }
}