force-app/main/default/objects/Account/fields/Dependent_Parent__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependent Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dependent Children</relationshipLabel>
    <relationshipName>Dependent_Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Sync_with_Household__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_with_Household__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sync with Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_with_Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Applicant_1__c</fullName>
    <label>Relationship with Applicant 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Ex-spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__Household__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Household Opportunities</relationshipLabel>
    <relationshipName>HouseholdOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountContactBatchable.cls
global class AccountContactBatchable implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT id, Is_Sync_with_Household__c, Relationship_with_Applicant_1__c, Dependent_Parent__c, PersonContactId '; 
        query += ' FROM account '; 
        query += 'WHERE Is_Sync_with_Household__c = false and recordtype.name = \'person account\'';
        System.debug('@@@@@accList     ' + Database.getQueryLocator(query));
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accList) {
        System.debug('@@@@@accList     ' + accList);
        List<AccountContactRelation> accConRelationList = new List<AccountContactRelation>();
        List<Account> accUpdateList = new List<Account>();
        Set<Id> accIds =  New Set<Id>();
        for(Account acc: accList){
            accIds.add(acc.Id);
            if(String.isNotBlank(acc.Dependent_Parent__c)){
                accIds.add(acc.Dependent_Parent__c);
            }
        }
        System.debug('@@@@@accIds     ' + accIds);
        List<Opportunity> oppList = [SELECT Id, Name, Applicant_1__r.Name, Applicant_2__c, Applicant_2__r.Name, AccountId, 
                                     Account.Name, Account.RecordType.Name, FinServ__Household__c
                                     FROM Opportunity 
                                     WHERE Applicant_1__c in: accIds OR Applicant_2__c in: accIds ];
        System.debug('@@@@@oppList     ' + oppList);
        Map<Id,Id> accHouseholdAcc = New Map<Id,Id>();
        List<Opportunity> oppListToUpdate = New List<Opportunity>();
        for(Opportunity opp: oppList){
            String householdId = '';
            if(String.isNotBlank(opp.FinServ__Household__c)){
                householdId = opp.FinServ__Household__c;
            }else if(String.isNotBlank(opp.AccountId) && ('Household').equalsIgnoreCase(opp.Account.RecordType.Name)){
                householdId = opp.AccountId;
                opp.AccountId = opp.Applicant_1__c;
                oppListToUpdate.add(opp);
            }
            System.debug('@@@@@householdId     ' + householdId);
            if(String.isNotBlank(householdId)){
                accHouseholdAcc.put(opp.Applicant_1__c, householdId);
                if(String.IsNotBlank(opp.Applicant_2__c)){
                    accHouseholdAcc.put(opp.Applicant_2__c, householdId);
                }
            }
        }
        System.debug('@@@@@accList     ' + accList);
        for(Account acc: accList){
            System.debug('@@@@@acc     ' + acc);
            String accId = '';
            if(accHouseholdAcc.containsKey(acc.Id)){
                accId = accHouseholdAcc.get(acc.Id);
            }else if(accHouseholdAcc.containsKey(acc.Dependent_Parent__c)){
                accId = accHouseholdAcc.get(acc.Dependent_Parent__c);
            } 
            System.debug('@@@@@accId     ' + accId);
            if(String.IsNotBlank(accId)){
                accConRelationList.add(new AccountContactRelation(AccountId = accId, 
                                                                  ContactId = acc.PersonContactId,
                                                                  Roles = acc.Relationship_with_Applicant_1__c,
                                                                  FinServ__PrimaryGroup__c = true,
                                                                  FinServ__Primary__c = acc.Relationship_with_Applicant_1__c=='Client',
                                                                  FinServ__Rollups__c='All'));
                acc.Is_Sync_with_Household__c = true;
                accUpdateList.add(acc);
            }
        }
        
        try {
            System.debug('@@@@@accUpdateList     ' + accUpdateList);
            System.debug('@@@@@accConRelationList     ' + accConRelationList);
            System.debug('@@@@@oppListToUpdate     ' + oppListToUpdate);
            update accUpdateList;
            insert accConRelationList;
            update oppListToUpdate;
        } catch(Exception e) {
            System.debug(e);
        }
    }

    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
}