force-app/main/default/objects/Account/fields/Dependent_Parent__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependent Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dependent Children</relationshipLabel>
    <relationshipName>Dependent_Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Sync_with_Household__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_with_Household__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sync with Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_with_Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Applicant_1__c</fullName>
    <label>Relationship with Applicant 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Ex-spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Is_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Authorised_Signatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Authorised Signatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Supporting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Application_Supporting_Notes__c</fullName>
    <label>Application Supporting Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preferred_repayment_frequency__c.field-meta.xml
<CustomField>
    <fullName>Preferred_repayment_frequency__c</fullName>
    <label>Preferred repayment frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResendSMSControllerTest.cls
@isTest
public class ResendSMSControllerTest {

    @isTest 
    public static void tesrMethod(){
       String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recordHTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Household').getRecordTypeId();
        List<Account> accList= new List<Account>();
        Account acc= new Account(
            RecordTypeID=recordHTypeId ,
            Name='Test Name'
        );
        accList.add(acc);
        
        System.debug('acc id +++'+acc.Id);
        Account accPerson= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test',
            LastName='Person',
            PersonEmail='test@yahoo.com',
            PersonBirthdate = system.today(),
            Is_Sync_with_Household__c=false,
            Does_your_spouse_earn_an_income__pc = 'Yes',
            spouse_s_approximate_annual_income__pc = 2000,
            FinServ__MaritalStatus__pc = 'Married / Defacto (to applicant 2)',
            Year__pc = '1',            
            Months__pc = '1',
            Year_1__pc = '1',
            Months_1__pc = '1',
            FinServ__NumberOfChildren__pc = 3
        );
        
        Account acc2Person= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test',
            LastName='Test',
            PersonEmail='test@yahoo.com',
            PersonBirthdate = system.today(),
            FinServ__NumberOfChildren__pc = 3
        );
        
        accList.add(accPerson);
        accList.add(acc2Person);
        insert accList;
        
        Account accChild1= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test Child',
            LastName='Test LName',
            PersonEmail='test@yahoo.com',
            Is_Sync_with_Household__c=false,
            Child_Age__pc = '1 Year',
            Relationship_with_Applicant_1__c='Dependent',
            Dependent_Parent__c = accPerson.Id
        );
        
        insert accChild1;
        
        Account Ac = [Select Id,PersonContactId from Account Where Id =: accPerson.Id];
        
        System.debug('acid'+Ac.PersonContactId);
        opportunity op1 = new Opportunity()	;
        op1.Name = 'testing';
        op1.AccountId = acc.Id;
        op1.Applicant_1__c = accPerson.Id;
        op1.Applicant_2__c = acc2Person.Id;
        //op1.Contact_1__c = Ac.PersonContactId;
        //op1.Contact_2__c = accPerson.Id;    
        op1.Preferred_repayment_frequency__c = 'Monthly';  
        op1.Loan_Amount__c = 560;
        op1.StageName = 'Working';
        op1.Application_Supporting_Notes__c = 'hello';
        op1.CloseDate = System.today();
        insert op1;
        
        ResendSMSController.fetchContacts(op1.id);
        ResendSMSController.fetchPhone(op1.id, 'Test Person');
        ResendSMSController.resendSMS('qwert', op1.id, 'Test Person', 'FULL', 'Email only');
        ResendSMSController.getVoiStatus(string.valueOf(op1.Id), 'Test Person');
        
            
    }
    
    @isTest 
    public static void testMethod2(){
        Id accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();        
        
        Account Accnew = new Account();
        Accnew.Name = 'testing';
        Accnew.RecordTypeId = accRTId;
        insert Accnew;
        
        contact con = new contact();
        con.AccountId = Accnew.id;
        con.firstname = 'qwert';
        con.lastName = 'testing';
        con.Email = 'tazeem.khan@chazecloud.com';
        con.Is_Authorised_Signatory__c = true;
        insert con;
        
        
        voi_status__c temp = new  voi_status__c();
        temp.Contact__c = con.id;
        temp.Case_Status__c = 'Sent';
        insert temp;
        
        ResendSMSController.fetchAccount(Accnew.Id);
        
        ResendSMSController.sendSmsFromReferrer(Accnew.Id, 'test', '1234567890');       
        
       
    }

}