force-app/main/default/objects/Account/fields/Is_Sync_with_Household__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_with_Household__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sync with Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_with_Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Applicant_1__c</fullName>
    <label>Relationship with Applicant 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Ex-spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/link_Expire_code__c.field-meta.xml
<CustomField>
    <fullName>link_Expire_code__c</fullName>
    <label>link Expire code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Skip_VOI__c.field-meta.xml
<CustomField>
    <fullName>Skip_VOI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip VOI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Type_For__c.field-meta.xml
<CustomField>
    <fullName>VOI_Type_For__c</fullName>
    <label>VOI type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FULL</fullName>
                <default>true</default>
                <label>FULL</label>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>E-SIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VOITriggerTest.cls
@isTest
public class VOITriggerTest {
    
    @testsetup
    static void setdata(){
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        List<Account> accList= new List<Account>();
        
        VOI_Status__c vs = new VOI_Status__c();
        vs.Case_Status__c = 'Sent';
        vs.Skip_VOI__c = true;
        insert vs;
        
        Account accPerson= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test Person',
            LastName='Test LName',
            Phone ='1234567890',
            PersonEmail='test@yahoo.com',
            Is_Sync_with_Household__c=false,
            Relationship_with_Applicant_1__c='Client'
        );
        accList.add(accPerson);
        
        Account accPerson2= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test Person2',
            LastName='Test LName',
            Phone ='1234567890',
            PersonEmail='test@yahoo.com',
            Is_Sync_with_Household__c=false,
            Relationship_with_Applicant_1__c='Spouse'
        );
        accList.add(accPerson2);
        
        insert accList;
        
        Opportunity oppty = new Opportunity ();
        oppty.applicant_1__c = accPerson.Id;
        oppty.applicant_2__c = accPerson2.Id;
        oppty.name = 'test Oppty';
        oppty.StageName='Assessment Needed'; 
        oppty.CloseDate = Date.today();
        insert oppty;
        
        Opportunity oppty2 = new Opportunity ();
        oppty2.applicant_1__c = accPerson.Id;
        oppty2.applicant_2__c = accPerson2.Id;
        oppty2.name = 'test Oppty2';
        oppty2.StageName='Assessment Needed'; 
        oppty2.CloseDate = Date.today();
        insert oppty2;
        
    }
    
    @isTest
    public static void methodOne(){
        VOI_Status__c vs = [Select id, name from VOI_Status__c where Case_Status__c = 'Sent' LIMIT 1]; 
        vs.Case_Status__c = 'SUbmitted';
        update vs;
    }
    
    @isTest
    public static void OppUpdateTest(){
        Opportunity Opp = [SELECT Id,Applicant_1__r.personcontactId,Applicant_2__r.personcontactId FROM Opportunity WHERE Name= 'test Oppty2' LIMIT 1];
        List<voi_Status__c> voiList = new List<voi_Status__c>();
        voi_Status__c vc = new voi_Status__c();
        vc.Contact__c = Opp.Applicant_1__r.personcontactId;
        vc.Case_Status__c = 'Sent';
        vc.Opportunity__c = Opp.Id;
        vc.link_Expire_code__c ='ttttt';
        vc.VOI_Status__c = 'Sent';
        voiList.add(vc);
        
        voi_Status__c vc1 = new voi_Status__c();
        vc1.Contact__c = Opp.Applicant_2__r.personcontactId;
        vc1.Case_Status__c = 'Sent';
        vc1.Opportunity__c = Opp.Id;
        vc1.link_Expire_code__c ='ttttt';
        vc1.VOI_Status__c = 'Sent';
        voiList.add(vc1);
        
        insert voiList;
        
        List<VOI_Status__c> VsList = [Select id,VOI_Status__c,Contact__c from VOI_Status__c where Id IN: voiList];
        for(VOI_Status__c vss : VsList){
            if(vss.Contact__c == Opp.Applicant_1__r.personcontactId){
                vss.VOI_Status__c = 'Delivered';
            }
            if(vss.Contact__c == Opp.Applicant_2__r.personcontactId){
                vss.VOI_Status__c = 'Submitted';
            }
        }
        update VsList;
    }
    
    @istest
    public static void testAdviserTask(){
        Opportunity Opp = [SELECT Id,Applicant_1__r.personcontactId,Applicant_2__r.personcontactId FROM Opportunity WHERE Name= 'test Oppty2' LIMIT 1];
        List<voi_Status__c> voiList = new List<voi_Status__c>();
        voi_Status__c vc = new voi_Status__c();
        vc.Contact__c = Opp.Applicant_1__r.personcontactId;
        vc.Case_Status__c = 'Sent';
        vc.Opportunity__c = Opp.Id;
        vc.link_Expire_code__c ='ttttt';
        vc.VOI_Status__c = 'Sent';
        vc.VOI_Type_For__c = 'FULL';
        voiList.add(vc);
        insert voiList;
        
        List<VOI_Status__c> VsList = [Select id,VOI_Status__c,Contact__c from VOI_Status__c where Id IN: voiList];
        for(VOI_Status__c vss : VsList){
            vss.Case_Status__c = 'Submitted';
        }
        update VsList;
    }
}