force-app/main/default/objects/Account/fields/Is_Sync_with_Household__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_with_Household__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sync with Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_with_Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_Applicant_1__c</fullName>
    <label>Relationship with Applicant 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Ex-spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
                <default>true</default>
                <label>Priorities</label>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirm_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Settlement_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Settlement Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Current_Application_Sections__c</fullName>
    <label>Current Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__Household__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Household Opportunities</relationshipLabel>
    <relationshipName>HouseholdOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Relationship_to_Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Relationship_to_Applicant_2__c</fullName>
    <label>Relationship to Applicant 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Ex-spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenericBatchableTest.cls
@isTest
public class GenericBatchableTest {
	@testsetup
    static void setUpData(){
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recordHTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Household').getRecordTypeId();
        String oppRecordTypeId  = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Home Loan Refinance').getRecordTypeId();
        List<Account> accList= new List<Account>();
        Account acc= new Account(
            RecordTypeID=recordHTypeId ,
            Name='Test Name'
        );
        accList.add(acc);
        
        Account accPerson= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test Person',
            LastName='Test LName',
            PersonEmail='test@yahoo.com',
            Is_Sync_with_Household__c=false,
            Relationship_with_Applicant_1__c='Client'
        );
        accList.add(accPerson);
        
        Account accPerson2= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test Person2',
            LastName='Test LName',
            Phone ='1234567890',
            PersonEmail='test@yahoo.com',
            Is_Sync_with_Household__c=false,
            Relationship_with_Applicant_1__c='Spouse'
        );
        accList.add(accPerson2);
        
        insert accList;
        
        Opportunity oppty = new Opportunity ();
        oppty.applicant_1__c = accPerson.Id;
        oppty.applicant_2__c = accPerson2.Id;
        oppty.AccountId = acc.Id;
        oppty.FinServ__Household__c  = acc.Id;
        oppty.name = 'test Oppty';
        oppty.StageName='Assessment Needed'; 
        oppty.CloseDate = Date.today();
        oppty.Application_Sections__c ='Own and Owe'; 
        oppty.Current_Application_Sections__c ='Who is applying';
        oppty.Relationship_to_Applicant_2__c = 'Spouse';
        oppty.Confirm_Settlement_Date__c = true;
        oppty.RecordTypeId = oppRecordTypeId;
        insert oppty;
    }
    
    static testmethod void exeBatch(){
        GenericBatchable gb = New GenericBatchable();
        gb.queryStr = 'Select Id, Owner.IsActive, OwnerId, Applicant_1__c, Applicant_2__c,FinServ__Household__c, AccountId from opportunity where  ';  
        gb.queryStr += ' RecordType.Name in (\'Commercial Mortgage\',\'Commercial Property Purchase\',\'First Home Purchase\',\'Home Loan Construction\',\'Home Loan Purchase\',\'Home Loan Refinance\',\'Next Home Purchase\') ' ;
        gb.queryStr +=' ORDER BY Applicant_1__r.Name, LastModifiedDate desc';
        
        database.executeBatch(gb);
    }
}