force-app/main/default/objects/Account/fields/On_Board_Referral__c.field-meta.xml
<CustomField>
    <fullName>On_Board_Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Board Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referrer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Rating__c</fullName>
    <label>Referrer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
                <default>true</default>
                <label>Blue</label>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Referrer_Status__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Status__c</fullName>
    <label>Referrer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/contactTriggerHelperTest.cls
@isTest
public class contactTriggerHelperTest {
    
    @istest
    private static void testContactTrigger(){  
        
        Account acc = new Account(); 
        acc.Name ='Test';
        acc.On_Board_Referral__c = true;
        insert acc;
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Referrer').getRecordTypeId(); 
        Contact con = new contact(); 
        con.AccountId = acc.Id;
        con.recordTypeId  = recordTypeId;
        con.lastName = 'Test';
        con.Email ='rdxrakesh345@gmail.com';
        con.Referrer_Status__c = 'Active';
        con.Referrer_Rating__c = 'Gold';
        test.startTest();
        insert con;
        test.stopTest();
        Contact cont = [select id,Referrer_Status__c,Referrer_Rating__c from contact LIMIT 1];
        cont.Referrer_Rating__c = 'Silver';
        cont.Referrer_Status__c = 'Current';
        update cont;
    }
}