force-app/main/default/objects/Account/fields/On_Board_Referral__c.field-meta.xml
<CustomField>
    <fullName>On_Board_Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Board Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/contactTriggerHelper.cls
public class contactTriggerHelper {
    
    public void SendEmailToReferrer(List<contact> conList){
        String recTypeName = 'Referrer';
        EmailTemplate emailTemplate = [SELECT Id,Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Welcome_For_Referrer' ];
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Set<id> AccId = new Set<id>();
        for(contact con : conList){
            accId.add(con.AccountId);
        }
        
        Map<id, Boolean> checkRef = new Map<id, Boolean>();
        
        for(account acc : [Select Id, On_Board_Referral__c from Account where Id In: AccId]){
            if(acc.On_Board_Referral__c){
                if(!checkRef.containsKey(acc.Id)){
                    checkRef.put(acc.Id, true);
                }                                
            }
        }
        
        System.debug('checkRefcheckRef'+checkRef);
            for(contact con : conList){
                String recTyname = Schema.SObjectType.contact.getRecordTypeInfosById().get(con.RecordTypeId).getDeveloperName();
                SYstem.debug('recordTY'+recTyname);
                if(recTyname == recTypeName && checkRef.get(con.AccountId) == true){
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
                    email.setTemplateId(emailTemplate.id);         
                    email.setTargetObjectId(con.Id);
                    email.setTreatTargetObjectAsRecipient(false);
                    OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'personalapplications@parkerlane.com.au'];
                    if(owea != null){
                        if ( owea.size() > 0 ) {
                            email.setOrgWideEmailAddressId(owea.get(0).Id);
                        }
                    }
                    email.setReplyTo('personalapplications@parkerlane.com.au');
                    email.saveAsActivity = true;
                    string[] to = new string[] {con.email};  
                        email.setToAddresses(to);
                    mails.add(email);            
                }
            }
            try{
                if(mails != null && mails.size() > 0){
                    Messaging.sendEmail(mails);
                }
            }catch(Exception ex){
                Exception__c eror = new Exception__c();
                eror.Class_Name__c = 'new referrer Customer';
                eror.Method_Name__c = 'Contact Trigger';
                eror.Error_Message__c = ex.getMessage() + '' + ex.getLineNumber();
                insert eror;
            }            
        
    }
}