force-app/main/default/objects/Account/fields/On_Board_Referral__c.field-meta.xml
<CustomField>
    <fullName>On_Board_Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Board Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_View__c.field-meta.xml
<CustomField>
    <fullName>Portal_View__c</fullName>
    <label>Portal View</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin View</fullName>
            </value>
            <value>
                <fullName>Referrer View</fullName>
                <default>true</default>
                <label>Referrer View</label>
            </value>
            <value>
                <fullName>Agent View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status_before_handover__c.field-meta.xml
<CustomField>
    <fullName>Request_Status_before_handover__c</fullName>
    <label>Request Status before handover</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender_Agent__c.field-meta.xml
<CustomField>
    <fullName>Lender_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Lender Agent)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( AND( OR( ISPICKVAL( StageName , &apos;Quote&apos;) , ISPICKVAL( StageName , &apos;CPA Started&apos;))  , OR( ISPICKVAL( Current_Application_Sections__c ,&apos;Priorities&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Loan Recommendation&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Getting Started&apos;) ) )  ,&apos;Quote-#fd636b&apos;,
 
IF(ISPICKVAL( StageName , &apos;CPA Started&apos;),&apos;Applying-#ffb902&apos;,
    
IF( AND( OR( ISPICKVAL(StageName,  &apos;Packs Out&apos;),ISPICKVAL( StageName, &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;CPA Done&apos;)), NOT(Funding_Variation_Request__c)), &apos;Verifying-#FFDF8F&apos;,

IF( AND( OR( ISPICKVAL(StageName, &apos;Application&apos;) ,ISPICKVAL(StageName, &apos;Conditional&apos;)), NOT(Funding_Variation_Request__c)), &apos;Credit-#b4f6e0&apos;, 

IF(  AND(ISPICKVAL(StageName, &apos;Approved&apos;), TODAY()- DATEVALUE( Approved_Date__c )&lt; 90 )   , &apos;Approved-#3be8b0&apos;,
IF(  OR(AND (ISPICKVAL(StageName, &apos;Funding&apos;), (TODAY()- DATEVALUE( Approved_Date__c )&lt; 90)),(AND (OR(ISPICKVAL(StageName,  &apos;CPA Done&apos;),ISPICKVAL( StageName, &apos;Packs Out&apos;),ISPICKVAL( StageName , &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;Application&apos;),
ISPICKVAL( StageName , &apos;Conditional&apos;)) ,Funding_Variation_Request__c ))), &apos;Funding-#d063d3&apos;,
IF( ISPICKVAL(StageName, &apos;Settled (closed won)&apos;) , &apos;Funded-#4a154b&apos;,
IF( AND( OR(ISPICKVAL(StageName, &apos;Approved&apos;),ISPICKVAL(StageName, &apos;Funding&apos;)) ,TODAY()- DATEVALUE( Approved_Date__c )&gt; 90) , &apos;Expired-#FFFF00&apos;, 
IF( OR( ISPICKVAL(StageName, &apos;Closed Lost&apos;) ,ISPICKVAL(StageName, &apos;Nurturing&apos;),ISPICKVAL(StageName, &apos;Working&apos;)) , &apos;Closed-#f2f2f2&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuthorisationCertificateControllerTest.cls
@isTest
public class AuthorisationCertificateControllerTest {
    
    @isTest
    public static void authorisationTest(){
        String recordTypeRefId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Lender').getRecordTypeId();
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recordTypeConId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Lender Contact').getRecordTypeId();
        
        Account testAcc = new Account();
        testAcc.RecordTypeId  = recordTypeRefId;
        testAcc.Name = 'Test acc'; 
        testAcc.On_Board_Referral__c  = true; 
        insert testAcc;
        
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'test';
        testAcc1.LastName = 'opp';
        testAcc1.Phone = '1234567890';
        testAcc1.On_Board_Referral__c  = true;
        testAcc1.PersonEmail = 'testopp1@test.com';
        insert testAcc1;
        
        Contact testCon = new Contact();
        testCon.FirstName = 'TestRef';
        testCon.LastName = 'Con';
        testCon.AccountId = testAcc.Id;
        testCon.Admin__c = true;
        testCon.Status__c = 'Active';
        testCon.Portal_View__c = 'Admin View';
        testCon.Phone = '1234567890';
        testCon.RecordTypeId = recordTypeConId;
        testCon.Password__c = '1234';
        testCon.Email = 'testpass@gmail.com';
        insert testCon; 
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test opp1';
        opp1.Lender_Agent__c = testCon.id;
        opp1.StageName ='Approved';
        opp1.CloseDate = System.Today();
        opp1.Applicant_1__c = testAcc1.Id;
        opp1.Loan_Amount__c = 5000;
        opp1.Approved_Date__c = system.today().addDays(-1);
        insert opp1;
        
        List<Funding_Request__c> frList = new List<Funding_Request__c>();
        
        Funding_Request__c frData = new Funding_Request__c(); 
        frData.Request_Status_before_handover__c = 'Example';
        frData.Opportunity__c = opp1.id;
        
        test.startTest();
        if(frData != null){
        	insert frData;    
        }
        test.stopTest();
        
        PageReference pageRef = Page.FundingAuthorisationCertificatePDF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', frData.Id);
        
        AuthorisationCertificateController controller = new AuthorisationCertificateController();
        System.assertEquals(opp1.Name, controller.oppName);
        
    }
}