force-app/main/default/objects/Account/fields/On_Board_Referral__c.field-meta.xml
<CustomField>
    <fullName>On_Board_Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Board Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Case/fields/Referrer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Rating__c</fullName>
    <formula>TEXT(Contact.Referrer_Rating__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Referrer Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_View__c.field-meta.xml
<CustomField>
    <fullName>Portal_View__c</fullName>
    <label>Portal View</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin View</fullName>
            </value>
            <value>
                <fullName>Referrer View</fullName>
                <default>true</default>
                <label>Referrer View</label>
            </value>
            <value>
                <fullName>Agent View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Referrer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Rating__c</fullName>
    <label>Referrer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
                <default>true</default>
                <label>Blue</label>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referrer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Rating__c</fullName>
    <formula>TEXT(ReferredByContact__r.Referrer_Rating__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Referrer Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( AND( OR( ISPICKVAL( StageName , &apos;Quote&apos;) , ISPICKVAL( StageName , &apos;CPA Started&apos;))  , OR( ISPICKVAL( Current_Application_Sections__c ,&apos;Priorities&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Loan Recommendation&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Getting Started&apos;) ) )  ,&apos;Quote-#fd636b&apos;,
 
IF(ISPICKVAL( StageName , &apos;CPA Started&apos;),&apos;Applying-#ffb902&apos;,
    
IF( AND( OR( ISPICKVAL(StageName,  &apos;Packs Out&apos;),ISPICKVAL( StageName, &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;CPA Done&apos;)), NOT(Funding_Variation_Request__c)), &apos;Verifying-#FFDF8F&apos;,

IF( AND( OR( ISPICKVAL(StageName, &apos;Application&apos;) ,ISPICKVAL(StageName, &apos;Conditional&apos;)), NOT(Funding_Variation_Request__c)), &apos;Credit-#b4f6e0&apos;, 

IF(  AND(ISPICKVAL(StageName, &apos;Approved&apos;), TODAY()- DATEVALUE( Approved_Date__c )&lt; 90 )   , &apos;Approved-#3be8b0&apos;,
IF(  OR(AND (ISPICKVAL(StageName, &apos;Funding&apos;), (TODAY()- DATEVALUE( Approved_Date__c )&lt; 90)),(AND (OR(ISPICKVAL(StageName,  &apos;CPA Done&apos;),ISPICKVAL( StageName, &apos;Packs Out&apos;),ISPICKVAL( StageName , &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;Application&apos;),
ISPICKVAL( StageName , &apos;Conditional&apos;)) ,Funding_Variation_Request__c ))), &apos;Funding-#d063d3&apos;,
IF( ISPICKVAL(StageName, &apos;Settled (closed won)&apos;) , &apos;Funded-#4a154b&apos;,
IF( AND( OR(ISPICKVAL(StageName, &apos;Approved&apos;),ISPICKVAL(StageName, &apos;Funding&apos;)) ,TODAY()- DATEVALUE( Approved_Date__c )&gt; 90) , &apos;Expired-#FFFF00&apos;, 
IF( OR( ISPICKVAL(StageName, &apos;Closed Lost&apos;) ,ISPICKVAL(StageName, &apos;Nurturing&apos;),ISPICKVAL(StageName, &apos;Working&apos;)) , &apos;Closed-#f2f2f2&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/CaseAssignmentHandlerTest.cls
@isTest
public class CaseAssignmentHandlerTest {
    
    static testMethod void testCase(){
        String recordTypeRefId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recordTypeConId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Referrer').getRecordTypeId();
        
        Account testAcc = new Account();
        testAcc.RecordTypeId  = recordTypeRefId;
        testAcc.Name = 'Test acc'; 
        testAcc.On_Board_Referral__c  = true;
        insert testAcc;
        
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'test';
        testAcc1.LastName = 'opp';
        testAcc1.Phone = '1234567890';
        testAcc1.On_Board_Referral__c  = true;
        testAcc1.PersonEmail = 'testopp1@test.com';
        insert testAcc1;
        
        Contact testCon = new Contact();
        testCon.FirstName = 'TestRef';
        testCon.LastName = 'Con';
        testCon.AccountId = testAcc.Id;
        testCon.Admin__c = true;
        testCon.Status__c = 'Active';
        //testCon.Referrer_Rating__c = 'Platinum';
        testCon.Portal_View__c = 'Admin View';
        testCon.Phone = '1234567890';
        testCon.RecordTypeId = recordTypeConId;
        testCon.Email = 'test@testt.com';
        insert testCon; 
        
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test opp';
        opp1.StageName ='Approved';
        opp1.CloseDate = System.Today();
        opp1.Loan_Amount__c = 5000;
        opp1.Approved_Date__c = system.today().addDays(-1);
        insert opp1;   
        
        Case cs = new Case();
        cs.Opportunity__c = opp1.id;
        cs.Origin = 'Email';
        cs.SuppliedEmail = 'test@testt.com';
        insert cs;
    }
    
    static testMethod void testCaseOpp(){
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'test';
        testAcc1.LastName = 'oppp';
        testAcc1.Phone = '1234567890';
        testAcc1.On_Board_Referral__c  = true;
        testAcc1.PersonEmail = 'testopp11@test.com';
        insert testAcc1;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test opp';
        opp1.StageName ='Approved';
        opp1.CloseDate = System.Today();
        opp1.Loan_Amount__c = 5000;
        opp1.Approved_Date__c = system.today().addDays(-1);
        opp1.Applicant_1__c = testAcc1.Id;
        insert opp1;        
        
        Case cs = new Case();
        cs.Opportunity__c = opp1.id;
        cs.Origin = 'Email';
        cs.SuppliedEmail = 'testopp11@test.com';
        insert cs;
    }
    
     static testMethod void testElseCase(){        
        Case cs = new Case();
        insert cs;
    }
}