force-app/main/default/objects/Account/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Referred by Company)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_1_A1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_A1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 1 (A1)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_2_A2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_A2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2 (A2)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Applicant 2 (A2))</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/BusinessDays__c.field-meta.xml
<CustomField>
    <fullName>BusinessDays__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BusinessDays</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 1)</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 2)</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Status__c</fullName>
    <label>Customer Authorisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request sent to customer(s)</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 2</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 1</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Type__c</fullName>
    <label>Customer Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Either to sign</fullName>
            </value>
            <value>
                <fullName>Both to sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Date_Last_Request_Status_Changes__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Request_Status_Changes__c</fullName>
    <label>Date Last Request Status Changes</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Funding_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Funding_On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Person_Requesting__c.field-meta.xml
<CustomField>
    <fullName>Person_Requesting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Requesting</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment requested by supplier</fullName>
            </value>
            <value>
                <fullName>Payment requested by supplier (pending contract)</fullName>
            </value>
            <value>
                <fullName>Variation requested by customer</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer (pending contract)</fullName>
            </value>
            <value>
                <fullName>Payment authorised by customer</fullName>
            </value>
            <value>
                <fullName>Funding handover call completed</fullName>
            </value>
            <value>
                <fullName>Payment funded</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment in full before installation</fullName>
            </value>
            <value>
                <fullName>Payment in full after installation</fullName>
            </value>
            <value>
                <fullName>Part payment before installation</fullName>
            </value>
            <value>
                <fullName>Remainder of payment after installation</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <label>Requested by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Variation_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Variation_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variation Requested By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Variation Requested By)</relationshipLabel>
    <relationshipName>Funding_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred by Company)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailyVariationReminder.cls
global  class DailyVariationReminder implements Schedulable {
    global void execute(SchedulableContext SC){
        Map<integer, String> dayToSubjectMap = new Map<integer, String>{
            1 => 'Friendly reminder!',
                2 => 'Friendly reminder! {!Variation_Requested_By__c} has requested a variation to your approval and your action is required.',
                3 => 'Your urgent action is required! {!Variation_Requested_By__c} has requested a variation to your approval.',
                4 => 'Your urgent action is required! {!Variation_Requested_By__c} has requested a variation to your approval.',
                5 => 'Final reminder! {!Variation_Requested_By__c} has requested a variation to your approval.'
                };
                    Map<integer, String> dayToSubjectMap2 = new Map<integer, String>{
                        1 => 'Friendly reminder! {!Variation_Requested_By__c} has requested payment.',
                            2 => 'Friendly reminder! {!Variation_Requested_By__c} has requested payment and your action is required.',
                            3 => 'Your urgent action is required! {!Variation_Requested_By__c} has requested payment.',
                            4 => 'Your urgent action is required! {!Variation_Requested_By__c} has requested payment.',
                            5 => 'Final reminder! {!Variation_Requested_By__c} has requested payment.'
                            };
                                List<String> emailTemplateNames = New List<String>{'FundingOnHold','FundingNotAuthorised','RequestedByApplicantORReferrer(App2)',
                                    'VariationRequested','VariationRequested2','VariationRequested(EmailToReferrer)','FundingAuthorised(EmailToReferrer)','Funded(EmailToReferrer)'
                                    ,'Funded(EmailToCustomers)','RequestedByApplicantORReferrer','VariationNotAuthorised(EmailToReferrer)','VariationNotAuthorised(EmailToOtherApplicant)'};
                                        Map<String, Id> emailTempIdMap = New Map<String, Id>();
        for(EmailTemplate emailTemp: [SELECT id, Name  FROM EmailTemplate WHERE Name IN: emailTemplateNames]){
            emailTempIdMap.put(emailTemp.Name, emailTemp.Id);
        }
        OrgWideEmailAddress[] owea = [SELECT Id from OrgWideEmailAddress WHERE Address =: UtilityClass.adminEmail];
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        list<Funding_Request__c> frRec = [select id,Opportunity__r.Applicant_1__c,BusinessDays__c,Opportunity__r.Contact_1__c,Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c, Requested_by__c,
                                          Opportunity__r.Referred_by_Company__c,Applicant_2_A2__c,Applicant_2_A2__r.PersonEmail,Applicant_1_A1__c,Applicant_1_A1__r.PersonEmail,
                                          Customer_Authorisation_Type__c,Date_Last_Request_Status_Changes__c,Customer_Authorisation_Status__c,Variation_Requested_By__r.name,Opportunity__c,
                                          Funding_On_Hold__c,Person_Requesting__r.id,Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId,Person_Requesting__c,Request_Status__c,Opportunity__r.FinServ__ReferredByContact__c,
                                          Opportunity__r.FinServ__ReferredByContact__r.Email from Funding_Request__c where Request_Status__c = 'Variation requested by customer' AND Opportunity__c != null];
        UpdateBusinessDays();
        set<id> oppId = new set<id>();
        for(Funding_Request__c fr : frRec){
            oppId.add(fr.Opportunity__c);
        }
        Map<id, list<id>> conMap = new Map<id, list<id>>();
        Map<id,string> textMap = new Map<id,string>();
        for(VOi_Status__c vs : [select id,Case_Status__c,Contact__c,Contact__r.name,Opportunity__c from VOi_Status__c where opportunity__c IN: oppId AND (Case_Status__c='Sent' OR Case_Status__c='Delivered')]){
            if(!conMap.containsKey(vs.Opportunity__c)){
                conMap.put(vs.Opportunity__c,new list<id>{vs.Contact__c});
                textMap.put(vs.Opportunity__c, vs.Contact__r.name + '<br/>'); 
            }
            else{
                conMap.get(vs.Opportunity__c).add(vs.Contact__c);
                string str = textMap.get(vs.Opportunity__c) + vs.Contact__r.name + '<br/>';
                textMap.put(vs.Opportunity__c, str);
            }
        }
        for(Funding_Request__c fr : [select id,Opportunity__r.Referred_by_Company__r.Name,Request_Type__c,Opportunity__r.Name,Date_Last_Request_Status_Changes__c,Applicant_2_A2__r.PersonEmail,Variation_Requested_By__r.name,Opportunity__c,Applicant_1_A1__c,Applicant_2_A2__c,Applicant_1_A1__r.personContactId,Applicant_2_A2__r.personContactId,Opportunity__r.Applicant_2__r.personContactId,Applicant_1_A1__r.Name,Applicant_2_A2__r.Name,Applicant_1_A1__r.Phone,Applicant_2_A2__r.Phone,Person_Requesting__r.name,Variation_Requested_By__c,Opportunity__r.FinServ__ReferredByContact__c,Opportunity__r.FinServ__ReferredByContact__r.Email,Opportunity__r.Applicant_1__r.personContactId,Opportunity__r.Applicant_2__r.Name,Opportunity__r.Applicant_1__r.Name,Opportunity__r.Applicant_1__c,Opportunity__r.Applicant_2__c,BusinessDays__c,Applicant_1_A1__r.PersonEmail from Funding_Request__c where Opportunity__c IN:conMap.keyset() AND Request_Status__c = 'Variation requested by customer' ]){
            Integer days = integer.valueOf(fr.BusinessDays__c);
            system.debug('days '+days);
            if(days < 6 && days != 0){
                system.debug('variationTT' +fr.Variation_Requested_By__c);
                system.debug('variationTT2' +fr.Variation_Requested_By__r.name);
                system.debug('variationTT3' +fr.Request_Type__c);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                //system.debug('con'+vs.Contact__c);
                system.debug('frcon'+fr.Applicant_1_A1__r.personContactId);
                if(conMap.get(fr.Opportunity__c).contains(fr.Applicant_1_A1__r.personContactId)){
                    system.debug('1st');
                    mail.setTemplateId(emailTempIdMap.get('VariationRequested'));
                    mail.setTargetObjectId(fr.Applicant_1_A1__r.personContactId);
                    mail.setTreatTargetObjectAsRecipient(false);
                    mail.setUseSignature(false);
                    mail.Setwhatid(fr.Id);
                    String sub = dayToSubjectMap.get(days);
                    sub = sub.replace('{!Variation_Requested_By__c}', fr.Variation_Requested_By__r.name);
                    //mail.setSubject(sub);
                    system.debug('subject'+sub);
                    
                    mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('VariationRequested'), fr.Applicant_1_A1__r.personContactId, fr.Id);
                    mail.setSubject(sub);
                    system.debug('mail'+mail);
                    if(owea.size() > 0){
                        mail.setorgWideEmailAddressId(Owea.get(0).Id);
                    }
                    List<string> sendTo = new List<string>();
                    sendTo.add(fr.Applicant_1_A1__r.PersonEmail);
                    mail.setToAddresses(sendTo);                
                    emailList.add(mail);
                    if(fr.Variation_Requested_By__c == fr.Applicant_1_A1__c){
                        system.debug('istOf1');
                        string txt = 'Hi '+fr.Applicant_1_A1__r.Name+', Action required! We have received your variation request but you must first sign the updated credit proposal before we can process your request. Please refer to your email to review and approve. The Parker Lane team :)';
                        sendMessageForVariation(fr.Applicant_1_A1__r.Phone, txt);
                    }
                    else if(fr.Variation_Requested_By__c == fr.Applicant_2_A2__c){
                        system.debug('2ndOf1');
                        string txt = 'Hi '+fr.Applicant_1_A1__r.Name+', Action required! '+fr.Person_Requesting__r.name+' has requested a variation to your approved limit and we require your authorisation. Please refer to your email to review and approve. The Parker Lane team :)';
                        sendMessageForVariation(fr.Applicant_1_A1__r.Phone, txt);
                    }
                }
                 if(conMap.get(fr.Opportunity__c).contains(fr.Applicant_2_A2__r.personContactId)){
                    system.debug('2nd');
                    mail.setTemplateId(emailTempIdMap.get('VariationRequested2'));
                    mail.setTargetObjectId(fr.Applicant_2_A2__r.personContactId);
                    mail.setTreatTargetObjectAsRecipient(false);
                    mail.setUseSignature(false);
                    mail.Setwhatid(fr.Id);
                    String subject = dayToSubjectMap.get(days);
                    subject = subject.replace('{!Variation_Requested_By__c}', fr.Variation_Requested_By__r.name);
                    mail.setSubject(subject);
                    mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('VariationRequested2'), fr.Applicant_2_A2__r.personContactId, fr.Id);
                    if(owea.size() > 0){
                        mail.setorgWideEmailAddressId(Owea.get(0).Id);
                    }
                    List<string> sendTo = new List<string>();
                    sendTo.add(fr.Applicant_2_A2__r.PersonEmail);
                    mail.setToAddresses(sendTo);                
                    emailList.add(mail);
                    if(fr.Variation_Requested_By__c == fr.Applicant_2_A2__c){
                        system.debug('2ndOf1');
                        string txt = 'Hi '+fr.Applicant_2_A2__r.Name+', Action required! We have received your variation request but you must first sign the updated credit proposal before we can process your request. Please refer to your email to review and approve. The Parker Lane team :)';
                        sendMessageForVariation(fr.Applicant_2_A2__r.Phone, txt);
                    }
                    else if(fr.Variation_Requested_By__c == fr.Applicant_1_A1__c){
                        system.debug('2ndOf2');
                        string txt = 'Hi '+fr.Applicant_2_A2__r.Name+', Action required! '+fr.Person_Requesting__r.name+' has requested a variation to your approved limit and we require your authorisation. Please refer to your email to review and approve. The Parker Lane team :)';
                        sendMessageForVariation(fr.Applicant_2_A2__r.Phone, txt);
                    }
                }
            }
            else if(days == 6){
                if(fr.Opportunity__r.Referred_by_Company__c != null){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setTemplateId(emailTempIdMap.get('VariationNotAuthorised(EmailToReferrer)'));
                    mail.setTargetObjectId(fr.Opportunity__r.FinServ__ReferredByContact__c);
                    mail.setTreatTargetObjectAsRecipient(false);
                    mail.setUseSignature(false);
                    mail.Setwhatid(fr.Id);
                    EmailTemplate emailTemp = [SELECT id,subject, Name,Markup  FROM EmailTemplate WHERE Name ='VariationNotAuthorised(EmailToReferrer)' limit 1];
                    String templateBody = emailTemp.Markup;
                    templateBody = templateBody.replace('[relatedTo.Opportunity__r.Referred_by_Company__r.Name]',fr.Opportunity__r.Referred_by_Company__r.Name);
                    templateBody = templateBody.replace('[applicant names]', textMap.get(fr.Opportunity__c));
                    templateBody = templateBody.replace('[relatedTo.Opportunity__r.Name]',fr.Opportunity__r.Name);
                    String subject = 'Funding delayed! We’ve been unable to reach your customers to complete the variation requested by '+fr.Variation_Requested_By__r.Name;
                    mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('VariationNotAuthorised(EmailToReferrer)'), fr.Opportunity__r.FinServ__ReferredByContact__c, fr.Id);
                    mail.setSubject(subject);
                    mail.setHtmlBody(templateBody);
                    if(owea.size() > 0){
                        mail.setorgWideEmailAddressId(Owea.get(0).Id);
                    }
                    List<string> sendTo = new List<string>();
                    sendTo.add(fr.Opportunity__r.FinServ__ReferredByContact__r.Email);
                    mail.setToAddresses(sendTo);                
                    emailList.add(mail);
                }
                if(fr.Opportunity__r.Applicant_2__c != null && conMap.get(fr.Opportunity__c).size() == 1){
                    string conID = conMap.get(fr.Opportunity__c)[0];
                    String dynmaic1,dynmaic2,targetID;
                    if(conID == fr.Opportunity__r.Applicant_1__r.personContactId){
                        dynmaic1 = fr.Opportunity__r.Applicant_1__r.Name;
                        dynmaic2 = fr.Opportunity__r.Applicant_2__r.Name;
                        targetID = fr.Opportunity__r.Applicant_1__r.personContactId;
                    }
                    else if(conID == fr.Opportunity__r.Applicant_2__r.personContactId){
                        dynmaic1 = fr.Opportunity__r.Applicant_2__r.Name;
                        dynmaic2 = fr.Opportunity__r.Applicant_1__r.Name;
                        targetID = fr.Opportunity__r.Applicant_2__r.personContactId;
                    }
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setTemplateId(emailTempIdMap.get('VariationNotAuthorised(EmailToOtherApplicant)'));
                    mail.setTargetObjectId(targetID);
                    mail.setTreatTargetObjectAsRecipient(false);
                    mail.setUseSignature(false);
                    mail.Setwhatid(fr.Id);
                    EmailTemplate emailTemp = [SELECT id,subject, Name,Markup  FROM EmailTemplate WHERE Name ='VariationNotAuthorised(EmailToOtherApplicant)' limit 1];
                    String templateBody = emailTemp.Markup;
                    templateBody = templateBody.replace('[dynamic element 1]',dynmaic1);
                    templateBody = templateBody.replace('[dynamic element 2]', dynmaic2);
                    String subject = 'Funding delayed! We’ve been unable to reach '+dynmaic1 +'to authorise payment.';
                    mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('VariationNotAuthorised(EmailToOtherApplicant)'), targetID, fr.Id);
                    mail.setSubject(subject);
                    mail.setHtmlBody(templateBody);
                    if(owea.size() > 0){
                        mail.setorgWideEmailAddressId(Owea.get(0).Id);
                    }
                    List<string> sendTo = new List<string>();
                    sendTo.add(fr.Opportunity__r.FinServ__ReferredByContact__r.Email);
                    mail.setToAddresses(sendTo);                
                    emailList.add(mail);
                }
            }
        }
        
        list<Funding_Request__c> frRec2 = [select id,Name,Opportunity__r.Name,Opportunity__r.Applicant_1__c,BusinessDays__c,Opportunity__r.Contact_1__c,Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c, Requested_by__c,Applicant_1_A1__r.Phone,Opportunity__r.Purpose__c,
                                           Opportunity__r.Referred_by_Company__c,Applicant_2_A2__c,Applicant_2_A2__r.PersonEmail,Applicant_1_A1__c,Applicant_1_A1__r.PersonEmail,Applicant_1_A1__r.Name,Opportunity__r.Referred_by_Company__r.Name,
                                           Customer_Authorisation_Type__c,Date_Last_Request_Status_Changes__c,Opportunity__r.Contact_2__c,Customer_Authorisation_Status__c,Variation_Requested_By__r.name,Opportunity__c,Applicant_2_A2__r.Name,Applicant_2_A2__r.Phone,Person_Requesting__r.Name,
                                           Funding_On_Hold__c,Person_Requesting__r.id,Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId,Person_Requesting__c,Request_Status__c,Opportunity__r.FinServ__ReferredByContact__c,
                                           Opportunity__r.FinServ__ReferredByContact__r.Email from Funding_Request__c where Opportunity__c != null];
        
        for(Funding_Request__c frR :frRec2){            
            Integer days = integer.valueOf(frR.BusinessDays__c);
            if((frR.Request_Status__c == 'Payment requested by supplier' || frR.Request_Status__c == 'Payment requested by supplier (pending contract)')
               || (frR.Request_Status__c == 'Payment requested by customer' || frR.Request_Status__c == 'Payment requested by customer (pending contract)') &&
               (frR.Requested_by__c == 'Customer' || frR.Requested_by__c == 'Supplier')){
                   if(days < 6 && days != 0){
                       list<String> sendList = new list<string>();
                       if(frR.Applicant_2_A2__c != null){
                           if(frR.Customer_Authorisation_Type__c == 'Either to sign'){
                               sendList.add(frR.Applicant_1_A1__r.PersonEmail);
                           }
                           else if(frR.Customer_Authorisation_Type__c == 'Both to sign'){
                               sendList.add(frR.Applicant_1_A1__r.PersonEmail);
                               sendList.add(frR.Applicant_2_A2__r.PersonEmail);
                           }
                       }
                       else if(frR.Applicant_2_A2__c == null){
                           sendList.add(frR.Applicant_1_A1__r.PersonEmail);
                       }
                       if(!sendList.isEmpty()){
                           for(String frval : sendList){
                               Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                               if(frval == frR.Applicant_1_A1__r.PersonEmail){
                                   mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('RequestedByApplicantORReferrer'), frR.Opportunity__r.Contact_1__c, frR.Id);
                               }
                               if(frval == frR.Applicant_2_A2__r.PersonEmail){
                                   mail = Messaging.renderStoredEmailTemplate(emailTempIdMap.get('RequestedByApplicantORReferrer(App2)'), frR.Opportunity__r.Contact_2__c, frR.Id); 
                               }
                               String subject = dayToSubjectMap2.get(days);
                               subject = subject.replace('{!Variation_Requested_By__c}', frR.Person_Requesting__r.Name);
                               mail.setSubject(subject);
                               mail.setTreatTargetObjectAsRecipient(false);
                               mail.setUseSignature(false);
                               List<string> sendTo = new List<string>();
                               sendTo.add(frval);
                               mail.setToAddresses(sendTo);
                               if(owea.size() > 0){
                                   mail.setorgWideEmailAddressId(Owea.get(0).Id);
                               }  
                               system.debug('mail'+mail);
                               if(!sendTo.isEmpty()){
                                   emailList.add(mail);
                               }
                           } 
                       }                      
                       
                       if(frR.Requested_by__c == 'Supplier'){
                           if(frR.Applicant_2_A2__c != null){
                               if(frR.Customer_Authorisation_Type__c != null && frR.Customer_Authorisation_Type__c == 'Either to sign'){
                                   sendMessage(frR.Requested_by__c, frR.Applicant_1_A1__r.Phone, frR.Applicant_1_A1__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                               }
                               else if(frR.Customer_Authorisation_Type__c != null && frR.Customer_Authorisation_Type__c == 'Both to sign'){
                                   sendMessage(frR.Requested_by__c, frR.Applicant_1_A1__r.Phone, frR.Applicant_1_A1__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                                   sendMessage(frR.Requested_by__c, frR.Applicant_2_A2__r.Phone, frR.Applicant_2_A2__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                               }
                           }
                           else if(frR.Applicant_2_A2__c == null){
                               sendMessage(frR.Requested_by__c, frR.Applicant_1_A1__r.Phone, frR.Applicant_1_A1__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                           }
                       }                       
                       if(frR.Requested_by__c == 'Customer'){
                           if(frR.Applicant_2_A2__c != null){
                               if(frR.Person_Requesting__c != null){
                                   if(frR.Customer_Authorisation_Type__c != null && frR.Customer_Authorisation_Type__c == 'Both to sign' && frR.Person_Requesting__r.id == frR.Applicant_1_A1__r.PersonContactId){
                                       sendMessage(frR.Requested_by__c, frR.Applicant_2_A2__r.Phone, frR.Applicant_2_A2__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                                   }
                                   else if(frR.Customer_Authorisation_Type__c != null && frR.Customer_Authorisation_Type__c == 'Both to sign' && frR.Person_Requesting__r.id == frR.Applicant_2_A2__r.PersonContactId){
                                       sendMessage(frR.Requested_by__c, frR.Applicant_1_A1__r.Phone, frR.Applicant_1_A1__r.Name, frR.Person_Requesting__r.Name, frR.Opportunity__r.Referred_by_Company__r.Name, frR.Opportunity__r.Purpose__c);
                                   }
                               }
                           }
                       }
                   }                   
               }else if(days == 6){
                   mailOnCompletion(frRec2);
               }
        }
        if(!emailList.isEmpty()){
            Messaging.sendEmail(emailList);            
        }
    }
    public static void UpdateBusinessDays(){
        //Kunal Sir Code for Business Days logic Starts.
        list<Funding_Request__c> frList = [select id,Opportunity__r.Applicant_1__c,BusinessDays__c,Opportunity__r.Contact_1__c,Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c, Requested_by__c,
                                          Opportunity__r.Referred_by_Company__c,Applicant_2_A2__c,Applicant_2_A2__r.PersonEmail,Applicant_1_A1__c,Applicant_1_A1__r.PersonEmail,
                                          Customer_Authorisation_Type__c,Date_Last_Request_Status_Changes__c,Customer_Authorisation_Status__c,Variation_Requested_By__r.name,Opportunity__c,
                                          Funding_On_Hold__c,Person_Requesting__r.id,Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId,Person_Requesting__c,Request_Status__c,Opportunity__r.FinServ__ReferredByContact__c,
                                          Opportunity__r.FinServ__ReferredByContact__r.Email from Funding_Request__c where Opportunity__c != null];
        DateTime myDateTime = DateTime.now();
        String dayOfWeek = myDateTime.format('EEEE');
        List<Funding_Request__c> frListToUpdate = new List<Funding_Request__c>();
        for(Funding_Request__c fundReq : frList){
            Integer days = (fundReq.Date_Last_Request_Status_Changes__c.Date()).daysBetween(system.today());
            Datetime dt = fundReq.Date_Last_Request_Status_Changes__c;
            fundReq.BusinessDays__c = 0;
            system.debug('DaysBetween '+days);
            system.debug('last date '+dt);
            for(integer i=1; i<=days; i++){
                Datetime diff = dt + i;
                if(diff.format('EEEE') != 'Saturday' && diff.format('EEEE') != 'Sunday'){
                    fundReq.BusinessDays__c += 1;
                }
            }
            frListToUpdate.add(fundReq);
        }
        if(!frListToUpdate.isEmpty()){
            update frListToUpdate; 
        }
        // Kunal Sir Code End.
    }
    public static void sendMessage(String reqBy, String phone, String fName, String personReq, String RefCompany, String purpose){
        List<smagicinteract__smsMagic__c> smsObjectList = new List<smagicinteract__smsMagic__c> ();
        String templateText = '';
        if(reqBy == 'Supplier'){
            templateText = 'Hi '+fName+', Action required! '+personReq+ ' at '+RefCompany+ 
                ' has requested payment and we require your approval. Please refer to your email to review and approve. The Parker Lane team :)';
        }
        else if(reqBy == 'Customer'){
            templateText = 'Hi '+fName+', Action required! '+personReq+ 
                '  has requested that your ' +purpose+ ' loan is funded and we require your approval. Please refer to your email to review and approve. The Parker Lane team :)';
        }
        smagicinteract__smsMagic__c smsObject = new smagicinteract__smsMagic__c();
        smsObject.smagicinteract__SenderId__c = 'parkerlane';
        smsObject.smagicinteract__PhoneNumber__c = phone;//contact.MobilePhone;
        smsObject.smagicinteract__Name__c = 'test';//contact.Name; // recordsname
        smsObject.smagicinteract__ObjectType__c = 'Funding Request'; // record type
        smsObject.smagicinteract__disableSMSOnTrigger__c = 0; // this field either be 0 or 1, if you specify the value as 1 then sms will not get send but entry of sms will get create under SMS History object
        smsObject.smagicinteract__external_field__c = smagicinteract.ApexAPI.generateUniqueKey();
        smsObject.smagicinteract__SMSText__c = templateText;
        //smsObject.smagicinteract__Funding_Request__c = fundingId;
        smsObjectList.add(smsObject);
        system.debug('smsObjectList'+smsObjectList);
        Database.SaveResult[] results = Database.insert(smsObjectList, false);
        for(Database.SaveResult result : results) {
            if(result.isSuccess()) {
                //  System.debug('Successfully inserted Accounts : ' + result.getId());
            } else {
                for(Database.Error error : result.getErrors()) {
                    System.debug('Error Status : ' + error.getMessage() + ' : ' + 'Error Fields : ' + error.getFields());
                }
            }
        }
    }
    
    public static void sendMessageForVariation(String phone, String templateText){
        List<smagicinteract__smsMagic__c> smsObjectList = new List<smagicinteract__smsMagic__c> ();
        smagicinteract__smsMagic__c smsObject = new smagicinteract__smsMagic__c();
        smsObject.smagicinteract__SenderId__c = 'parkerlane';
        smsObject.smagicinteract__PhoneNumber__c = phone;//contact.MobilePhone;
        smsObject.smagicinteract__Name__c = 'test';//contact.Name; // recordsname
        smsObject.smagicinteract__ObjectType__c = 'Funding Request'; // record type
        smsObject.smagicinteract__disableSMSOnTrigger__c = 0; // this field either be 0 or 1, if you specify the value as 1 then sms will not get send but entry of sms will get create under SMS History object
        smsObject.smagicinteract__external_field__c = smagicinteract.ApexAPI.generateUniqueKey();
        smsObject.smagicinteract__SMSText__c = templateText;
        //smsObject.smagicinteract__Funding_Request__c = fundingId;
        smsObjectList.add(smsObject);
        Database.SaveResult[] results = Database.insert(smsObjectList, false);
        for(Database.SaveResult result : results) {
            if(result.isSuccess()) {
                //  System.debug('Successfully inserted Accounts : ' + result.getId());
            } else {
                for(Database.Error error : result.getErrors()) {
                    System.debug('Error Status : ' + error.getMessage() + ' : ' + 'Error Fields : ' + error.getFields());
                }
            }
        }
    }
    
    public static void mailOnCompletion(list<Funding_Request__c> FrDetail){
        OrgWideEmailAddress[] owea = [SELECT Id from OrgWideEmailAddress WHERE Address =:UtilityClass.adminEmail];
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        list<String> conEmailList = new list<String>();
        set<id> companyList = new set<id>();
        list<contact> conList = new list<contact>();
        for(Funding_Request__c Fr : FrDetail){
            companyList.add(Fr.Opportunity__r.Referred_by_Company__c);
        }
        if(companyList != null){
            conList = [Select id, Email from contact where AccountId IN: companyList AND Admin__c = true];
        }            
        for(contact cont : conList){
            if(cont.Email != null){
                conEmailList.add(cont.Email);
            }
        }
        for(Funding_Request__c getFr : FrDetail){
            if((getFr.Customer_Authorisation_Status__c == 'Pending Applicant 1' || getFr.Customer_Authorisation_Status__c == 'Pending Applicant 2') && getFr.BusinessDays__c == 6){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                EmailTemplate et=[Select id, Subject, Body from EmailTemplate where Name = 'FundingNotAuthorised(EmailToApplicant)']; 
                mail.setTemplateId(et.id);
                mail.setTargetObjectId(getFr.Opportunity__r.Contact_1__c);
                mail.setTreatTargetObjectAsRecipient(false);
                mail.setUseSignature(false);
                String appName = '';
                if(getFr.Customer_Authorisation_Status__c != null && getFr.Customer_Authorisation_Status__c == 'Pending Applicant 1'){
                    appName = getFr.Applicant_1_A1__r.Name;
                }
                else if(getFr.Customer_Authorisation_Status__c != null && getFr.Customer_Authorisation_Status__c == 'Pending Applicant 2'){
                    appName = getFr.Applicant_2_A2__r.Name;
                }
                mail = Messaging.renderStoredEmailTemplate(et.id, getFr.Opportunity__r.Contact_1__c, getFr.Id);
                String sub = 'Funding delayed! We’ve been unable to reach '+ appName + ' to authorise payment.';
                mail.setSubject(sub);
                mail.Setwhatid(getFr.Id);
                
                if(owea.size() > 0){
                    mail.setorgWideEmailAddressId(Owea.get(0).Id);
                }
                
                List<string> sendTo = new List<string>();
                if(getFr.Customer_Authorisation_Status__c != null && getFr.Customer_Authorisation_Status__c == 'Pending Applicant 1'){
                    sendTo.add(getFr.Applicant_2_A2__r.PersonEmail);
                }
                else if(getFr.Customer_Authorisation_Status__c != null && getFr.Customer_Authorisation_Status__c == 'Pending Applicant 2'){
                    sendTo.add(getFr.Applicant_1_A1__r.PersonEmail);
                }
                mail.setToAddresses(sendTo);                   
                emailList.add(mail);  
            }
            
            //Funding not authorised at the completion of reminder emails - email to referrer
            if((getFr.Request_Status__c == 'Payment requested by customer' || getFr.Request_Status__c == 'Payment requested by customer (pending contract)')
               || (getFr.Request_Status__c == 'Payment requested by supplier' || getFr.Request_Status__c == 'Payment requested by supplier (pending contract)') 
               && getFr.Opportunity__r.Referred_by_Company__c != null && getFr.BusinessDays__c == 6){
                   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                   EmailTemplate et=[Select id, Subject, Body from EmailTemplate where Name = 'FundingNotAuthorised']; 
                   mail.setTemplateId(et.id);
                   mail.setTargetObjectId(getFr.Opportunity__r.Contact_1__c);
                   String[] oppName = getFr.Opportunity__r.Name.split(',');
                   mail = Messaging.renderStoredEmailTemplate(et.Id, getFr.Opportunity__r.Contact_1__c, getFr.Id);
                   String sub = 'Funding delayed! We’ve been unable to reach '+ oppName + ' to authorise payment.';
                   mail.setSubject(sub);
                   mail.setTreatTargetObjectAsRecipient(false);
                   mail.setUseSignature(false);
                   mail.Setwhatid(getFr.Id);
                   
                   if(owea.size() > 0){
                       mail.setorgWideEmailAddressId(Owea.get(0).Id);
                   }
                   
                   List<string> sendTo = new List<string>();
                   sendTo.add(getFr.opportunity__r.FinServ__ReferredByContact__r.Email);
                   sendTo.addall(conEmailList);
                   mail.setToAddresses(sendTo);                    
                   emailList.add(mail);                    
               }
        }
        if(!emailList.isEmpty()){
            Messaging.sendEmail(emailList);
        }
    }    
}