force-app/main/default/objects/Account/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Referred by Company)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/business.recordType-meta.xml
<RecordType>
    <fullName>business</fullName>
    <active>true</active>
    <label>business</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_View__c.field-meta.xml
<CustomField>
    <fullName>Portal_View__c</fullName>
    <label>Portal View</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin View</fullName>
            </value>
            <value>
                <fullName>Referrer View</fullName>
                <default>true</default>
                <label>Referrer View</label>
            </value>
            <value>
                <fullName>Agent View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_1_A1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_A1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 1 (A1)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_2_A2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_A2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2 (A2)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Applicant 2 (A2))</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 1)</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Status__c</fullName>
    <label>Customer Authorisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request sent to customer(s)</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 2</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 1</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Type__c</fullName>
    <label>Customer Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Either to sign</fullName>
            </value>
            <value>
                <fullName>Both to sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Date_Last_Request_Status_Changes__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Request_Status_Changes__c</fullName>
    <label>Date Last Request Status Changes</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Person_Requesting__c.field-meta.xml
<CustomField>
    <fullName>Person_Requesting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Requesting</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment requested by supplier</fullName>
            </value>
            <value>
                <fullName>Payment requested by supplier (pending contract)</fullName>
            </value>
            <value>
                <fullName>Variation requested by customer</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer (pending contract)</fullName>
            </value>
            <value>
                <fullName>Payment authorised by customer</fullName>
            </value>
            <value>
                <fullName>Funding handover call completed</fullName>
            </value>
            <value>
                <fullName>Payment funded</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment in full before installation</fullName>
            </value>
            <value>
                <fullName>Payment in full after installation</fullName>
            </value>
            <value>
                <fullName>Part payment before installation</fullName>
            </value>
            <value>
                <fullName>Remainder of payment after installation</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <label>Requested by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Variation_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Variation_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variation Requested By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Variation Requested By)</relationshipLabel>
    <relationshipName>Funding_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred by Company)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Current_VOI_section__c.field-meta.xml
<CustomField>
    <fullName>Current_VOI_section__c</fullName>
    <label>Current VOI section</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VOI_Type_For__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email Verificaiton</fullName>
                <default>true</default>
                <label>Email Verificaiton</label>
            </value>
            <value>
                <fullName>Id Upload</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>CQP</fullName>
            </value>
            <value>
                <fullName>TMCU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Type_For__c.field-meta.xml
<CustomField>
    <fullName>VOI_Type_For__c</fullName>
    <label>VOI type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FULL</fullName>
                <default>true</default>
                <label>FULL</label>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>E-SIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailyVariationRemainderTest.cls
@isTest
public class DailyVariationRemainderTest {
    @testsetup
    static void setUpData(){
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recordTypeRefId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        
        Account testAcc = new Account();
        testAcc.RecordTypeId  = recordTypeRefId;
        testAcc.Name = 'TestRef Account';
        insert testAcc;
        
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'Test';
        testAcc1.LastName = 'Opportunity 1';
        testAcc1.Phone = '1234567890';
        testAcc1.PersonEmail = 'opp1@test.com';
        
        Account testAcc2 = new Account();
        testAcc2.RecordTypeId  = recordTypePId;
        testAcc2.FirstName = 'Test2';
        testAcc2.LastName = 'Opportunity 2';
        testAcc2.Phone = '1234567870';
        testAcc2.PersonEmail = 'opp1@test1.com';
        
        insert testAcc1;
        insert testAcc2;
        
        Contact testCon = new Contact();
        testCon.FirstName = 'TestRef';
        testCon.LastName = 'Contact';
        testCon.AccountId = testAcc.Id;
        testCon.Admin__c = true;
        testCon.Portal_View__c = 'Admin View';
        testCon.Phone ='0412568868';
        testCon.Email ='rakesh@gmail.com';
        insert testCon;
        
        Opportunity testOpp1 = new Opportunity();
        testOpp1.Name = 'Test Opportunity 1';
        testOpp1.FinServ__ReferredByContact__c = testCon.Id;
        testOpp1.Referred_by_Company__c =testAcc.id;
        testOpp1.Contact_1__c = testCon.id;
        testOpp1.StageName ='Approved';
        testOpp1.CloseDate = System.Today();
        testOpp1.Applicant_1__c = testAcc1.Id;
        testOpp1.Applicant_2__c = testAcc2.id;
        insert testOpp1;
        
        Opportunity testOpp2 = new Opportunity();
        testOpp2.Name = 'Test Opportunity 2';
        testOpp2.FinServ__ReferredByContact__c = testCon.Id;
        testOpp2.Referred_by_Company__c =testAcc.id;
        testOpp2.Contact_1__c = testCon.id;
        testOpp2.StageName ='Approved';
        testOpp2.CloseDate = System.Today();
        testOpp2.Applicant_1__c = testAcc1.Id;
        testOpp2.Applicant_2__c = testAcc2.id;
        insert testOpp2;
        
        Opportunity opp = [select id,name,Applicant_1__c,Applicant_2__c,Applicant_1__r.name,Applicant_2__r.name,Applicant_1__r.personcontactId,Applicant_2__r.personcontactId from Opportunity where Name = 'Test Opportunity 1' LIMIT 1];
        list<VOI_Status__c> voiList = new list<VOI_Status__c>();
        VOI_Status__c obj = new VOI_Status__c();
        obj.Opportunity__c = opp.id;
        obj.Contact__c = opp.Applicant_1__r.personContactID;
        obj.Case_Status__c = 'Sent';
        obj.VOI_Type_For__c = 'E-SIGN';
        obj.Current_VOI_section__c = 'CQP';
        voiList.add(obj);
        
        VOI_Status__c obj2 = new VOI_Status__c();
        obj2.Opportunity__c = opp.id;
        obj2.Contact__c = opp.Applicant_2__r.personContactID;
        obj2.Case_Status__c = 'Sent';
        obj2.VOI_Type_For__c = 'E-SIGN';
        obj2.Current_VOI_section__c = 'CQP';
        //voiList.add(obj2);
        
        insert voiList;
        
        list<Funding_Request__c> frlist = new list<Funding_Request__c>();
        Funding_Request__c fr = new Funding_Request__c();
        fr.Request_Type__c = 'Variation';
        fr.Request_Status__c = 'Variation requested by customer';
        fr.Opportunity__c = opp.Id;
        fr.Applicant_1_A1__c = opp.Applicant_1__c;
        fr.Applicant_2_A2__c = opp.Applicant_2__c;
        fr.Requested_by__c = 'Customer';
        fr.Person_Requesting__c = opp.Applicant_1__r.personcontactId;
        fr.Variation_Requested_By__c = opp.Applicant_1__c;
        fr.Customer_Authorisation_Type__c = 'Either to sign';
        fr.Customer_Authorisation_Status__c = 'Pending Applicant 1';
        fr.Date_Last_Request_Status_Changes__c = system.now().addDays(-5);
        frlist.add(fr);
        
        Funding_Request__c fr3 = new Funding_Request__c();
        fr3.Request_Type__c = 'Variation';
        fr3.Request_Status__c = 'Variation requested by customer';
        fr3.Opportunity__c = opp.Id;
        fr3.Applicant_1_A1__c = opp.Applicant_1__c;
        fr3.Applicant_2_A2__c = opp.Applicant_2__c;
        fr3.Requested_by__c = 'Customer';
        fr3.Person_Requesting__c = opp.Applicant_1__r.personcontactId;
        fr3.Variation_Requested_By__c = opp.Applicant_1__c;
        fr3.Customer_Authorisation_Type__c = 'Either to sign';
        fr3.Customer_Authorisation_Status__c = 'Pending Applicant 1';
        fr3.Date_Last_Request_Status_Changes__c = system.now().addDays(-5);
        frlist.add(fr3);
        
        system.debug('personCOnID'+fr.Person_Requesting__c);
        
        Funding_Request__c fr2 = new Funding_Request__c();
        fr2.Request_Type__c = 'Payment in full before installation';
        fr2.Request_Status__c = 'Payment requested by supplier';
        fr2.Opportunity__c = opp.Id;
        fr2.Applicant_1_A1__c = opp.Applicant_1__c;
        fr2.Applicant_2_A2__c = opp.Applicant_2__c;
        fr2.Requested_by__c = 'Supplier';
        fr2.Person_Requesting__c = opp.Applicant_2__r.personcontactId;
        fr2.Customer_Authorisation_Type__c = 'Both to sign';
        fr2.Customer_Authorisation_Status__c = 'Pending Applicant 1';
        fr2.Date_Last_Request_Status_Changes__c = system.now().addDays(-5);
        frlist.add(fr2);
 
        insert frlist;
        
    }
    
    static testMethod void test1(){
        Opportunity opp = [select id,name,Applicant_1__c,Applicant_2__c,Applicant_1__r.name,Applicant_2__r.name,Applicant_1__r.personcontactId,Applicant_2__r.personcontactId from Opportunity where Name = 'Test Opportunity 1' LIMIT 1];
        list<Funding_Request__c> frlist = [select id,Date_Last_Request_Status_Changes__c,Request_Type__c from Funding_Request__c where opportunity__c =:opp.id];
        integer count =-8;
        Boolean ispass = false;
        for(Funding_Request__c fr : frlist){
            if(fr.Request_Type__c == 'Variation'){
                fr.Date_Last_Request_Status_Changes__c = system.now().addDays(count);
            }
            else{
                fr.Date_Last_Request_Status_Changes__c = system.now().addDays(count);
            }
            count = count+1;
        }
        update frlist;
        
        
        Datetime scheduledTime = Datetime.now().addMinutes(1);
        String cronExpression = '' + scheduledTime.second() + ' ' + scheduledTime.minute() + ' ' +scheduledTime.hour() + ' ' + scheduledTime.day() + ' ' + scheduledTime.month() +' ? ' + scheduledTime.year();
        Test.startTest();
        String jobId = System.schedule('Test Job', cronExpression, new DailyVariationReminder()); 
        Test.stopTest();
    }
}