force-app/main/default/objects/Account/fields/ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>ContactContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Pending_Notes__c.field-meta.xml
<CustomField>
    <fullName>Application_Pending_Notes__c</fullName>
    <label>Application Pending Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Pending_Status__c</fullName>
    <label>Application Pending Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No action required</fullName>
            </value>
            <value>
                <fullName>Customer Action</fullName>
            </value>
            <value>
                <fullName>Adviser Action</fullName>
            </value>
            <value>
                <fullName>Lender Action</fullName>
            </value>
            <value>
                <fullName>Admin Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Escalation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (External Referrer)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Time_at_current_stage__c.field-meta.xml
<CustomField>
    <fullName>Time_at_current_stage__c</fullName>
    <formula>VALUE(TEXT(
    IF(MOD((NOW() - Last_Stage_Change_Date__c)*24,24)&lt;9,
        CEILING(( NOW()  - Last_Stage_Change_Date__c))-1,
        CEILING((NOW()  - Last_Stage_Change_Date__c))
    )
    +
    MOD(
        ROUND(
            9 * (
                ( 5 *
                    FLOOR(
                        ( DATEVALUE(NOW()) - DATE( 1900, 1, 8) ) / 7) +
                        MIN(5, MOD( DATEVALUE(NOW()) - DATE( 1900, 1, 8), 7) +
                        MIN( 1, 24 / 9 * ( MOD(NOW() - DATETIMEVALUE( &apos;1900-01-08 22:00:00&apos; ), 1 ) ) )
                    )
                )-( 5 *
                     FLOOR(
                         ( DATEVALUE(Last_Stage_Change_Date__c  ) - DATE( 1900, 1, 8) ) / 7) +
                        MIN( 5, MOD( DATEVALUE(Last_Stage_Change_Date__c ) - DATE( 1996, 1, 1), 7 ) +
                        MIN( 1, 24 / 9 * ( MOD(Last_Stage_Change_Date__c - DATETIMEVALUE( &apos;1900-01-08 22:00:00&apos; ), 1) ) )
                    )
                )
            ),
        0), 9
    )/10
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time at current stage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReferrersReportController.cls
public class ReferrersReportController {
	public static final string ConId = ApexPages.currentPage().getParameters().get('ConId');
    public Map<id, List<Opportunity>> refMap {get;set;}
    public Integer sizelist{get;set;}
    public List<opportunity> opList{get;set;}
    public string now{get;Set;}
    public Account Acc{get; set;}
    public contact con{get; set;}
    public String xlsHeader {
        get {
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
    public ReferrersReportController(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = opportunity.stageName.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     

        con = [Select Id, AccountId, name From Contact WHERE id =: ConId LIMIT 1];
        for(Account Ac : [Select Id, name from Account WHERE ID =: con.AccountId Limit 1]){
            Acc = Ac;
        }
        opList = new List<opportunity>();
        refMap = new Map<id, List<Opportunity>>();
        for(Opportunity op : [Select Id,Loan_Amount__c,Lender__c,Escalation__c,LastModifiedDate,Application_Pending_Notes__c,Application_Pending_Status__c, Name,Time_at_current_stage__c, StageName,CreatedDate,LastActivityDate,ReferredByContact__c,ReferredByContact__r.name from opportunity WHERE ReferredByContact__c =: con.Id order By stageName,Time_at_current_stage__c  Asc]){
            if(((op.stageName == 'Working' || op.stageName == 'Nurturing') && op.Time_at_current_stage__c <= 7) 
               || (op.StageName == 'Closed Lost' && op.Time_at_current_stage__c <= 7)
               || ((op.StageName != 'Settled (closed won)' && op.stageName != 'Working' && op.stageName != 'Nurturing' && op.StageName != 'Closed Lost') && op.Time_at_current_stage__c <= 120)
               || (op.StageName == 'Settled (closed won)') 
              ){
                  opList.add(op);
                  if(!refMap.containsKey(op.ReferredByContact__c)){
                      refMap.put(op.ReferredByContact__c, new List<Opportunity>{op});  
                      System.debug('infii89i89989f');
                  }
                  else{
                      refMap.get(op.ReferredByContact__c).add(op);
                      System.debug('infif'+refMap.get(op.ReferredByContact__c));
                  }
              }
        }
        
        sizelist = (opList != null && opList.size() > 0 ? opList.size() : 0);
        
        DateTime todayTImm = System.now();
        now = monthCOnvert(todayTImm)[1];
    }
    
    public List<string> monthCOnvert(dateTime dat){
        
        List<string> datetimeconverted = new List<string>();
        List<string> data = string.valueOf(dat).split(' ');
        dateTime tim =  dat;
        string team = tim.format('h:mm a');
        
        datetimeconverted.add(team);
        
        integer nm = dat.month();
        
        string mnth = '';
        if(nm == 1){
            mnth = 'Jan';
        }
        else if(nm == 2){
            mnth = 'Feb';
        }
        else if(nm == 3){
            mnth = 'Mar';
        }
        else if(nm == 4){
            mnth = 'Apr';
        }
        else if(nm == 5){
            mnth = 'May'; 
        }
        else if(nm == 6){
            mnth = 'Jun';
        }
        else if(nm == 7){
            mnth = 'Jul';
        }
        else if(nm == 8){
            mnth = 'Aug';
        }
        else if(nm == 9){
            mnth = 'Sep';
        }
        else if(nm == 10){
            mnth = 'Oct';
        }
        else if(nm == 11){
            mnth = 'Nov';
        }
        else if(nm == 12){
            mnth = 'Dec'; 
        }
        else{
            mnth = '';
        }
        
        string st = dat.day() + ' ' + mnth + ' ' + dat.year();
        
        datetimeconverted.add(st);
        return datetimeconverted;
    }
    
}