force-app/main/default/objects/Account/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Referred by Company)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/Funding_Request__c.object-meta.xml
<CustomObject>
    <label>Funding Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Funding Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/A1_Payment_Authorisation_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>A1_Payment_Authorisation_Submitted_Date__c</fullName>
    <label>A1 Payment Authorisation Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/A2_Payment_Authorisation_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>A2_Payment_Authorisation_Submitted_Date__c</fullName>
    <label>A2 Payment Authorisation Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_1_A1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_A1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 1 (A1)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Applicant_2_A2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_A2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2 (A2)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Requests (Applicant 2 (A2))</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 1)</relationshipLabel>
    <relationshipName>Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Funding Requests (Contact 2)</relationshipLabel>
    <relationshipName>Funding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Status__c</fullName>
    <label>Customer Authorisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request sent to customer(s)</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 2</fullName>
            </value>
            <value>
                <fullName>Pending Applicant 1</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Customer_Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorisation_Type__c</fullName>
    <label>Customer Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Either to sign</fullName>
            </value>
            <value>
                <fullName>Both to sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Date_Last_Request_Status_Changes__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Request_Status_Changes__c</fullName>
    <label>Date Last Request Status Changes</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Disbursement_amount__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_amount__c</fullName>
    <formula>IF(ISPICKVAL(Request_Type__c , &apos;Part payment before installation&apos;),  Request_Amount__c ,  IF(Request_Amount__c  &lt;  Net_Funds_Available__c , Request_Amount__c , Net_Funds_Available__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Disbursement amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Funded_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Funded_To_Date__c</fullName>
    <label>Funded to Date (not including this req)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Funding_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Funding_On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <inlineHelpText>Invoice Amount (Amount to be funded from the loan)</inlineHelpText>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Net_Funds_Available__c.field-meta.xml
<CustomField>
    <fullName>Net_Funds_Available__c</fullName>
    <formula>IF( ISPICKVAL( Request_Type__c , &apos;Variation&apos;) ,  Opportunity__r.Previous_Loan_Amount_After_Variation__c - Funded_To_Date__c, Opportunity__r.SyncedQuote.Customer_Amount__c - Funded_To_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Funds Available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Net_Surplus_Shortfall__c.field-meta.xml
<CustomField>
    <fullName>Net_Surplus_Shortfall__c</fullName>
    <label>Net Surplus / Shortfall</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Person_Requesting__c.field-meta.xml
<CustomField>
    <fullName>Person_Requesting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Requesting</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Fundings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Amount__c.field-meta.xml
<CustomField>
    <fullName>Request_Amount__c</fullName>
    <label>Request Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment requested by supplier</fullName>
            </value>
            <value>
                <fullName>Payment requested by supplier (pending contract)</fullName>
            </value>
            <value>
                <fullName>Variation requested by customer</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer (pending contract)</fullName>
            </value>
            <value>
                <fullName>Payment authorised by customer</fullName>
            </value>
            <value>
                <fullName>Funding handover call completed</fullName>
            </value>
            <value>
                <fullName>Payment funded</fullName>
            </value>
            <value>
                <fullName>Payment requested by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment in full before installation</fullName>
            </value>
            <value>
                <fullName>Payment in full after installation</fullName>
            </value>
            <value>
                <fullName>Part payment before installation</fullName>
            </value>
            <value>
                <fullName>Remainder of payment after installation</fullName>
            </value>
            <value>
                <fullName>Variation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <label>Requested by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funding_Request__c/fields/Total_Funds_Approved_Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Funds_Approved_Customer_Amount__c</fullName>
    <formula>IF( ISPICKVAL( Request_Type__c , &apos;Variation&apos;) ,  Opportunity__r.Previous_Loan_Amount_After_Variation__c , Opportunity__r.SyncedQuote.Customer_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Funds Approved (Customer Amount)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_by_Company__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred by Company)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AuthorisationCertificateController.cls
public without sharing class AuthorisationCertificateController {
    public Funding_Request__c frRec{get; set;}
    public string oppName{get; set;}
    public string auhtoDate{get; set;}
    public string authoName{get; set;}
    public boolean isTwoPerson{get; set;}
    
     /*public Boolean init{
        get{
            init();            
            return false;
        }
    } */

    public AuthorisationCertificateController(){
        ID fundId = ApexPages.currentPage().getParameters().get('id');
        system.debug('FUNDIUNID'+fundId);
        frRec = [select Id,Opportunity__r.Applicant_1__c,Opportunity__r.SyncedQuote.Product__r.Funding_Authorisation_Type__c, Requested_by__c,Request_Type__c,Opportunity__c,Total_Funds_Approved_Customer_Amount__c,Invoice_Amount__c,Disbursement_amount__c,Net_Funds_Available__c,Funded_To_Date__c,Net_Surplus_Shortfall__c,
                                          Opportunity__r.Referred_by_Company__c,Applicant_2_A2__c,Applicant_2_A2__r.PersonEmail,Applicant_1_A1__c,Applicant_1_A1__r.PersonEmail,Opportunity__r.Name,Opportunity__r.Referred_by_Company__r.Name,Applicant_1_A1__r.Phone,Applicant_2_A2__r.Phone,Request_Amount__c,Request_Date__c,Opportunity__r.Lender__c,
                                          Customer_Authorisation_Type__c,Date_Last_Request_Status_Changes__c,Customer_Authorisation_Status__c,Applicant_1_A1__r.PersonContactId,Applicant_2_A2__r.PersonContactId,Person_Requesting__r.Name,Opportunity__r.Purpose__c,Applicant_1_A1__r.Name,Applicant_2_A2__r.Name,Installation_Date__c,
                                          A1_Payment_Authorisation_Submitted_Date__c,A2_Payment_Authorisation_Submitted_Date__c,Opportunity__r.SyncedQuote.Brokerage_Amount__c,
                                          Funding_On_Hold__c,Person_Requesting__c,Person_Requesting__r.email,Person_Requesting__r.id,Opportunity__r.Contact_1__c,Opportunity__r.Contact_2__c,Request_Status__c,Opportunity__r.FinServ__ReferredByContact__c,Opportunity__r.FinServ__ReferredByContact__r.Email from Funding_Request__c where id=: fundId LIMIT 1];
        if(frRec.Opportunity__c != null){
        	String nme = frRec.Opportunity__r.Name; 
        	string[] ch = nme.split(',');
        	oppName = ch[0];    
        }
        Datetime now = System.now();
        auhtoDate = now.format('dd/MM/yyyy hh:mm a');
        authoName = frRec.Applicant_1_A1__r.name;
        if(frRec.Applicant_2_A2__c != null){
            authoName = authoName+','+' '+frRec.Applicant_2_A2__r.name;
            isTwoPerson = true;
        }
        
    }
}