force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( isAlready_provided__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/green.png&quot;, &quot;Already Provided&quot;, 20, 20)&amp; &quot; Already Provided&quot;,
IF( isApplicable__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/yellow.png&quot;, &quot;Not Applicable&quot;, 20, 20) &amp; &quot; Not Applicable&quot;,
IF( isComplete__c == true,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/darkgreen.png&quot;, &quot;Submitted&quot;, 20, 20) &amp; &quot; Submitted&quot;,
IMAGE(&quot;/resource/DocumentRequestedIcons/docsReq/red.png&quot;, &quot;Requested&quot;, 20, 20) &amp; &quot; Requested&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_Credit_Score__c</fullName>
    <label>Applicant 1 Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Response__c.field-meta.xml
<CustomField>
    <fullName>Customer_Response__c</fullName>
    <label>Customer Response-Disclosure Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funding_Variation_Request__c.field-meta.xml
<CustomField>
    <fullName>Funding_Variation_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding Variation Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_Chart_JSON__c.field-meta.xml
<CustomField>
    <fullName>Line_Chart_JSON__c</fullName>
    <label>Line Chart JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Repayments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Repayments__c</fullName>
    <label>Monthly Repayments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purchase_Price_Funds_Needed__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price_Funds_Needed__c</fullName>
    <label>Purchase Price / Funds Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( AND( OR( ISPICKVAL( StageName , &apos;Quote&apos;) , ISPICKVAL( StageName , &apos;CPA Started&apos;))  , OR( ISPICKVAL( Current_Application_Sections__c ,&apos;Priorities&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Loan Recommendation&apos;), ISPICKVAL( Current_Application_Sections__c  ,&apos;Getting Started&apos;) ) )  ,&apos;Quote-#fd636b&apos;,
 
IF(ISPICKVAL( StageName , &apos;CPA Started&apos;),&apos;Applying-#ffb902&apos;,
    
IF( AND( OR( ISPICKVAL(StageName,  &apos;Packs Out&apos;),ISPICKVAL( StageName, &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;CPA Done&apos;)), NOT(Funding_Variation_Request__c)), &apos;Verifying-#FFDF8F&apos;,

IF( AND( OR( ISPICKVAL(StageName, &apos;Application&apos;) ,ISPICKVAL(StageName, &apos;Conditional&apos;)), NOT(Funding_Variation_Request__c)), &apos;Credit-#b4f6e0&apos;, 

IF(  AND(ISPICKVAL(StageName, &apos;Approved&apos;), TODAY()- DATEVALUE( Approved_Date__c )&lt; 90 )   , &apos;Approved-#3be8b0&apos;,
IF(  OR(AND (ISPICKVAL(StageName, &apos;Funding&apos;), (TODAY()- DATEVALUE( Approved_Date__c )&lt; 90)),(AND (OR(ISPICKVAL(StageName,  &apos;CPA Done&apos;),ISPICKVAL( StageName, &apos;Packs Out&apos;),ISPICKVAL( StageName , &apos;Packs Back&apos;),ISPICKVAL( StageName , &apos;Application&apos;),
ISPICKVAL( StageName , &apos;Conditional&apos;)) ,Funding_Variation_Request__c ))), &apos;Funding-#d063d3&apos;,
IF( ISPICKVAL(StageName, &apos;Settled (closed won)&apos;) , &apos;Funded-#4a154b&apos;,
IF( AND( OR(ISPICKVAL(StageName, &apos;Approved&apos;),ISPICKVAL(StageName, &apos;Funding&apos;)) ,TODAY()- DATEVALUE( Approved_Date__c )&gt; 90) , &apos;Expired-#FFFF00&apos;, 
IF( OR( ISPICKVAL(StageName, &apos;Closed Lost&apos;) ,ISPICKVAL(StageName, &apos;Nurturing&apos;),ISPICKVAL(StageName, &apos;Working&apos;)) , &apos;Closed-#f2f2f2&apos;, &apos;&apos;) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Monthly_Repayments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Repayments__c</fullName>
    <formula>((((Interest_Rate__c/12) * Total_loan_amount__c) * ((1 + (Interest_Rate__c/12))^Loan_Term__c)) / ((1 + (Interest_Rate__c/12))^Loan_Term__c - 1))+ Monthly_Account_Keeping_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Repayments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/Time_Line_Conditions__c.object-meta.xml
<CustomObject>
    <label>Time Line Conditions</label>
    <nameField>
        <label>Time Line Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Line Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Condition_1__c.field-meta.xml
<CustomField>
    <fullName>Condition_1__c</fullName>
    <label>Condition 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Condition_2__c.field-meta.xml
<CustomField>
    <fullName>Condition_2__c</fullName>
    <label>Condition 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Condition_3__c.field-meta.xml
<CustomField>
    <fullName>Condition_3__c</fullName>
    <label>Condition 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Condition_match__c.field-meta.xml
<CustomField>
    <fullName>Condition_match__c</fullName>
    <label>Condition match</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Done_Title__c.field-meta.xml
<CustomField>
    <fullName>Done_Title__c</fullName>
    <label>Done Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/is_Major__c.field-meta.xml
<CustomField>
    <fullName>is_Major__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Major</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/number_of_condition__c.field-meta.xml
<CustomField>
    <fullName>number_of_condition__c</fullName>
    <formula>IF(ISBLANK( Condition_1__c ),0,1) 
+ IF(ISBLANK( Condition_2__c ),0,1)
+ IF(ISBLANK( Condition_3__c ),0,1)
+ IF(ISBLANK( Condition_4__c ),0,1)
+ IF(ISBLANK( Condition_5__c ),0,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>number of condition</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Operator_1__c.field-meta.xml
<CustomField>
    <fullName>Operator_1__c</fullName>
    <label>Operator 1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Operator_2__c.field-meta.xml
<CustomField>
    <fullName>Operator_2__c</fullName>
    <label>Operator 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Operator_3__c.field-meta.xml
<CustomField>
    <fullName>Operator_3__c</fullName>
    <label>Operator 3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Required Now</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Todo_s_For__c.field-meta.xml
<CustomField>
    <fullName>Todo_s_For__c</fullName>
    <label>Todo&apos;s For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>ParkerLane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Value_1__c.field-meta.xml
<CustomField>
    <fullName>Value_1__c</fullName>
    <label>Value 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Value_2__c.field-meta.xml
<CustomField>
    <fullName>Value_2__c</fullName>
    <label>Value 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time_Line_Conditions__c/fields/Value_3__c.field-meta.xml
<CustomField>
    <fullName>Value_3__c</fullName>
    <label>Value 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Linechartcont.cls
public without sharing class Linechartcont {
	/*
		before made changes in Time_Line_Conditions__c records please check the ORDER__C number here also!!!
	
	*/
    @AuraEnabled
    public static List<activityWrapper> fillActivity(id Recid){
        List<activityWrapper> ActList = new List<activityWrapper>();
        List<Time_Line_Conditions__c> tlcList = [Select id, name,Todo_s_For__c,order__c,number_of_condition__c, is_Major__c,Icon_Name__c,Done_Title__c,Status__c,Condition_match__c, Condition_1__c,Operator_1__c,Value_1__c,Condition_2__c,Operator_2__c,Value_2__c,Condition_3__c,Operator_3__c,Value_3__c from Time_Line_Conditions__c order by Order__c, Status__c, Todo_s_For__c];
        opportunity op = [select id,Approved_Date__c, applicant_1__r.name,applicant_2__r.name,Funding_Variation_Request__c, Customer_Response__c,Line_Chart_JSON__c,Applicant_1_Credit_Score__c,Purchase_Price_Funds_Needed__c,Monthly_Repayments__c,Lender__c,Applicant_1__c,Applicant_2__c,Applicant_1__r.personContactId,Applicant_2__r.personContactId, name,Current_Application_Sections__c,Send_the_quote_to__c, stageName from opportunity where id = : Recid];
        string oldOPVal = op.Line_Chart_JSON__c;
        boolean appOnevar = false;
        boolean appTwovar = false;
        VOI_Status__c singleVOI = new VOI_Status__c();    
        List<Funding_Request__c> FundingList = new List<Funding_Request__c>();
        List<VOI_Status__c> voiSList = new List<VOI_Status__c>();
        Map<id, List<VOI_Status__c>> VOIMAP = new Map<id, List<VOI_Status__c>>();
        for(VOI_Status__c vs : [select id, name, Contact__c,Contact__r.name,Case_Status__c, Opportunity__c, VOI_Type_For__c from VOI_Status__c where Opportunity__r.id =: op.Id AND Case_Status__c != 'Rejected' order by createddate ASC]){
            voiSList.add(vs);
            
            if(!VOIMAP.containsKey(vs.Contact__c)){
                VOIMAP.put(vs.Contact__c, new List<VOI_Status__c>{vs});
            }
            else{
                VOIMAP.get(vs.Contact__c).add(vs);
            }            
        }
        for(Funding_Request__c fc : [Select id,Applicant_1_A1__c,Applicant_2_A2__c,Applicant_1_A1__r.FirstName,Applicant_2_A2__r.FirstName,Person_Requesting__r.Name,Person_Requesting__c,Request_Status__c,CreatedDate,Customer_Authorisation_Type__c,Customer_Authorisation_Status__c, name from Funding_Request__c where Opportunity__c =: op.id Order by CreatedDate DESC]){
            FundingList.add(fc);
        }
     
        Set<id> conDocId = new Set<id>();
        for(ContentDocumentLink cdl :[select Id, LinkedEntityId, ContentDocumentId, ShareType, Visibility from ContentDocumentLink where LinkedEntityId =: Recid]){
            conDocId.add(cdl.ContentDocumentId);
        }
        
        List<ContentVersion> cvList = new List<ContentVersion>();
        for(ContentVersion cv : [SELECT Id, ContentDocumentId,Current_in_use__c, Category__c, Related__c FROM ContentVersion WHERE ContentDocumentId IN: conDocId]){
            cvList.add(cv); 
        }
        
        
        
        List<Document_Requested__c> drList = new List<Document_Requested__c>();
        List<Document_Requested__c> FullDoc = new List<Document_Requested__c>();
        List<Document_Requested__c> drListForBankStmnt = new List<Document_Requested__c>();
        for(Document_Requested__c dc : [SELECT Id,Name,Document__c,CreatedDate,isComplete__c, Details__c,Related_To__c,Status__c,Category__c FROM Document_Requested__c WHERE Opportunity__c =: op.Id AND Document__c != '' order by CreatedDate ASC]){
            FullDoc.add(dc);
            if(!dc.isComplete__c){
                drList.add(dc);
            }  
            			
            if(dc.Category__c == 'Bank Statements' || dc.Document__c.equalsIgnoreCase('Bank Statement')){
                drListForBankStmnt.add(dc);
            }

            
        } 
        integer size = 0;
        for(Time_Line_Conditions__c tc : tlcList){
            boolean bankStmnt = false;
            boolean condition = false;
            
            if(!String.isBlank(tc.Operator_1__c)){
                if(tc.Operator_1__c.contains('>')){
                    condition = true;
                    size = (drList != null ? drList.size() : 0);
                }
            } 
            
            if(tc.Order__c == 21 && FundingList != null && FundingList.size() > 0){
                for(Funding_Request__c fr : FundingList){
                    if(fr.Person_Requesting__c != null){
                        activityWrapper obj = new activityWrapper();
                        obj.doneText = tc.Done_Title__c +' ('+fr.Person_Requesting__r.Name+')';
                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                        obj.iconName = tc.Icon_Name__c;
                        obj.isMajor = tc.is_Major__c;
                        if(fr.Person_Requesting__c == fr.Applicant_1_A1__c || fr.Person_Requesting__c == fr.Applicant_2_A2__c ){
                            obj.toDoFor = 'Customer';
                        }
                        else{
                            obj.toDoFor = 'Referrer';  
                        }
                        ActList.add(obj);
                        break;
                    }
                }
            }
            if(tc.Order__c == 22 && FundingList != null && FundingList.size() > 0){
                for(Funding_Request__c fr : FundingList){
                    if(fr.Customer_Authorisation_Status__c != null && fr.Customer_Authorisation_Status__c != 'Request sent to customer(s)'){
                        if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 1'){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c +' ('+fr.Applicant_2_A2__r.FirstName+')';
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                            break;
                        }
                        else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 2'){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c +' ('+fr.Applicant_1_A1__r.FirstName+')';
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                            break;
                        }
                        else if(fr.Customer_Authorisation_Status__c == 'Authorised'){
                            if(fr.Applicant_2_A2__c != null){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c +' ('+fr.Applicant_1_A1__r.FirstName+')';
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                                
                                activityWrapper obj1 = new activityWrapper();
                                obj1.doneText = tc.Done_Title__c +' ('+fr.Applicant_2_A2__r.FirstName+')';
                                obj1.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj1.iconName = tc.Icon_Name__c;
                                obj1.isMajor = tc.is_Major__c;
                                obj1.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj1);
                                break;
                            }
                            if(fr.Applicant_2_A2__c == null){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c +' ('+fr.Applicant_1_A1__r.FirstName+')';
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                                break;
                            }
                        }
                    }
                }
            }
            
            if(tc.Order__c != 35 && tc.Order__c == 34 && !FundingList.isEmpty() && FundingList != null){
                for(Funding_Request__c fr : FundingList){
                    if((fr.Request_Status__c != 'Variation requested by customer') && (fr.Request_Status__c == 'Payment requested by supplier' || fr.Request_Status__c == 'Payment requested by customer')){
                        if(op.Applicant_2__c == null && fr.Customer_Authorisation_Status__c == 'Request sent to customer(s)'){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c +' ('+op.Applicant_1__r.Name+')';
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                            break;
                        } 
                        else if(op.Applicant_2__c != null){
                            if(fr.Customer_Authorisation_Status__c == 'Request sent to customer(s)' && fr.Customer_Authorisation_Type__c == 'Both to sign'){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c +' ('+ op.Applicant_1__r.Name+')';
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                                
                                activityWrapper obj1 = new activityWrapper();
                                obj1.doneText = tc.Done_Title__c +' ('+ op.Applicant_2__r.Name +')';
                                obj1.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj1.iconName = tc.Icon_Name__c;
                                obj1.isMajor = tc.is_Major__c;
                                obj1.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj1);
                                break;  
                            }
                            else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 1' && fr.Customer_Authorisation_Type__c == 'Both to sign'){
                                activityWrapper obj1 = new activityWrapper();
                                obj1.doneText = tc.Done_Title__c +' ('+ op.Applicant_1__r.Name +')';
                                obj1.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj1.iconName = tc.Icon_Name__c;
                                obj1.isMajor = tc.is_Major__c;
                                obj1.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj1);
                                break;  
                            }
                            else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 2' && fr.Customer_Authorisation_Type__c == 'Both to sign'){
                                activityWrapper obj1 = new activityWrapper();
                                obj1.doneText = tc.Done_Title__c +' ('+ op.Applicant_2__r.Name + ')';
                                obj1.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj1.iconName = tc.Icon_Name__c;
                                obj1.isMajor = tc.is_Major__c;
                                obj1.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj1);
                                break;  
                            }
                            else if(fr.Customer_Authorisation_Status__c == 'Pending Applicant 1' && fr.Customer_Authorisation_Type__c == 'Either to sign'){
                                activityWrapper obj1 = new activityWrapper();
                                obj1.doneText = tc.Done_Title__c +' (' + op.Applicant_1__r.Name +')';
                                obj1.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj1.iconName = tc.Icon_Name__c;
                                obj1.isMajor = tc.is_Major__c;
                                obj1.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj1);
                                break;  
                            }
                        }
                    }
                }                
            }
            if(tc.Order__c == 35 && op.Funding_Variation_Request__c == true){
                activityWrapper obj = new activityWrapper();
                obj.doneText = tc.Done_Title__c;
                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                obj.iconName = tc.Icon_Name__c;
                obj.isMajor = tc.is_Major__c;
                obj.toDoFor = tc.Todo_s_For__c;
                ActList.add(obj);
            }
            if(tc.number_of_condition__c == 1){       
                boolean isDocExis = false;
                boolean isFundAuth = false; 
                boolean isFundPending = false; 
                boolean isFund = false; 
                for(Funding_Request__c fc : FundingList){
                    if(op.stageName == 'Funding' && (fc.Request_Status__c == 'Payment requested by customer (pending contract)' || fc.Request_Status__c == 'Payment requested by supplier (pending contract)') ){
                        isFundPending = true;
                        break;
                    }
                }
                for(Funding_Request__c fc : FundingList){
                    if(fc.Request_Status__c == 'Payment authorised by customer'){
                        isFundAuth = true;
                        break;
                    }
                }
                for(Funding_Request__c fc : FundingList){
                    if(fc.Request_Status__c != 'Payment funded' && fc.Request_Status__c != 'Payment authorised by customer'){
                        isFund = true;
                        break;
                    }
                }
                for(ContentVersion cv : cvList){
                    if(cv.Category__c == 'Lender Credit Contract' && cv.Current_in_use__c){
                 		isDocExis = true;
                        break;
                    }
                }
               if(tc.Order__c == 6 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && (FundingList.size() == 0)){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
                if(tc.Order__c == 7 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && (isDocExis)){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
                if(tc.Order__c != 44 && tc.Order__c != 7 && tc.Order__c != 6 && tc.Order__c != 43 && tc.Order__c != 37 && tc.Order__c != 33 && tc.Order__c != 32 && tc.name != 'Approval expires in 10 days' && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c))){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
                
                if(tc.Order__c != 37 && tc.Order__c != 33 && tc.Order__c != 32 && tc.name == 'Approval expires in 10 days' && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c))){
                    if(op.Approved_Date__c != null && (op.Approved_Date__c.date()).daysbetween(system.today()) > 79 && (op.Approved_Date__c.date()).daysbetween(system.today()) < 91){
                        activityWrapper obj = new activityWrapper();
                        obj.doneText = tc.Done_Title__c;
                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                        obj.iconName = tc.Icon_Name__c;
                        obj.isMajor = tc.is_Major__c;
                        obj.toDoFor = tc.Todo_s_For__c;
                        ActList.add(obj);   
                    }                    
                }
                if(tc.Order__c == 32 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && (FundingList.size() == 0)){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }                  
                if(tc.Order__c == 33 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && (!isDocExis)){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
                if(tc.Order__c == 37 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && isFundAuth){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c;
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                } 
                if(tc.Order__c == 43 && (tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) || (isFundPending)) ){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c; 
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
                if(tc.Order__c == 44 && tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && isFund ){
                    activityWrapper obj = new activityWrapper();
                    obj.doneText = tc.Done_Title__c; 
                    obj.status = (tc.Status__c != null ? tc.Status__c : '');
                    obj.iconName = tc.Icon_Name__c;
                    obj.isMajor = tc.is_Major__c;
                    obj.toDoFor = tc.Todo_s_For__c;
                    ActList.add(obj);
                }
            }
            if(tc.number_of_condition__c == 2){
                if(condition){                    
                    if(FullDoc != null && FullDoc.size() > 0 && size == 0 && tc.order__c == 17){
                        if(tc.Value_2__c.contains((string)op.get(tc.Condition_2__c))){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = 'Supporting information provided';
                            obj.status = 'Done';//(tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = 'SmallGreen';
                            obj.isMajor = false;
                            obj.toDoFor = 'Customer';
                            ActList.add(obj);  
                        }                         
                    } 
                    if(size != 0 && tc.order__c == 27){     
                        if(tc.Value_2__c.contains((string)op.get(tc.Condition_2__c))){           
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = 'Provide supporting information';
                            obj.status = 'Required Now';
                            obj.iconName = 'SmallToDo';
                            obj.isMajor = false;
                            obj.toDoFor = 'Customer';
                            ActList.add(obj);                           
                        }
                    }
                    condition = false;
                }    
                else if(tc.order__c == 18){
                    if(tc.Value_1__c.contains((string)op.get(tc.Condition_1__c))){
                        for(Document_Requested__c dc : drListForBankStmnt){
                            if(dc.isComplete__c && tc.Order__c == 18){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = 'Bank data provided';
                                obj.status = 'Done';
                                obj.iconName = 'SmallGreen';
                                obj.isMajor = false;
                                obj.toDoFor = 'Customer';
                                ActList.add(obj); 
                                if(!test.isRunningTest())
                                    break;
                            }                            
                        }                        
                    }
                }    
                else if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && tc.Condition_2__c.contains('Bank Statement Data document request')){
                    if(drListForBankStmnt != null && drListForBankStmnt.size() > 0){
                        if(drListForBankStmnt[0].status__c.contains(tc.Value_2__c)){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                        }
                    }
                }
                else if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && tc.Condition_2__c.contains('Document Requested with category "Purchase Quote or Invoice"')){
                    if(cvList != null && cvList.size() > 0){
                        for(ContentVersion dc : cvList){
                            if( (dc.Category__c == 'Purchase Invoice' ||  dc.Category__c == 'Loan Purpose') && tc.Value_2__c == 'Submitted'){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                                if(!test.isRunningTest())
                                	break;
                            }
                        }
                        for(Document_Requested__c dc : drList){
                            if((dc.Category__c == 'Purchase Invoice' ||  dc.Category__c == 'Loan Purpose') && tc.Value_2__c == 'Requested'){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                                if(!test.isRunningTest())
                                    break;
                            }
                        }
                    }                                        
                }
               /* else if(tc.Name == 'Request funding' || tc.Name == 'Issue Credit Contract' || tc.Name == 'Fund' ){                   
                    if(tc.Name == 'Request funding'){                        
                        if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c))){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                        }
                        else if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && op.get(tc.Condition_2__c) == null && tc.Operator_2__c == '!='){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                            
                        }
                        else if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && op.get(tc.Condition_2__c) != null && tc.Operator_2__c == '=='){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj); 
                        }
                    }
                    else if(tc.Name == 'Issue Credit Contract'){
                        if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && op.get(tc.Condition_2__c) == null && tc.Operator_2__c == '!='){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                        }
                        else if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && op.get(tc.Condition_2__c) != null && tc.Operator_2__c == '=='){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj); 
                        }
                    }
                    else if(tc.Name == 'Fund'){                        
                        if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c)) && op.get(tc.Condition_2__c) == null && tc.Operator_2__c == '!='){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                        } 
                    }     				
                    
                }*/
                else{ 
                    if((op.get(tc.Condition_1__c) == null ? false : tc.Value_1__c.contains((string)op.get(tc.Condition_1__c))) && (tc.Condition_2__c == null ? false : (tc.Condition_2__c == null ? false : (tc.name == 'Authorise payment' ? op.get(tc.Condition_2__c) == null : (op.get(tc.Condition_2__c) != null ? tc.Value_2__c.contains((string)op.get(tc.Condition_2__c)) : false))))){
                        activityWrapper obj = new activityWrapper();
                        obj.doneText = tc.Done_Title__c;
                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                        obj.iconName = tc.Icon_Name__c;
                        obj.isMajor = tc.is_Major__c;
                        obj.toDoFor = tc.Todo_s_For__c;
                        ActList.add(obj);
                    }
                 }
                
                
            }
            if(tc.number_of_condition__c == 3){
                if(condition){
                    if(size > 0 && tc.Value_2__c.contains((string)op.get(tc.Condition_2__c)) && tc.Value_3__c.contains((string)op.get(tc.Condition_3__c))){
                        activityWrapper obj = new activityWrapper();
                        obj.doneText = tc.Done_Title__c;
                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                        obj.iconName = tc.Icon_Name__c;
                        obj.isMajor = tc.is_Major__c;
                        obj.toDoFor = tc.Todo_s_For__c;
                        ActList.add(obj);
                    }
                }
                else if((tc.Name.contains('Verify Identity') || tc.Name.contains('Sign credit proposal'))){                   
                    if(VOIMAP != null && VOIMAP.size() > 0){
                        if(tc.Value_1__c.split(',').contains((string)op.get(tc.Condition_1__c))){                            
                            string typeOfOne = '';
                            boolean full = false;
                            boolean VOI = false;
                            boolean Esign = false;
                            if(VOIMAP.containsKey(op.Applicant_1__r.personContactid)){
                                for(VOI_Status__c vs : VOIMAP.get(op.Applicant_1__r.personContactid)){
                                    if(vs.VOI_Type_For__c == 'FULL'){
                                        if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                            full = true;
                                            if(!test.isRunningTest())
                                                break;
                                        }
                                    }    
                                    if(vs.VOI_Type_For__c == 'VOI'){
                                        if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                            VOI = true;
                                            if(!test.isRunningTest())
                                                break;
                                        }
                                    }
                                    if(vs.VOI_Type_For__c == 'E-SIGN'){
                                        if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                            Esign = true;
                                            if(!test.isRunningTest())
                                                break;
                                        }
                                    }
                                }
                            }
                            
                            if(VOIMAP.containsKey(op.Applicant_1__r.personContactid)){
                                for(VOI_Status__c vs : VOIMAP.get(op.Applicant_1__r.personContactid)){
                                    if(vs.VOI_Type_For__c == 'FULL'){
                                        if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                            typeOfOne = 'Full-not';
                                        }
                                        else{
                                            typeOfOne = 'Full-done';
                                        }
                                    }
                                    if(vs.VOI_Type_For__c == 'VOI'){
                                        if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                            typeOfOne = 'VOI-not';
                                        }
                                        else{
                                            typeOfOne = 'VOI-done';
                                        }
                                    }
                                    if(vs.VOI_Type_For__c == 'E-SIGN'){
                                        if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                            typeOfOne = 'sign-not';
                                        }
                                        else{
                                            typeOfOne = 'sign-done';
                                        }
                                    }
                                }
                            }
                            if((typeOfOne == 'Full-not' || typeOfOne == 'VOI-not') && tc.Order__c == 28){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);  
                            }
                            else if((typeOfOne == 'Full-not' || typeOfOne == 'sign-not') && tc.Order__c == 29){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);  
                            }
                            else if((typeOfOne == 'Full-done' || typeOfOne == 'VOI-done') && tc.Order__c == 19){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                            }
                            else if((typeOfOne == 'Full-done' || typeOfOne == 'sign-done') && tc.Order__c == 20){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj);
                            }
                            
                            if(typeOfOne == 'sign-not' && (full || VOI) && tc.Order__c == 19){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj); 
                            }
                            if(typeOfOne == 'VOI-not' && (full || Esign) && tc.Order__c == 20){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj); 
                            }
                            
                            if(typeOfOne == 'sign-done' && (full || VOI) && tc.Order__c == 19){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj); 
                            }
                            if(typeOfOne == 'VOI-done' && (full || Esign) && tc.Order__c == 20){
                                activityWrapper obj = new activityWrapper();
                                obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_1__r.name;
                                obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                obj.iconName = tc.Icon_Name__c;
                                obj.isMajor = tc.is_Major__c;
                                obj.toDoFor = tc.Todo_s_For__c;
                                ActList.add(obj); 
                            }
                            
                            
                                if(op.Applicant_2__c != null && VOIMAP.get(op.Applicant_2__r.PersonContactId) != null && VOIMAP.get(op.Applicant_2__r.PersonContactId).size() > 0){
                                    string typeOfTwo = '';
                                    boolean fullTwo = false;
                                    boolean VOITwo = false;
                                    boolean EsignTwo = false;
                                    for(VOI_Status__c vs : VOIMAP.get(op.Applicant_2__r.PersonContactId)){
                                        if(vs.VOI_Type_For__c == 'FULL'){
                                            if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                                fullTwo = true;
                                                if(!test.isRunningTest())
                                                    break;
                                            }
                                        }    
                                        if(vs.VOI_Type_For__c == 'VOI'){
                                            if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                                VOITwo = true;
                                                if(!test.isRunningTest())
                                                    break;
                                            }
                                        }
                                        if(vs.VOI_Type_For__c == 'E-SIGN'){
                                            if(vs.Case_Status__c == 'Verified' || vs.Case_Status__c == 'Submitted'){
                                                EsignTwo = true;
                                                if(!test.isRunningTest())
                                                    break;
                                            }
                                        }
                                    }
                                    
                                    for(VOI_Status__c vs : VOIMAP.get(op.Applicant_2__r.personContactid)){
                                        if(vs.VOI_Type_For__c == 'FULL'){
                                            if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                                typeOfTwo = 'Full-not';
                                            }
                                            else{
                                                typeOfTwo = 'Full-done';
                                            }
                                        }
                                        if(vs.VOI_Type_For__c == 'VOI'){
                                            if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                                typeOfTwo = 'VOI-not';
                                            }
                                            else{
                                                typeOfTwo = 'VOI-done';
                                            }
                                        }
                                        if(vs.VOI_Type_For__c == 'E-SIGN'){
                                            if(vs.Case_Status__c == 'Sent' || vs.Case_Status__c == 'Delivered'){
                                                typeOfTwo = 'sign-not';
                                            }
                                            else{
                                                typeOfTwo = 'sign-done';
                                            }
                                        }
                                    }
                                    if((typeOfTwo == 'Full-not' || typeOfTwo == 'VOI-not') && tc.Order__c == 28){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj);  
                                    }
                                    else if((typeOfTwo == 'Full-not' || typeOfTwo == 'sign-not') && tc.Order__c == 29){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj);  
                                    }
                                    else if((typeOfTwo == 'Full-done' || typeOfTwo == 'VOI-done') && tc.Order__c == 19){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj);
                                    }
                                    else if((typeOfTwo == 'Full-done' || typeOfTwo == 'sign-done') && tc.Order__c == 20){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj);
                                    }
                                    
                                    if(typeOfTwo == 'sign-not' && (fullTwo || VOITwo) && tc.Order__c == 19){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj); 
                                    }
                                    if(typeOfTwo == 'VOI-not' && (fullTwo || EsignTwo) && tc.Order__c == 20){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj); 
                                    }
                                    
                                    if(typeOfTwo == 'sign-done' && (fullTwo || VOITwo) && tc.Order__c == 19){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj); 
                                    }
                                    if(typeOfTwo == 'VOI-done' && (fullTwo || EsignTwo) && tc.Order__c == 20){
                                        activityWrapper obj = new activityWrapper();
                                        obj.doneText = tc.Done_Title__c + ' for ' + op.Applicant_2__r.name;
                                        obj.status = (tc.Status__c != null ? tc.Status__c : '');
                                        obj.iconName = tc.Icon_Name__c;
                                        obj.isMajor = tc.is_Major__c;
                                        obj.toDoFor = tc.Todo_s_For__c;
                                        ActList.add(obj); 
                                    }
                                }
                        }
                    }
                }
                else{
                    if((op.get(tc.Condition_1__c) == null ? false : tc.Value_1__c.contains((string)op.get(tc.Condition_1__c))) && (op.get(tc.Condition_2__c) == null ? false : tc.Value_2__c.contains((string)op.get(tc.Condition_2__c)))
                        && (op.get(tc.Condition_3__c) == null ? false : tc.Value_3__c.contains((string)op.get(tc.Condition_3__c)))){
                            activityWrapper obj = new activityWrapper();
                            obj.doneText = tc.Done_Title__c;
                            obj.status = (tc.Status__c != null ? tc.Status__c : '');
                            obj.iconName = tc.Icon_Name__c;
                            obj.isMajor = tc.is_Major__c;
                            obj.toDoFor = tc.Todo_s_For__c;
                            ActList.add(obj);
                        }
                    }                       
            }
        }
        
        string value = '[';
        for(Integer i=0; i<ActList.size(); i++){
            value+= '{';
            value += '"doneText":"'+ActList[i].doneText+'",';
            value += '"status":"'+ActList[i].status+'",';
            value += '"iconName":"'+ActList[i].iconName+'",';
            value += '"isMajor":"'+ActList[i].isMajor+'",';
            value += '"toDoFor":"'+ActList[i].toDoFor+'"';
            value+= '}';
            if(i != ActList.size()-1)
            {
                value += ',';
            }
        }
        value+= ']';
        op.Line_Chart_JSON__c = '';
        op.Line_Chart_JSON__c = value;
        if(op.Line_Chart_JSON__c != oldOPVal){
            OpportunityTriggerHandler.isByPassTrigger = true;
            update op;
            OpportunityTriggerHandler.isByPassTrigger = false;
        }
        return ActList;
        
    } 
    
    public class activityWrapper{
        @AuraEnabled public string doneText;
        @AuraEnabled public string status;
        @AuraEnabled public String iconName;
        @AuraEnabled public Boolean isMajor;
        @AuraEnabled public string toDoFor;
    }
    
}