force-app/main/default/objects/Average_Stage_Tracker__c/Average_Stage_Tracker__c.object-meta.xml
<CustomObject>
    <label>Average Stage Tracker</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>Stage Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Average Stage Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Average_Stage_Tracker__c/fields/Average_Stage_Duration__c.field-meta.xml
<CustomField>
    <fullName>Average_Stage_Duration__c</fullName>
    <label>Average Stage Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Time_at_current_stage__c.field-meta.xml
<CustomField>
    <fullName>Time_at_current_stage__c</fullName>
    <formula>VALUE(TEXT(
    IF(MOD((NOW() - Last_Stage_Change_Date__c)*24,24)&lt;9,
        CEILING(( NOW()  - Last_Stage_Change_Date__c))-1,
        CEILING((NOW()  - Last_Stage_Change_Date__c))
    )
    +
    MOD(
        ROUND(
            9 * (
                ( 5 *
                    FLOOR(
                        ( DATEVALUE(NOW()) - DATE( 1900, 1, 8) ) / 7) +
                        MIN(5, MOD( DATEVALUE(NOW()) - DATE( 1900, 1, 8), 7) +
                        MIN( 1, 24 / 9 * ( MOD(NOW() - DATETIMEVALUE( &apos;1900-01-08 22:00:00&apos; ), 1 ) ) )
                    )
                )-( 5 *
                     FLOOR(
                         ( DATEVALUE(Last_Stage_Change_Date__c  ) - DATE( 1900, 1, 8) ) / 7) +
                        MIN( 5, MOD( DATEVALUE(Last_Stage_Change_Date__c ) - DATE( 1996, 1, 1), 7 ) +
                        MIN( 1, 24 / 9 * ( MOD(Last_Stage_Change_Date__c - DATETIMEVALUE( &apos;1900-01-08 22:00:00&apos; ), 1) ) )
                    )
                )
            ),
        0), 9
    )/10
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time at current stage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StageTrackerReportScheduler.cls
global class StageTrackerReportScheduler  implements Schedulable {
    global void execute(SchedulableContext sc){
        try{
            
            executeCreate();
        }catch(exception e){
            UtilityClass.createException('', 'StageTrackerReportScheduler', 'execute', e.getMessage(), e.getStackTraceString(), ''+e.getLineNumber(),
                                         e.getTypeName(), ''+e.getCause());

        }
    }
	
    global void executeCreate(){
        
        Map<Id, Opportunity> oppStageTrackingMap = New Map<Id, Opportunity>();
        
        Map<String, Map<String, Decimal>> stageWithDurationMap = New Map<String, Map<String, Decimal>>();

        for(Opportunity opp: [SELECT Id,Time_at_current_stage__c, StageName FROM Opportunity LIMIT 50000]){
                                  
            System.debug('@@@@opp= '+ opp);
            Map<String, Decimal> durationMap = stageWithDurationMap.get(opp.StageName);
            
            if(durationMap == NULL){
                durationMap = New Map<String, Decimal>();
                durationMap.put('count', 0);
                durationMap.put('duration', 0);
            }
            
            durationMap.put('count', durationMap.get('count') + 1);
            durationMap.put('duration', durationMap.get('duration') + (opp.Time_at_current_stage__c == NULL ? 0 : opp.Time_at_current_stage__c));
            stageWithDurationMap.put(opp.StageName, durationMap);
        }
        List<Average_Stage_Tracker__c> avrgStageTrackerList = New List<Average_Stage_Tracker__c>();
        for(String st: getStages()){
            Decimal duration = 0;
            if(stageWithDurationMap.containsKey(st) && stageWithDurationMap.get(st).get('count') > 0){
                duration = stageWithDurationMap.get(st).get('duration')/stageWithDurationMap.get(st).get('count');
            }
            Average_Stage_Tracker__c aStageTracker = New Average_Stage_Tracker__c(
                Average_Stage_Duration__c  = duration,
                Date__c = Date.today(),
                Stage_Name__c = st
            );
            avrgStageTrackerList.add(aStageTracker);
        }
        insert avrgStageTrackerList;
        
    }
    
    private List<String> getStages(){
        List<String> appSectionsList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.StageName.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
            appSectionsList.add(f.getLabel());
        }   
        return appSectionsList;
    }
}