force-app/main/default/objects/Manage_Document__c/Manage_Document__c.object-meta.xml
<CustomObject>
    <label>Manage Document</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>Manage Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Document__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Application</fullName>
            </value>
            <value>
                <fullName>Solar Application</fullName>
            </value>
            <value>
                <fullName>Debit Consolidation</fullName>
            </value>
            <value>
                <fullName>Home Loan Refinance</fullName>
            </value>
            <value>
                <fullName>Home Purchase</fullName>
            </value>
            <value>
                <fullName>Generic Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Document__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manage_Document__c/fields/IsJoint__c.field-meta.xml
<CustomField>
    <fullName>IsJoint__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsJoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Identification</fullName>
    </customValue>
    <customValue>
        <fullName>Income</fullName>
    </customValue>
    <customValue>
        <fullName>Business Income</fullName>
    </customValue>
    <customValue>
        <fullName>Rental Income</fullName>
    </customValue>
    <customValue>
        <fullName>Liabilities Being Refinanced</fullName>
    </customValue>
    <customValue>
        <fullName>Liabilities Remaining</fullName>
    </customValue>
    <customValue>
        <fullName>Living Expenses</fullName>
    </customValue>
    <customValue>
        <fullName>Assets</fullName>
    </customValue>
    <customValue>
        <fullName>Loan Purpose</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Standard If Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Proof of Ownership</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Report</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Lender Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Proposal</fullName>
    </customValue>
    <customValue>
        <fullName>Lender Credit Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Preliminary Assessment</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Debit Form</fullName>
    </customValue>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManageDocumentController_Test.cls
@isTest
private class ManageDocumentController_Test {
    static testMethod void checkApplicantTwo(){
         Opportunity opp = new Opportunity(Name='Test', StageName='open', CloseDate= Date.today());
         Insert opp;
        Manage_Document__c Md = new Manage_Document__c(isJoint__c = true, Application_Type__c ='Home Loan Refinance;Home Purchase', Category__c='Identification', Document__c='Passport');
        Insert Md;
        Contact con = new Contact(LastName = 'Test', Email='test@tet.com');
        insert con;
        OpportunityContactRole Oc = new OpportunityContactRole();
        Oc.IsPrimary = true;
        oc.ContactId= con.Id;
        oc.OpportunityId = opp.Id;
        insert oc;
        boolean test = ManageDocumentController.checkApplicantTwo(opp.Id);
        //object op1 = ManageDocumentController.getApplicantOne();
        object opJ = ManageDocumentController.getJointApplication();
        object SC = ManageDocumentController.getSelectedCategory('Home Loan Refinance');
        Md.IsJoint__c = false;
        update Md;
        object op2 = ManageDocumentController.getApplicantTwo();
        object op1 = ManageDocumentController.getApplicantOne();
        ManageDocumentController.sendMail('balkishan.kachawa@gmail.com','sushil.verma6@gmail.com','hello how are you?');
        ManageDocumentController.createDocumentRequest('[{"label":"ApplicantOne","value":[{"categry":"Income","selectedItem":[{"label":"Payslips : 2 recent consecutive (no older than 6 weeks)","value":"Payslips","Discription":"","isBankStatment":false}]},{"categry":"Identification","selectedItem":[{"label":"Driver’s license (front and back)","value":"Driver’s license (front and back)","Discription":"","isBankStatment":false},{"label":"Medicare Card","value":"Medicare Card","Discription":"","isBankStatment":false}]}]},{"label":"JointApp","value":[{"categry":"Assets","selectedItem":[{"label":"Recent council rates notice","value":"Recent council rates notice","Discription":"","isBankStatment":false}]},{"categry":"Living Expenses","selectedItem":[{"label":"Last 3 months transaction bank statements","value":"Last 3 months transaction bank statements","Discription":"","isBankStatment":true}]}]}]',true, opp.Id,true);
    }
}