force-app/main/default/objects/Document_Requested__c/Document_Requested__c.object-meta.xml
<CustomObject>
    <label>Document Requested</label>
    <nameField>
        <displayFormat>DR-{0000000000}</displayFormat>
        <label>Document Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Requested</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Requested__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/is_bank_fail__c.field-meta.xml
<CustomField>
    <fullName>is_bank_fail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is bank fail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/isComplete__c.field-meta.xml
<CustomField>
    <fullName>isComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isComplete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Requested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents Requested</relationshipLabel>
    <relationshipName>Documents_Requested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/bankStatementServiceTest.cls
@isTest
public class bankStatementServiceTest {
    
    @istest
    public static void EmailService(){
        Opportunity opp = new Opportunity(Name='Test', StageName='open', CloseDate= Date.today(), RecordTypeId = '0120o000001lPS9AAM');
        Insert opp;
       
		Document_Requested__c Dc = new Document_Requested__c(Opportunity__c = opp.id, isComplete__c = false,Document__c='Test',Category__c='Bank Statements');
        insert Dc;
        
        Document_Requested__c doc = [select id,Category__c,is_bank_fail__c, isComplete__c,Document__c from Document_Requested__c where Opportunity__r.id =:opp.id ];
        SYstem.debug('doc__+_+'+doc.Category__c);
        
        Messaging.InboundEmail testEmail = new Messaging.InboundEmail();
        testEmail.subject = 'Test Subject-' + opp.Id;
        testEmail.htmlBody = '<p>Test Body</p>';
        Messaging.InboundEmail.TextAttachment textAttachment = new Messaging.InboundEmail.TextAttachment();
        textAttachment.fileName = 'test_file.txt';
        textAttachment.body ='Test Text Attachment';
        testEmail.textAttachments = new List<Messaging.InboundEmail.TextAttachment>{textAttachment};
            Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
        binaryAttachment.fileName = 'test_file.json';
        binaryAttachment.body = Blob.valueOf('{"test": "Test JSON Attachment"}');
        testEmail.binaryAttachments = new List<Messaging.InboundEmail.BinaryAttachment>{binaryAttachment};
            
            test.startTest();
        bankStatementService service = new bankStatementService();
        Messaging.InboundEmailResult result = service.handleInboundEmail(testEmail, null);     
        test.stopTest();
    }
    
    @istest
    public static void EmailServiceAnother(){
        Messaging.InboundEmail testEmail = new Messaging.InboundEmail();
        testEmail.subject = 'Test Subject';
        testEmail.htmlBody = '<p>Test Body</p>';
        Messaging.InboundEmail.TextAttachment textAttachment = new Messaging.InboundEmail.TextAttachment();
        textAttachment.fileName = 'test_file.txt';
        textAttachment.body ='Test Text Attachment';
        testEmail.textAttachments = new List<Messaging.InboundEmail.TextAttachment>{textAttachment};
            Messaging.InboundEmail.BinaryAttachment binaryAttachment = new Messaging.InboundEmail.BinaryAttachment();
        binaryAttachment.fileName = 'test_file.json';
        binaryAttachment.body = Blob.valueOf('{"test": "Test JSON Attachment"}');
        testEmail.binaryAttachments = new List<Messaging.InboundEmail.BinaryAttachment>{binaryAttachment};
            
            test.startTest();
        bankStatementService service = new bankStatementService();
        Messaging.InboundEmailResult result = service.handleInboundEmail(testEmail, null);     
        test.stopTest();
    }
}