force-app/main/default/objects/Loan_Fees__c/Loan_Fees__c.object-meta.xml
<CustomObject>
    <label>Loan Fees</label>
    <nameField>
        <label>Loan Fees</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fees__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Exit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Override_allowed__c.field-meta.xml
<CustomField>
    <fullName>Override_allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product_Loan_Fees__c.field-meta.xml
<CustomField>
    <fullName>Product_Loan_Fees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Loan Fees</label>
    <referenceTo>Loan_Fees__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Acceptable_Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Acceptable_Loan_Purpose__c</fullName>
    <label>Acceptable Loan Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
            <value>
                <fullName>General Personal</fullName>
                <isActive>false</isActive>
                <label>General Personal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brokerage_Override_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Override_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brokerage Override Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Override_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Commission_Override_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commission Override Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Eligibility__c</fullName>
    <label>Eligibility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Extra_Repayments__c.field-meta.xml
<CustomField>
    <fullName>Extra_Repayments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extra Repayments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Extra_Repayments_Details__c.field-meta.xml
<CustomField>
    <fullName>Extra_Repayments_Details__c</fullName>
    <label>Extra Repayments Details</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate_Override__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Rate Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loan_Amounts__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amounts__c</fullName>
    <formula>&apos;$&apos; &amp; TEXT(Minimum_Loan_Amount__c) &amp; &apos; to $&apos; &amp; TEXT(Maximum_Loan_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amounts</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <formula>Maximum_Loan_Term_Years__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Maximum_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Loan_Amount__c</fullName>
    <label>Maximum Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Min_Loan_Term__c</fullName>
    <formula>Minimum_Loan_Term_Years__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Minimum_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Loan_Amount__c</fullName>
    <label>Minimum Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Redraw__c.field-meta.xml
<CustomField>
    <fullName>Redraw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Redraw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Top_Up__c.field-meta.xml
<CustomField>
    <fullName>Top_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Top Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate_From__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_From__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Rate From</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate_Override__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Override__c</fullName>
    <label>Interest Rate Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <label>Max Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Min_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Min_Loan_Term__c</fullName>
    <label>Min Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/productSearch.cls
public class productSearch {
    @AuraEnabled
    public static String getOppStage(String oppId){
        String oppStage = [SELECT Id,StageName FROM Opportunity WHERE Id =: oppId][0].StageName;
        return oppStage;        
    }
    @AuraEnabled
    public static List<String> getProductType(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Product2.Acceptable_Loan_Purpose__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;        
    }
    @AuraEnabled
    public static List<Product2> getProduct(String prdtype, Decimal amount){
        return [SELECT id,  Interest_Rate__c,Interest_Rate_Override__c,Interest_Rate_From__c,Interest_Rate_Type__c,Actual_Comparison_Rate__c,Brokerage_Amount__c,Brokerage_Override_Allowed__c,Commission_Amount__c,Commission_Override_Allowed__c,Description,Features__c,Redraw__c,Extra_Repayments__c,Extra_Repayments_Details__c,Top_Up__c,Eligibility__c,Lender__c,Name, Max_Loan_Term__c ,Min_Loan_Term__c,Loan_Amounts__c , Acceptable_Loan_Purpose__c,Loan_Term__c,
                ( select id,Fee_Type__c,Frequency__c,Name,Override_allowed__c,Amount__c from Loan_Fees__r)
                FROM Product2
                WHERE Maximum_Loan_Amount__c >=: amount AND Minimum_Loan_Amount__c <=: amount AND Acceptable_Loan_Purpose__c INCLUDES(:prdtype)];
        
    }
    @AuraEnabled
    public static void insertQuote(String prodList, string PType, String groupName, String oppId){
        System.debug(oppId);
        if(String.isBlank(groupName)){
            groupName = 'Unknown';
        }
        List<Quote> quoteGruop = [Select Gruop_Name__c from quote where Gruop_Name__c like :groupName+'-%' AND  OpportunityId=: oppId 
                                  ORDER By Gruop_Name__c DESC LIMIT 1];
        if(quoteGruop.isEmpty()){
            groupName += '-1';
        }else{
            groupName +='-';
            groupName += (Integer.valueOf(quoteGruop.get(0).Gruop_Name__c.substringAfterLast(groupName))+1);
        }
        Map<integer, Quote> quoteMap = new Map<integer, Quote>();
        Map<integer, List<Loan_Fees__c>> feesMap = new Map<integer, List<Loan_Fees__c>>();
        List<quoteWrapper> pro = (List<quoteWrapper>)JSON.deserialize(prodList, List<quoteWrapper>.class);
        System.debug(pro);
        List<Quote> insertQute = new List<Quote>();
        integer i =  0 ;
        for(quoteWrapper var : pro){
            System.debug(var);
            //insertQute.add();
            Quote qt = new Quote();
            qt.Lender__c = var.Lender;
            qt.Max_Loan_Term__c = var.MaxTerm;
            qt.Min_Loan_Term__c = var.MinTerm;
            qt.Interest_Rate__c = var.InterestRate;
            qt.Product__c = var.Id;
            qt.OpportunityId = oppId;
            qt.Purpose__c = PType;
            qt.Gruop_Name__c = groupName;
            qt.Name = var.ProductName;
            qt.Description = var.Description;
            qt.Loan_Term__c = var.LoanTerm;
            qt.Brokerage_Amount__c = var.BrokerageAmount;
            qt.Commission_Amount__c = var.CommissionAmount;
            qt.Interest_Rate_From__c = var.InterestRateFrom;
            qt.Customer_Amount__c = var.LoanAmount;
            qt.Actual_Comparison_Rate__c = var.ComparisonRate;
            quoteMap.put(i, qt);
            feesMap.put(i++,var.feesList);
        }
        insert quoteMap.values();
        System.debug(quoteMap.values());
        List<Loan_Fees__c> fessList = new List<Loan_Fees__c>();
        Id loanfeeRT = Schema.SObjectType.Loan_Fees__c.getRecordTypeInfosByName().get('Quote Loan Fees').getRecordTypeId();
        for(integer var : quoteMap.keySet()){
            id opp = quoteMap.get(var).Id;
            System.debug(opp);
            for(Loan_Fees__c fs : feesMap.get(var)){
                if(fs != null){
                    fs.Product_Loan_Fees__c =fs.Id;
                    fs.id = null;
                    fs.Quote__c = opp;
                    fs.Product__c = null;
                    fs.RecordTypeId = loanfeeRT;
                    fessList.add(fs);
                }
                
            }
        }
        insert fessList;
        Opportunity opp = [SELECT Id,StageName FROM Opportunity WHERE Id =: oppId][0];
        opp.StageName = 'Quote';
        opp.Application_Sections__c = 'Loan Recommendation';
        opp.Current_Application_Sections__c = 'Loan Recommendation';
        update opp;
    }
    public class quoteWrapper{
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public boolean chk;
        @AuraEnabled
        public String Lender;
        @AuraEnabled
        public Decimal MaxTerm;
        @AuraEnabled
        public Decimal MinTerm;
        @AuraEnabled
        public Decimal LoanAmount;
        @AuraEnabled
        public Decimal InterestRate;
        @AuraEnabled
        public String ProductName;
        @AuraEnabled
        public Integer LoanTerm;
        @AuraEnabled
        public String InterestRateType;
        @AuraEnabled
        public Decimal ComparisonRate;
        @AuraEnabled
        public String Description;
        @AuraEnabled
        public String Features;
        @AuraEnabled
        public Boolean InterestRateFrom;
        @AuraEnabled
        public Decimal BrokerageAmount;
        @AuraEnabled
        public Boolean BrokerageOverrideAllowed;
        @AuraEnabled
        public Decimal CommissionAmount;
        @AuraEnabled
        public Boolean CommissionOverrideAllowed;
        @AuraEnabled
        public List<Loan_Fees__c> feesList;
    }
    
}