force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LineChart_Flag__c.field-meta.xml
<CustomField>
    <fullName>LineChart_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LineChart Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/batchForLineChart.cls
global class batchForLineChart implements Database.Batchable<sObject>,Database.Stateful {
    
    public List<opportunity> oppList;
    public batchForLineChart(List<opportunity> opp){
        oppList = new List<opportunity>();
        oppList = opp;
        System.debug('-=OPPOPOP++++'+oppList);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('select id, LineChart_Flag__c from opportunity where id IN : oppList');
    }
    
    global void execute(Database.BatchableContext bc, List<opportunity> scope) {
        System.debug('-=OPPOPOP++++'+oppList);
        System.debug('-=Scope++++'+scope.size());
        try{
            List<opportunity> oppl = new List<opportunity>();
            for(opportunity op : scope){
                Linechartcont.fillActivity(op.id);
                op.LineChart_Flag__c = true;
                oppl.add(op);
            }
            OpportunityTriggerHandler.isByPassTrigger = true;
            update oppl;
            OpportunityTriggerHandler.isByPassTrigger = false;
        }catch(Exception ex){
            insert new Exception__c(Class_Name__c = 'linechart batch', Method_Name__c = 'ALL', Error_Message__c = ex.getMessage() + '' + ex.getLineNumber());            
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients,
        // give a call to another batch class
        // Can give to another batch class
        // Can give callout request
        system.debug('batch job id = '+bc.getJobId());
    }
    
}