force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Exceptions</relationshipLabel>
    <relationshipName>Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomNotificationFromApex.cls
public without sharing class CustomNotificationFromApex {

    public static void notifyUsers(list<opportunity> opList, List<id> csUser, string title, string body) {
	    // Get the Id for our custom notification type
        CustomNotificationType notificationType = 
            [SELECT Id, DeveloperName 
             FROM CustomNotificationType 
             WHERE DeveloperName='customer_support_tasks'];
        set<string> userSt = new Set<string>();
        for(id ids : csUser){
            userSt.add(ids);
        }
        
        for(opportunity opp : opList){
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            notification.setTitle(title);
            notification.setBody(body);
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(opp.Id);
            try {
                notification.send(userSt);
            }
            catch (Exception e) {
                Exception__c eror = new Exception__c(Class_Name__c = 'CustomNotificationFromApex',Method_Name__c = 'notifyUsers',Error_Message__c = e.getMessage() + '' + e.getLineNumber(),opportunity__c = opList[0].id);
                insert eror;
            }    
        }
        
    }
}