force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/Loan_Fees__c.object-meta.xml
<CustomObject>
    <label>Loan Fees</label>
    <nameField>
        <label>Loan Fees</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fees__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Exit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Product_Loan_Fees__c.field-meta.xml
<CustomField>
    <fullName>Product_Loan_Fees__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Loan Fees</label>
    <referenceTo>Loan_Fees__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Fees__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/Loan_Rate__c.object-meta.xml
<CustomObject>
    <label>Loan Rate</label>
    <nameField>
        <label>Loan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Rate__c/fields/Comparison_rate__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/From_amount__c.field-meta.xml
<CustomField>
    <fullName>From_amount__c</fullName>
    <label>From amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/Interest_rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_rate__c</fullName>
    <label>Interest rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Rates</relationshipLabel>
    <relationshipName>Loan_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Rate__c/fields/To_amount__c.field-meta.xml
<CustomField>
    <fullName>To_amount__c</fullName>
    <label>To amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Temp_Flag__c.field-meta.xml
<CustomField>
    <fullName>Temp_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temp Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Default_Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Default_Loan_Term_Months__c</fullName>
    <formula>Default_Loan_Term__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Default Loan Term (Months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <formula>Maximum_Loan_Term_Years__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <label>Max Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Temp_Flag__c.field-meta.xml
<CustomField>
    <fullName>Temp_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temp Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/updateQuotesByProductBatch.cls
global class updateQuotesByProductBatch implements Database.Batchable<sObject>,Database.Stateful {
    
    private string productID;
    public updateQuotesByProductBatch(String proId) {
        productID = proId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        List<string> stages = new List<string>{'Nurturing','Working','CPA Started','CPA Done','Packs Out','Packs Back','Quote'};
            string Query = 'Select Id, Actual_Comparison_Rate__c, Customer_Amount__c,Product__r.Actual_Comparison_Rate__c, Name, Product__r.Name, Interest_Rate__c, Product__r.Interest_Rate__c,Loan_Term__c, Product__r.Max_Loan_Term__c, Product__r.Default_Loan_Term_Months__c, Commission_Amount__c, Product__r.Commission_Amount__c,Brokerage_Amount__c, Product__r.Brokerage_Amount__c, Lender__c, Product__r.Lender__c,(SELECT ID, Amount__c, Fee_Type__c, Frequency__c, Product_Loan_Fees__r.Amount__c, Product_Loan_Fees__r.Fee_Type__c, Product_Loan_Fees__r.Frequency__c FROM Loan_Fees__r)From Quote WHERE Product__c=:productID  AND Opportunity.StageName IN: stages Limit 10000';
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext bc, List<Quote> scope) {
        List<Loan_Rate__c> objList = new List<Loan_Rate__c>();
        List<Loan_Fees__c> lfees = new List<Loan_Fees__c>();
        List<Quote> quotesList = new List<Quote>();
        try{
            System.debug('SCOPR===='+scope.size());
            
            for(Loan_Rate__c lr : [select id,Interest_rate__c,From_amount__c,Comparison_rate__c,To_amount__c from Loan_Rate__c where Product__c = :productID ]){
                objList.add(lr);
            }
            
            for(Quote quote: scope){
                quote.Actual_Comparison_Rate__c = quote.Product__r.Actual_Comparison_Rate__c;
                quote.Name = quote.Product__r.Name;
                //quote.Interest_Rate__c = quote.Product__r.Interest_Rate__c;
                for(Loan_Rate__c  lr: objList){
                    //console.log('>>>>From_amount  ' + loanRates[i].From_amount__c);
                    if(lr.From_amount__c <= quote.Customer_Amount__c && lr.To_amount__c >= quote.Customer_Amount__c){
                        quote.Actual_Comparison_Rate__c = lr.Comparison_rate__c;
                        quote.Interest_Rate__c = lr.Interest_rate__c;
                        //break;
                    }
                }
                quote.Loan_Term__c = quote.Product__r.Max_Loan_Term__c;
                if(quote.Product__r.Default_Loan_Term_Months__c != NULL && quote.Product__r.Default_Loan_Term_Months__c > 0){   
                    quote.Loan_Term__c = quote.Product__r.Default_Loan_Term_Months__c;    
                }
                quote.Commission_Amount__c = quote.Product__r.Commission_Amount__c;
                quote.Brokerage_Amount__c = quote.Product__r.Brokerage_Amount__c;
                quote.Lender__c = quote.Product__r.Lender__c;
                //quote.Temp_Flag__c = true;
                quotesList.add(quote);
                
                for(Loan_Fees__c lf:quote.Loan_Fees__r){
                    lf.Amount__c = lf.Product_Loan_Fees__r.Amount__c;
                    lf.Fee_Type__c = lf.Product_Loan_Fees__r.Fee_Type__c;
                    lf.Frequency__c = lf.Product_Loan_Fees__r.Frequency__c;
                    lfees.add(lf);
                }
                
            }
        }catch(Exception ex){
            Exception__c eror = new Exception__c();
            eror.Class_Name__c = 'Quote Update Batch';
            eror.Method_Name__c = 'In code error';
            eror.Error_Message__c = ex.getMessage() + '' + ex.getLineNumber() + '' + ex.getCause();
            insert eror;  
        }
        System.debug('>>>>quotesList' + quotesList.size());
        System.debug('>>>>lfees' + lfees.size());
        try{
            database.update(lfees, false);
            Database.update(quotesList, false);
        }catch(Exception ex){
            Exception__c eror = new Exception__c();
            eror.Class_Name__c = 'Quote Update Batch';
            eror.Method_Name__c = 'updating Failed';
            eror.Error_Message__c = ex.getMessage() + '' + ex.getLineNumber() + '' + ex.getCause();
            insert eror;
        }
        
    }
    
    global void finish(Database.BatchableContext bc) {
        system.debug('batch job id = '+bc.getJobId());
        String userName = UserInfo.getUserName();
        User activeUser = [Select name,Email From User where Username = : userName limit 1];
        list<String> userEmail =  new List<string>();
        userEmail.add(activeUser.Email); 
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address =: activeUser.Email]; //sushil.verma1988@gmail.com
        if(owea != null){
            if ( owea.size() > 0 ) {
                email.setOrgWideEmailAddressId(owea.get(0).Id);
            }
        }
        string body = 'Hi ' + activeUser.name + '\n\n';
        body += 'Quotes are Updated Successfully';
        email.setToAddresses(userEmail);
        email.setSubject('Quotes are Updated Successfully!!');
        email.setPlainTextBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
    
}