force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UtilityClass.cls
public class UtilityClass {
    public static final String adminEmail = 'tazeem.khan@chazecloud.com';
    public static final string sendEMail = 'sethu.rawat@chazecloud.com';
    
    
    public static void createException(String recordId, String className, String methodName, String ErrorMessage, String stackTrace, String lineNo,
                                       String errorType, String errorCause){
                                           Exception__c exe = New Exception__c(Record_Id__c = recordId,
                                                                               Method_Name__c = methodName, 
                                                                               Class_Name__c = className,
                                                                               Error_Message__c = ErrorMessage,
                                                                               Error_Cause__c = errorCause,
                                                                               Line_Number__c = lineNo,
                                                                               Stack_Trace__c = stackTrace,
                                                                               Error_Type__c = errorType);
                                           try{
                                               insert exe;
                                           } catch (Exception e) {
                                               System.debug(e.getMessage());
                                           }
                                       }
    
    
}