force-app/main/default/objects/Lead/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Current_Application_Sections__c</fullName>
    <label>Current Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
/**
 * @description       : This is a Selector Class for Lead
 * @Author            : Sethu Singh Rawat
 * @Created on        : 26/02/2024
 * @Last Modified By  : Sethu Singh Rawat
 * @Last Modified On  : 26/02/2024
**/
public with sharing  class LeadSelector {
    
    public static Lead selectLeadId(String leadId){
        return[SELECT Id,Name,Application_Sections__c, Current_Application_Sections__c FROM Lead WHERE id =: leadId];
    }

}