force-app/main/default/objects/Lead/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Type</label>
    <referenceTo>Product_Type__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
                <default>true</default>
                <label>Priorities</label>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Comparison_Rate_Warning__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Rate_Warning__c</fullName>
    <label>Comparison Rate Warning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Eligibility__c</fullName>
    <label>Eligibility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Eligibility_Description__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Description__c</fullName>
    <label>Eligibility Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <formula>Maximum_Loan_Term_Years__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Min_Loan_Term__c</fullName>
    <formula>Minimum_Loan_Term_Years__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green Loan</fullName>
            </value>
            <value>
                <fullName>Consolidation Loan</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Car Loan</fullName>
            </value>
            <value>
                <fullName>First Home Loan</fullName>
            </value>
            <value>
                <fullName>Asset Finance</fullName>
                <isActive>false</isActive>
                <label>Asset Finance</label>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
                <isActive>false</isActive>
                <label>Debt Consolidation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/What_document_needs_to_apply__c.field-meta.xml
<CustomField>
    <fullName>What_document_needs_to_apply__c</fullName>
    <label>What document needs to apply</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Max_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Term__c</fullName>
    <label>Max Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Min_Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Min_Loan_Term__c</fullName>
    <label>Min Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Monthly_Repayment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Repayment__c</fullName>
    <formula>CEILING(((((Interest_Rate__c/12) * Total_loan_amount__c) * ((1 + (Interest_Rate__c/12))^Loan_Term__c)) / ((1 + (Interest_Rate__c/12))^Loan_Term__c - 1))+ Monthly_Account_Keeping_Fees__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ceiling Monthly Repayment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotationTemplatePDFCtrl.cls
public without sharing class QuotationTemplatePDFCtrl {
    public List<QuoteWrapper> quoteWrpList {get;set;}
    public Map<String,List<QuoteWrapper>> quoteWrpMap {get;set;}
    public Map<String,Decimal> custmerAmountMap {get;set;}
    public String loanPurpose {get;set;}
    public String applicantName {get;set;}
    public Decimal custmerAmount {get;set;}
    public Boolean isAfterLoanRecc {get;set;}
    public Opportunity opprtunity {get;set;}
    
    public QuotationTemplatePDFCtrl(){
        isAfterLoanRecc = false;
        applicantName='';
        custmerAmount = 0;
        opprtunity = New Opportunity();
        string OppId = apexpages.currentpage().getparameters().get('id');
        string isSelected =  apexpages.currentpage().getparameters().get('isSelected');
        custmerAmountMap = New Map<String,Decimal> ();
        if(String.isNotBlank(OppId)){
            quoteWrpMap = New Map<String,List<QuoteWrapper>>();
            quoteWrpList = New List<QuoteWrapper>();
            list<Opportunity> oppsQuotesList = new List<Opportunity>();
            if(isSelected=='yes'){
                oppsQuotesList=
                    [SELECT Id, Product_Type__c, Applicant_1__c, Applicant_2__c, Applicant_1__r.Name, Applicant_2__r.Name, Amount,
                     Application_Sections__c, Purpose__c,
                     (SELECT Id, Actual_Comparison_Rate__c, Comparison_Rate_Warning__c, Eligibility__c, Gruop_Name__c,
                      Product__r.Features__c,Product__r.What_document_needs_to_apply__c, Interest_Rate__c, Customer_Amount__c, Loan_Term__c, Name, Product__r.Eligibility_Description__c ,
                      Monthly_Repayment__c, Product__r.Min_Loan_Term__c, Product__r.Max_Loan_Term__c, Purpose__c, Lead__c,
                      Product__r.Lender__c,Product__r.Is_Feature_Product__c, Total_Loan_Cost__c, Weekly_Repayments__c, Product__r.Security__c, Product__r.Interest_Rate_Type__c,
                      Product__r.Description, Product__r.Product_Type__c, Product__r.Interest_Rate_From__c, Total_Setup_Fees__c, Lead__r.Name,isSelected__c
                      FROM Quotes where isSelected__c=true ORDER BY Product__r.Product_Order__c) 
                     FROM Opportunity WHERE Id =: OppId];
                System.debug('@@@@@oppsQuotesList' + oppsQuotesList.size());}
            else{
                oppsQuotesList=
                    [SELECT Id, Product_Type__c, Applicant_1__c, Applicant_2__c, Applicant_1__r.Name, Applicant_2__r.Name, Amount,
                     Application_Sections__c, Purpose__c,
                     (SELECT Id, Actual_Comparison_Rate__c, Comparison_Rate_Warning__c, Eligibility__c, Gruop_Name__c,
                      Product__r.Features__c,Product__r.What_document_needs_to_apply__c, Interest_Rate__c, Customer_Amount__c, Loan_Term__c, Name, Product__r.Eligibility_Description__c ,
                      Monthly_Repayment__c, Product__r.Min_Loan_Term__c, Product__r.Max_Loan_Term__c, Purpose__c, Lead__c,
                      Product__r.Lender__c,Product__r.Is_Feature_Product__c, Total_Loan_Cost__c, Weekly_Repayments__c, Product__r.Security__c, Product__r.Interest_Rate_Type__c,
                      Product__r.Description, Product__r.Product_Type__c, Product__r.Interest_Rate_From__c, Total_Setup_Fees__c, Lead__r.Name
                      FROM Quotes ORDER BY Product__r.Product_Order__c) 
                     FROM Opportunity WHERE Id =: OppId];
            }
            
            List<String> appSectionsList = ApplicationFormController.getApplicationSections();
            
            if(!oppsQuotesList.isEmpty()){
                opprtunity = oppsQuotesList[0];
                
                if(appSectionsList.indexOf(opprtunity.Application_Sections__c) >= 2){
                    isAfterLoanRecc = true;
                }
                
                if(isAfterLoanRecc){
                    if(String.isNotBlank(opprtunity.Applicant_1__c))
                        applicantName += opprtunity.Applicant_1__r.Name;
                    
                    if(String.isNotBlank(opprtunity.Applicant_2__c))
                        applicantName += ' and ' + opprtunity.Applicant_2__r.Name;
                }
                if(!opprtunity.Quotes.isEmpty()){
                    for(Quote qt : opprtunity.Quotes){
                        custmerAmount = qt.Customer_Amount__c;
                        applicantName = qt.Gruop_Name__c;
                        quoteWrpList.add(getQuoteWrapper(qt));
                        List<QuoteWrapper> quoteWrpListTemp = quoteWrpMap.get(qt.Gruop_Name__c);
                        if(quoteWrpListTemp == NULL){
                            quoteWrpListTemp = New List<QuoteWrapper>();
                        }                   
                        quoteWrpListTemp.add(getQuoteWrapper(qt));
                        custmerAmountMap.put(qt.Gruop_Name__c, qt.Customer_Amount__c);
                        quoteWrpMap.put(qt.Gruop_Name__c, quoteWrpListTemp);
                    }
                }
            }
        }  
    }
    
    private QuoteWrapper getQuoteWrapper(Quote qt){
        System.debug('@@@@@opprtunity.Quote' + qt);
        QuoteWrapper quoteWrp = New QuoteWrapper();
        quoteWrp.Loan_Term = qt.Loan_Term__c;
        quoteWrp.Monthly_Repayment = qt.Monthly_Repayment__c;
        quoteWrp.Weekly_Repayments = qt.Weekly_Repayments__c;
        quoteWrp.Security = qt.Product__r.Security__c;
        quoteWrp.Interest_Rate_Type = qt.Product__r.Interest_Rate_Type__c;
        quoteWrp.Interest_Rate = qt.Interest_Rate__c;
        quoteWrp.Actual_Comparison_Rate = qt.Actual_Comparison_Rate__c;
        quoteWrp.Description = qt.Product__r.Description;
        quoteWrp.Lender = qt.Product__r.Lender__c;
        quoteWrp.Total_Setup_Fees = qt.Total_Setup_Fees__c;
        quoteWrp.Total_Loan_Cost = qt.Total_Loan_Cost__c;
        quoteWrp.Eligibility_Description = qt.Product__r.Eligibility_Description__c;
        quoteWrp.fromStr = qt.Product__r.Interest_Rate_From__c ? ' From' : '';
        quoteWrp.Loan_Term_Available = qt.Product__r.Min_Loan_Term__c + '-' + qt.Product__r.Max_Loan_Term__c;
        quoteWrp.Loan_Term_Year = qt.Product__r.Min_Loan_Term__c/12 + '-' + qt.Product__r.Max_Loan_Term__c/12;
        quoteWrp.isFeatured = qt.Product__r.Is_Feature_Product__c;
        if(qt.Product__r.Features__c != Null){
            quoteWrp.features = qt.Product__r.Features__c.split(';');
        }
        if(qt.Product__r.What_document_needs_to_apply__c != Null){
            quoteWrp.whatYouGet = qt.Product__r.What_document_needs_to_apply__c.split(';');
        }        
        return quoteWrp;
    }
    
    public class QuoteWrapper{
        public list<String> features {get;set;}
        public list<String> whatYouGet {get;set;}
        public Decimal Loan_Term {get;set;}
        public Decimal Monthly_Repayment {get;set;}
        public Decimal Weekly_Repayments {get;set;}
        public String Gruop_Name {get;set;}
        public String Security {get;set;}
        public String Interest_Rate_Type {get;set;}
        public Decimal Interest_Rate {get;set;}
        public Decimal Actual_Comparison_Rate {get;set;}
        public String Description {get;set;}
        public String Lender {get;set;}
        public String fromStr {get;set;}
        public Decimal Total_Setup_Fees {get;set;}
        public Decimal Total_Loan_Cost {get;set;}
        public String Eligibility_Description {get;set;}
        public String Loan_Term_Available {get;set;}
        public String Loan_Term_Year {get;set;}
        public Boolean isFeatured {get;set;}
    }
}