force-app/main/default/objects/Lead/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/isSelected__c.field-meta.xml
<CustomField>
    <fullName>isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_Group_Label__c.field-meta.xml
<CustomField>
    <fullName>Quote_Group_Label__c</fullName>
    <label>Quote Group Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuotesEmailControllerTest.cls
@isTest
private class QuotesEmailControllerTest {
    @testSetup
    static void createTestData() {
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account acc = new account();
        acc.RecordTypeId= recordTypeId;
        acc.FirstName = 'Test';
        acc.LastName = 'Testr'; 
        acc.PersonEmail='rakesh@gmail.com';
        insert acc;
        
        Opportunity testOpp1 = new Opportunity();
        testOpp1.Name = 'Test Opportunity 1';
        testOpp1.StageName ='Approved';
        testOpp1.CloseDate = System.Today();
        testOpp1.Loan_Amount__c = 22000;
        testOpp1.Applicant_1__c = acc.Id;
        insert testOpp1;

        List<Quote> quotes = new List<Quote>();
        quotes.add(new Quote(
            Name = 'Test Quote 1',
            Customer_Amount__c = 1000,
            OpportunityId = testOpp1.Id,
            Interest_Rate__c = 0.01,
            Gruop_Name__c = 'Test Group Label 1',
            Quote_Group_Label__c = 'Test Group Label 1',
            Actual_Comparison_Rate__c = 0.02,
            IsSelected__c = true
        ));
        quotes.add(new Quote(
            Name = 'Test Quote 2',
            Customer_Amount__c = 2000,
            OpportunityId = testOpp1.Id,
            Interest_Rate__c = 0.02,
            Gruop_Name__c = 'Test Group Label 1',
            Quote_Group_Label__c = 'Test Group Label 1',
            Actual_Comparison_Rate__c = 0.03,
            IsSelected__c = true
        ));
        insert quotes;
        
        Opportunity testOpp2 = new Opportunity();
        testOpp2.Name = 'Test Opportunity 2';
        testOpp2.StageName ='Approved';
        testOpp2.CloseDate = System.Today();
        testOpp2.Loan_Amount__c = 22000;
        testOpp2.SyncedQuoteId = quotes[0].id;
        insert testOpp2;
        
        lead jd = new lead();
        jd.Email ='rakesh@gmail.com';
        jd.LastName='test';
        insert jd;
        
    }

    @isTest
    static void testInit() {
        QuotesEmailController controller = new QuotesEmailController();
        controller.opportunityId = [SELECT Id FROM Opportunity where name='Test Opportunity 1' LIMIT 1].Id;
        
        Test.startTest();
        controller.init();
        Test.stopTest();
   
    }
    
    @isTest
    static void testgetOpportunity() {
        QuotesEmailController controller = new QuotesEmailController();
        controller.opportunityId = [SELECT Id FROM Opportunity where name='Test Opportunity 2' LIMIT 1].Id;
        
        Test.startTest();
        controller.getOpportunity();
        Test.stopTest();
   
    }
}