force-app/main/default/objects/Lead/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Referrals</relationshipLabel>
    <relationshipName>Referral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/leadAddress__c.field-meta.xml
<CustomField>
    <fullName>leadAddress__c</fullName>
    <description>For solar quotes</description>
    <label>leadAddress</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Send_the_quote_to__c.field-meta.xml
<CustomField>
    <fullName>Send_the_quote_to__c</fullName>
    <label>Send the quote to</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Me and my customer</fullName>
            </value>
            <value>
                <fullName>Me only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_Email__c</fullName>
    <formula>Applicant_1__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 1 Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_FirstName__c</fullName>
    <formula>Applicant_1__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 1 FirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_Name__c</fullName>
    <formula>Applicant_1__r.FirstName+&apos; &apos;+Applicant_1__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 1 Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_FirstName__c</fullName>
    <formula>Applicant_2__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 2 FirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_Name__c</fullName>
    <formula>Applicant_2__r.FirstName+&apos; &apos;+Applicant_2__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 2 Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documents_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Documents_Outstanding__c</fullName>
    <description>Documents Outstanding</description>
    <label>Documents Outstanding</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/leadAddress__c.field-meta.xml
<CustomField>
    <fullName>leadAddress__c</fullName>
    <description>For solar quotes</description>
    <label>leadAddress</label>
    <length>550</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_the_quote_to__c.field-meta.xml
<CustomField>
    <fullName>Send_the_quote_to__c</fullName>
    <label>Send the quote to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Me and my customer</fullName>
            </value>
            <value>
                <fullName>Me only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Actual_Comparison_Rate__c.field-meta.xml
<CustomField>
    <fullName>Actual_Comparison_Rate__c</fullName>
    <label>Comparison Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Comparison_Rate_Display__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Rate_Display__c</fullName>
    <formula>Product__r.Comparison_Rate_Display__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comparison Rate Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/isSelected__c.field-meta.xml
<CustomField>
    <fullName>isSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Master_Quote_For_URL__c.field-meta.xml
<CustomField>
    <fullName>Master_Quote_For_URL__c</fullName>
    <formula>SUBSTITUTE(Gruop_Name__c, &apos;&amp;&apos;, &apos;%26&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Master Quote For URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Monthly_Repayment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Repayment__c</fullName>
    <formula>CEILING(((((Interest_Rate__c/12) * Total_loan_amount__c) * ((1 + (Interest_Rate__c/12))^Loan_Term__c)) / ((1 + (Interest_Rate__c/12))^Loan_Term__c - 1))+ Monthly_Account_Keeping_Fees__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ceiling Monthly Repayment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ORG_URL__c.field-meta.xml
<CustomField>
    <fullName>ORG_URL__c</fullName>
    <formula>&apos;https://apply-parkerlane.secure.force.com/&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ORG URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_Group_Label__c.field-meta.xml
<CustomField>
    <fullName>Quote_Group_Label__c</fullName>
    <label>Quote Group Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Details__c.field-meta.xml
<CustomField>
    <fullName>VOI_Details__c</fullName>
    <formula>Contact__r.FirstName + &apos; &apos; + Contact__r.MiddleName + &apos; &apos; + Contact__r.LastName + &apos; (&apos; + IF( ISBLANK(TEXT(VOI_Type_For__c) ) , TEXT(Contact__r.VOI_type__c), TEXT(VOI_Type_For__c) ) + &apos;)&apos;  
&amp; IF( OR(TEXT(VOI_Status__c) == &apos;Submitted&apos;, TEXT(VOI_Status__c) == &apos;eSign Complete&apos;), BR() &amp;&apos; (&apos; &amp; TEXT(VOI_Status__c ) &amp; &apos; &apos; &amp; TEXT(DAY( DATEVALUE(Date_submitted__c )))+&quot;/&quot; +TEXT(MONTH(DATEVALUE(Date_submitted__c )))+&quot;/&quot; +TEXT(YEAR(DATEVALUE(Date_submitted__c))) &amp; &apos; &apos; &amp; IF (ISBLANK(DATEVALUE(Date_submitted__c )), &quot;&quot;,
IF(HOUR(TIMEVALUE(Date_submitted__c )) &lt; 12, TEXT(HOUR(TIMEVALUE(Date_submitted__c )) + 12), TEXT(HOUR(TIMEVALUE(Date_submitted__c ) ) - 12)) &amp; &quot;:&quot; &amp;
IF (MINUTE(TIMEVALUE(Date_submitted__c )) &lt; 10, &quot;0&quot; + TEXT(MINUTE(TIMEVALUE(Date_submitted__c ))), TEXT(MINUTE(TIMEVALUE(Date_submitted__c )))) ) &amp;&apos;)&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VOI Details</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotesEmailController.cls
public class QuotesEmailController {
    public String opportunityId{get;set;}
    public String opportunityName{get;set;}
    public String leadName{get;set;}
    public String custName{get;set;}
    public String refName{get;set;}
    public String purpose{get;set;}
    public String address{get;set;}
    public String phone{get;set;}
    public String sendQuoteTo{get;set;}
    public String openUrl{get;set;}
    public Boolean var1{get;set;}
    public Boolean var2{get;set;}
    public Boolean noVoi{get;set;}    
    public list<quoteWrp> qtWrapper{get;set;}
    public Quote qtDetails{get;set;}
    
    
    public Boolean init{
        get{
            init();            
            return false;
        }
    } 
    
    public opportunity getOpportunity(){
        var1 = false;
        var2 = false;
        noVoi = false;
        String custLabel = System.Label.baseUrl;        
        Opportunity opp = [select id,name,StageName,SyncedQuoteId,Applicant_1__r.personContactId,Applicant_2__r.personContactId,Applicant_1_FirstName__c,Applicant_2_FirstName__c,purpose__c,Applicant_1_Name__c,Applicant_2_Name__c,Documents_Outstanding__c from opportunity where id=:opportunityId LIMIT 1];
        system.debug('Documents_Outstanding__c'+opp.Documents_Outstanding__c);
        Quote qtDetails = [Select id, Gruop_Name__c from Quote where id =: opp.SyncedQuoteId];
        openUrl = custLabel+'?id='+opportunityId+'&master='+qtDetails.Gruop_Name__c.replace('&', '%26')+ '';
        list<VOI_Status__c> newlst = [select id,Contact__c,VOI_Details__c,VOI_Status__c from VOI_Status__c where Opportunity__c =: opportunityId];
        system.debug('newlst'+newlst);
        if(newlst.isEmpty()){
            noVoi = true;
        }
        for(VOI_Status__c sd : newlst){
            if(sd.Contact__c == opp.Applicant_1__r.personContactId){
                if(sd.VOI_Status__c == 'Sent' || sd.VOI_Status__c == 'Delivered'){
                    var1 = true;
                }
            }
            if(opp.Applicant_2__c != null){
                if(sd.Contact__c == opp.Applicant_2__r.personContactId){
                    if(sd.VOI_Status__c == 'Sent' || sd.VOI_Status__c == 'Delivered'){
                        var2 = true;
                    }
                }   
            }            
        }
        
        system.debug('newlst>>>>>'+newlst);
        return opp;
    }
    
    public void init(){
        
        Opportunity opp = [select id,name,Applicant_1_FirstName__c,Applicant_1_Email__c,FinServ__ReferredByContact__r.Name,purpose__c,leadAddress__c, Applicant_1__r.phone, Send_the_quote_to__c from opportunity where id=:opportunityId LIMIT 1];
        Lead ld = [select id,name,email from lead where email=:opp.Applicant_1_Email__c limit 1];
         opportunityName = opp.Name;
         custName = opp.Applicant_1_FirstName__c;
         leadName = ld.Name;
         refName  = opp.FinServ__ReferredByContact__r.Name;
         purpose  = opp.Purpose__c;
         address  = opp.leadAddress__c;
         phone    = opp.Applicant_1__r.phone;
         sendQuoteTo = opp.Send_the_quote_to__c;
        Map<String,quoteWrp> mapOfquotes = new Map<String,quoteWrp>();
        decimal minInterest=0;
        decimal minRepayment=0;
        list<Quote> qtList =[SELECT id,Name,QuoteNumber,Customer_Amount__c,Master_Quote_For_URL__c,ORG_URL__c,OpportunityId,Interest_Rate__c,Monthly_Repayment__c,Gruop_Name__c,Quote_Group_Label__c,Application__c,Loan_Term__c,Comparison_Rate_Display__c,Actual_Comparison_Rate__c FROM Quote WHERE
                             OpportunityId =: opportunityId AND IsSelected__c=true];
        system.debug('My list--'+qtList);
        for(Quote qt : qtList){
            quoteWrp quoteWrapper = new quoteWrp();
            if(!mapOfquotes.containskey(qt.Gruop_Name__c)){
                quoteWrapper.InterestRate = qt.Interest_Rate__c;
                minInterest = qt.Interest_Rate__c;
                quoteWrapper.Repayment = qt.Monthly_Repayment__c;
                minRepayment = qt.Monthly_Repayment__c;
                quoteWrapper.ComparsionRate= qt.Actual_Comparison_Rate__c;
                quoteWrapper.Loanterm = qt.Loan_Term__c;
                quoteWrapper.Amount=qt.Customer_Amount__c;
                quoteWrapper.GroupName = qt.Gruop_Name__c;
                quoteWrapper.GroupLabel = qt.Quote_Group_Label__c;
                quoteWrapper.isChecked = false;
                quoteWrapper.masterQuoteForURL = qt.Master_Quote_For_URL__c;
                quoteWrapper.compRateDisplay = qt.Comparison_Rate_Display__c;
                quoteWrapper.orgURL = qt.ORG_URL__c;
                quoteWrapper.oppId = qt.OpportunityId;
                mapOfquotes.put(qt.Gruop_Name__c,quoteWrapper);
            }
            else{
                if(qt.Interest_Rate__c < minInterest){
                    quoteWrapper.InterestRate = qt.Interest_Rate__c;
                    quoteWrapper.ComparsionRate= qt.Actual_Comparison_Rate__c;
                    minInterest = qt.Interest_Rate__c;
                }
                else if(qt.Interest_Rate__c == minInterest){
                    if(mapOfquotes.get(qt.Gruop_Name__c).ComparsionRate > qt.Actual_Comparison_Rate__c){
                        quoteWrapper.ComparsionRate= qt.Actual_Comparison_Rate__c;
                    }
                    quoteWrapper.InterestRate = qt.Interest_Rate__c;
                    quoteWrapper.ComparsionRate= qt.Actual_Comparison_Rate__c;
                    minInterest = qt.Interest_Rate__c;
                }
                else{
                    quoteWrapper.InterestRate = mapOfquotes.get(qt.Gruop_Name__c).InterestRate;
                    quoteWrapper.ComparsionRate= mapOfquotes.get(qt.Gruop_Name__c).ComparsionRate;
                }
                if(qt.Monthly_Repayment__c < minRepayment){
                    quoteWrapper.Repayment = qt.Monthly_Repayment__c;
                    quoteWrapper.Loanterm  = qt.Loan_Term__c;
                    minRepayment = qt.Monthly_Repayment__c;
                }
                else{
                    quoteWrapper.Repayment = mapOfquotes.get(qt.Gruop_Name__c).Repayment;
                    quoteWrapper.Loanterm  = mapOfquotes.get(qt.Gruop_Name__c).Loanterm;
                }
                quoteWrapper.Amount = mapOfquotes.get(qt.Gruop_Name__c).Amount;
                quoteWrapper.GroupName = mapOfquotes.get(qt.Gruop_Name__c).GroupName;
                quoteWrapper.GroupLabel = mapOfquotes.get(qt.Gruop_Name__c).GroupLabel;
                quoteWrapper.isChecked = false;
                quoteWrapper.masterQuoteForURL = mapOfquotes.get(qt.Gruop_Name__c).masterQuoteForURL;
                quoteWrapper.compRateDisplay = mapOfquotes.get(qt.Gruop_Name__c).compRateDisplay;
                quoteWrapper.orgURL = mapOfquotes.get(qt.Gruop_Name__c).orgURL;
                quoteWrapper.oppId = mapOfquotes.get(qt.Gruop_Name__c).oppId;
                mapOfquotes.put(qt.Gruop_Name__c,quoteWrapper);
            }
        }
        qtWrapper = new list<quoteWrp>();
        if(mapOfquotes.values()!=null){
        qtWrapper = mapOfquotes.values();
        }
        system.debug('mail quoets--'+qtWrapper.size());
        //system.Assert(false);
        
    }
    
    public class quoteWrp{
        public Decimal InterestRate{get;set;}
        public Decimal ComparsionRate{get;set;}
        public Decimal Repayment{get;set;}
        public Decimal Loanterm{get;set;}
        public Decimal Amount{get;set;}
        public String oppId{get;set;}
        public string masterQuoteForURL{get;set;}
        public string compRateDisplay{get;set;}
        public string orgURL{get;set;}
        public String GroupName{get;set;}
        public String GroupLabel{get;set;}
        public Boolean isChecked{get;set;}
    }
    
    
}