force-app/main/default/objects/Lead/fields/installationAddressLineOne__c.field-meta.xml
<CustomField>
    <fullName>installationAddressLineOne__c</fullName>
    <label>installationAddressLineOne</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Point_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Origin__c</fullName>
    <label>Point of Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SolarQuotes API</fullName>
            </value>
            <value>
                <fullName>Referral Page</fullName>
            </value>
            <value>
                <fullName>Website Contact Form</fullName>
            </value>
            <value>
                <fullName>Website Quote / Application</fullName>
            </value>
            <value>
                <fullName>Calendly</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>1300 number</fullName>
            </value>
            <value>
                <fullName>Direct Adviser Call</fullName>
            </value>
            <value>
                <fullName>Direct Email</fullName>
            </value>
            <value>
                <fullName>Solar@parkerlane</fullName>
            </value>
            <value>
                <fullName>Hello@parkerlane</fullName>
            </value>
            <value>
                <fullName>98% Loan for First Home Buyers</fullName>
            </value>
            <value>
                <fullName>90% No LMI Everyday Heroes</fullName>
            </value>
            <value>
                <fullName>Screw Waiting General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/quarterlyBill__c.field-meta.xml
<CustomField>
    <fullName>quarterlyBill__c</fullName>
    <label>quarterlyBill</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referred_by_Aggregator_Acc__c.field-meta.xml
<CustomField>
    <fullName>Referred_by_Aggregator_Acc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred by Aggregator</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads &amp; Referrals (Referred by Aggregator)</relationshipLabel>
    <relationshipName>Leads_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <description>SQ</description>
    <label>Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/What_type_of_system_are_you_after__c.field-meta.xml
<CustomField>
    <fullName>What_type_of_system_are_you_after__c</fullName>
    <label>What type of system are you after?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReferralLeadIntegration.cls
@RestResource(urlMapping='/ReferralLeadIntegration/*')
global class ReferralLeadIntegration {
    
    @HttpPost
    //global static void createLead(String cFName, String cLName, String cEmail, String cPhone, String supplierdetail){
    global static void createLead(){    
    	String jsonStr ='{}';
        
        try{
            RestRequest req = RestContext.request;
            if(String.isBlank(req.requestBody.toString())){
                jsonStr ='{"Status" : "Error","Message" : "Required API body missing" }';
            }else{
                Map<String, Object> objMap = (Map<String, Object>)JSON.deserializeUntyped(req.requestBody.toString());
                String cFName = (String)objMap.get('cFName');
                String cLName = (String)objMap.get('cLName');
                String cEmail = (String)objMap.get('cEmail');
                String cPhone = (String)objMap.get('cPhone');
                String cMobilePhone = (String)objMap.get('cMobilePhone');
				String systemType = (String)objMap.get('systemType');
                String systemSize = (String)objMap.get('systemSize');
                String installationAdd = (String)objMap.get('InstallationAddress');
                String quarterlyEnergyBill = (String)objMap.get('QuarterlyEnergyBill');
                
                List<Object> supplierDetailList = New List<Object>();
                if(objMap.containsKey('supplierdetail')){
                	supplierDetailList = (List<Object>)objMap.get('supplierdetail');
                }
                if( String.isBlank(cLName)){
                    jsonStr ='{"Status" : "Error","Message" : "Required field[s] missing" }';
                }else{
                    
                    system.debug('>>supplierdetail>>>>>' + supplierDetailList);
                    Account Accgr = new Account();
                    if(!Test.isRunningTest()){
                        string accId = system.label.Solar_Quotes_Id;
                        Accgr = [select id, name from Account where Id =: accId LIMIT 1];
                    }
                    Lead ld = New Lead(FirstName = cFName, LastName = cLName, Email = cEmail, Phone = cPhone,
                                       MobilePhone = cMobilePhone, What_type_of_system_are_you_after__c = systemType,
                                       size__c = systemSize, installationAddressLineOne__c = installationAdd,Referred_by_Aggregator_Acc__c = Accgr.id,
                                        quarterlyBill__c = QuarterlyEnergyBill,LeadSource='SolarQuotes', Point_of_Origin__c = 'SolarQuotes API'); 
                    insert ld;
                    
                    List<Supplier__c> suppList = New List<Supplier__c>();
                    for(Object obj: supplierDetailList ){
                        Map<String, Object> objSMap = (Map<String, Object>)obj;
                        Supplier__c supp = New Supplier__c(Name = (String)objSMap.get('sName'), Lead__c = ld.Id);
                        suppList.add(supp);
                    }
                    
                    insert suppList;
                    
                    
                    jsonStr = '{"Status" : "Success","Message" : "New Lead Inserted successfully","LeadId" : "' + ld.Id + '"}';
                }
            }
        }catch(exception e){
            jsonStr = '{"Status" : "Error","Message" : "'+e.getMessage()+'"}';
        }
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(jsonStr);
        return;
    }
    
    
}