force-app/main/default/objects/Lead/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>FinServ__Lead Process</businessProcess>
    <description>These are leads who expressed interest in Solar</description>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirm_Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Settlement_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Settlement Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <formula>FinServ__FinancialAccount__r.FinServ__InterestRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Opportunity Process</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate_Override__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Rate Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interest_Rate_Override__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Override__c</fullName>
    <label>Interest Rate Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/groupQuoteController_Test.cls
@isTest
public class groupQuoteController_Test {
    @isTest
    static void testMethod1(){
       
        
        User user = new User( ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id, LastName = 'last', Email = 'puser000@amamama.com', Username = 'puser000@amamama.com' + System.currentTimeMillis(), CompanyName = 'TEST', Title = 'title', Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US' );
        insert user;
        System.runAs(user){
            String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            Account ac = new Account(FirstName='Test Ac',PersonEmail = 'puser000@amamama.com', LastName='test', RecordTypeID = recordTypeId );
            insert ac;
            Account acc = new account();
            acc.RecordTypeId= recordTypeId;
            acc.FirstName = 'Test';
            acc.LastName = 'Testr'; 
            acc.PersonEmail='rakesh@gmail.com';
            insert acc;
            //List<String> typeList = productSearch.getProductType();
            Product2 pd = new Product2();
            pd.Interest_Rate__c = 5.6;
            pd.Interest_Rate_Override__c = true;
            pd.Interest_Rate_Type__c = 'Fixed';
            pd.Name = 'Test product';
            insert pd;
            Opportunity opp = new Opportunity( Applicant_1__c = ac.Id,Applicant_2__c = ac.Id, Name='Test', StageName='Settled (closed won)', CloseDate= Date.today(), Confirm_Settlement_Date__c = true);
            Insert opp;
             Opportunity opp1 = new Opportunity( Applicant_1__c = ac.Id,Applicant_2__c = ac.Id, Name='Test', StageName='Application', CloseDate= Date.today(), Confirm_Settlement_Date__c = true);
            Insert opp1;
            Opportunity opp3 = new Opportunity( Applicant_1__c = ac.Id,Applicant_2__c = ac.Id, Name='Test', StageName='Settled (closed won)', CloseDate= Date.today(), Confirm_Settlement_Date__c = true);
            Insert opp3;
            Opportunity opp4 = new Opportunity( Applicant_1__c = acc.Id,Applicant_2__c = ac.Id, Name='Test', StageName='Settled (closed won)', CloseDate= Date.today(), Confirm_Settlement_Date__c = true);
            Insert opp4;
            
            List<Quote> temQuote = new List<Quote>();
            temQuote.add(new Quote(Name ='test', Gruop_Name__c = 'test',Purpose__c='Solar', OpportunityId=opp.Id));
            temQuote.add(new Quote(Name ='test1', Gruop_Name__c = 'test2',Purpose__c='Solar', OpportunityId=opp.Id));
            temQuote.add(new Quote(Name ='test1', Gruop_Name__c = 'test1',Purpose__c='Solar', OpportunityId=opp.Id));
            temQuote.add(new Quote(Name ='test3', Gruop_Name__c = 'test3',Purpose__c='Solar', OpportunityId=opp4.Id));
            insert temQuote;
            
            lead jd = new lead();
            jd.Email ='rakesh@gmail.com';
            jd.LastName='test';
            insert jd;
            
            Map<String, List<Object>> temp = groupQuoteController.getQuoteName(opp.ID);
            test.startTest();
            groupQuoteController.sendApplication(opp.id,temQuote[0].id);
            groupQuoteController.sendQuotation(opp4.id,temQuote[0].id,temQuote[3].Gruop_Name__c);
            groupQuoteController.updateQuoteApplication(temQuote[1].id ,opp1.id, temQuote[0].id);
            groupQuoteController.updateQuote(temQuote[0].id, opp3.Id);
            groupQuoteController.deleteApplication(opp.Id, temQuote[0].Gruop_Name__c);
            test.stopTest();
            
        }
    }
}