force-app/main/default/objects/Lead/fields/Unread__c.field-meta.xml
<CustomField>
    <fullName>Unread__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Unread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unread__c.field-meta.xml
<CustomField>
    <fullName>Unread__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Unread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestOpportunityLeadController.cls
@isTest
public class TestOpportunityLeadController {
	@isTest
    public static void testchangeUnread(){
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Green Loan'];
        Lead testLed = new Lead(FirstName='Test',
                                LastName='Lead',
                               RecordType = rt,
                               Unread__c = true);
        insert testLed;
        Account acct = new Account(FirstName='Test',LastName='Acct');
        insert acct;
        Account acct1 = new Account(FirstName='Test1',LastName='Acct1');
        insert acct1;
        Date dt = date.today();
        Opportunity testOpp = new Opportunity(RecordType = rt,
                                         Name = 'Test',
                                         StageName = 'Quote',
                                         CloseDate = dt,
                                         Applicant_1__c = acct.Id,
                                         Applicant_2__c = acct1.Id,
                                         Unread__c = true);
        insert testOpp;
        System.assert(testLed.Unread__c == true);
        System.assert(testOpp.Unread__c == true);
        OpportunityLeadController.changeUnread(testOpp.Id,'opportunity');
        OpportunityLeadController.changeUnread(testLed.Id,'lead');
        testOpp = [Select id,Unread__c from opportunity where Id=:testOpp.Id];
        testLed = [Select id,Unread__c from Lead where Id=:testLed.Id];
        System.assert(testLed.Unread__c == false);
        System.assert(testOpp.Unread__c == false);
    }
}