force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestContentDocumentTrigger.cls
@IsTest
public class TestContentDocumentTrigger {
	@IsTest
    public static void testBeforeInsert(){
        List<String> Cids = new List<String>();
        Account acct = new Account(FirstName='Test',LastName='Acct');
        insert acct;
        Account acct1 = new Account(FirstName='Test1',LastName='Acct1');
        insert acct1;
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Green Loan'];
        Date dt = date.today();
        Opportunity testOpp = new Opportunity(RecordType = rt,
                                         Name = 'Test',
                                         StageName = 'Quote',
                                         CloseDate = dt,
                                         Applicant_1__c = acct.Id,
                                         Applicant_2__c = acct1.Id);
        insert testOpp;
        ContentVersion contentVersion2 = new ContentVersion(
            Title = 'Penguins1',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion2;
        
        ContentDocumentLink cdl2 = New ContentDocumentLink();
        cdl2.LinkedEntityId = testOpp.Id;
        cdl2.ContentDocumentId = [select contentdocumentid from contentversion where id =: contentVersion2.id].contentdocumentid;
        cdl2.shareType = 'V';
        insert cdl2;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = testOpp.Id;
        cdl.ContentDocumentId = [select contentdocumentid from contentversion where id =: contentVersion.id].contentdocumentid;
        cdl.shareType = 'V';
        insert cdl;
        List<ContentDocumentLink> getcdl = [Select Id, ContentDocumentId, Visibility, ShareType FROM ContentDocumentLink where LinkedEntityId=:testOpp.Id];
        for(ContentDocumentLink c: getcdl){
            System.assert(c.ShareType!='I');
            System.assert(c.Visibility=='Allusers');    
        } 
        
    }
}