force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_Email__c</fullName>
    <formula>Applicant_1__r.PersonContact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 1 Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1_FirstName__c</fullName>
    <formula>Applicant_1__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 1 FirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2_FirstName__c</fullName>
    <formula>Applicant_2__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant 2 FirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Expire_Date__c</fullName>
    <formula>DATEVALUE(Approved_Date__c) + 90</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/leadAddress__c.field-meta.xml
<CustomField>
    <fullName>leadAddress__c</fullName>
    <description>For solar quotes</description>
    <label>leadAddress</label>
    <length>550</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_the_quote_to__c.field-meta.xml
<CustomField>
    <fullName>Send_the_quote_to__c</fullName>
    <label>Send the quote to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Me and my customer</fullName>
            </value>
            <value>
                <fullName>Me only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Customer_Approval_Email_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Customer_Approval_Email_Instructions__c</fullName>
    <label>Customer Approval Email Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Funding_Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Authorisation_Type__c</fullName>
    <label>Funding Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct with lender</fullName>
            </value>
            <value>
                <fullName>Managed via Parker Lane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApprovedRemainderController.cls
public class ApprovedRemainderController {
    
    public String opportunityId{get;set;}
    public Product2 product{get;set;}
    public Quote Qt{get;set;}
    public String oppName{get;set;}
    
    public Boolean init{
        get{
            init();            
            return false;
        }
    } 
    
    public void init(){
        product = new Product2();
        Qt = new Quote();
        
        Qt = [Select id,Customer_Amount__c, Product__c,Product__r.id from Quote where OpportunityId =: opportunityId AND Application__c = true LIMIT 1]; 
        
        product = [Select id, Customer_Approval_Email_Instructions__c,Funding_Authorisation_Type__c from Product2 WHERE id =: Qt.Product__r.id LIMIT 1];
    }
    
    public opportunity getOpportunity(){
        Opportunity opp = [select id,Applicant_1__c,Applicant_2__c,Approved_Expire_Date__c,Loan_Amount__c ,Opportunity.Applicant_2_FirstName__c,name,Applicant_1_FirstName__c,Applicant_1_Email__c,
                           FinServ__ReferredByContact__r.Name,FinServ__ReferredByContact__r.Account.name,purpose__c,leadAddress__c, Applicant_1__r.phone, Send_the_quote_to__c 
                           from opportunity where id=:opportunityId LIMIT 1];
        oppName = opp.name.split(',')[0];
        return opp;
    }
    
}