force-app/main/default/objects/Opportunity/fields/Application_Supporting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Application_Supporting_Notes__c</fullName>
    <label>Application Supporting Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>Code_Not_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Code Not Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code__c</fullName>
    <label>Secure Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code_Orignal__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code_Orignal__c</fullName>
    <label>Secure Code Orignal</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Video_and_Photo_ID_of_the_same_person__c.field-meta.xml
<CustomField>
    <fullName>Video_and_Photo_ID_of_the_same_person__c</fullName>
    <label>Video and Photo ID of the same person</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facial match (success)</fullName>
            </value>
            <value>
                <fullName>Not facial match (failed)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Show_Video_Controller_Test.cls
@isTest
public class Show_Video_Controller_Test {
	@isTest	
    public static void VideoTestMethod(){
        
        
        VOI_Detail__c obj = new VOI_Detail__c();
        obj.Secure_Code__c = '1234';
        obj.Secure_Code_Orignal__c = '1434';
        insert obj;
        
        Show_Video_controller.FetchVoiDetail(obj.Id);
        
        Show_Video_controller.UpdateVOI(obj);
        Show_Video_controller.sendVideoDataToComponent(obj.Id);
       
    }
    
    @isTest
    public static void videoTestMethodSec(){
        contact con = new contact();
        con.LastName = 'test';
        con.Email = 'test@gmail.com';
        insert con;
        
        opportunity opp = new opportunity();
        opp.Name = 'test oop';
        opp.StageName = 'Working';
        opp.Application_Supporting_Notes__c = 'hello';
        opp.CloseDate = System.today();
        opp.Contact_1__c = con.Id;
        insert opp;
        
        
        VOI_Detail__c obj1 = new VOI_Detail__c();
        obj1.Contact__c = con.Id;
        obj1.Secure_Code__c = '1234';
        obj1.Secure_Code_Orignal__c = '1234';
        obj1.Video_and_Photo_ID_of_the_same_person__c = 'Facial match (success)';
        obj1.Code_Not_Required__c  =true;	
        insert obj1;
        
        VOI_Status__c vois = new VOI_Status__c();
        vois.Contact__c = con.id;
        vois.VOI_Detail__c = obj1.Id;
        vois.Opportunity__c = opp.id;
        insert vois;

        
        PageReference pageRef = Page.Show_Video; // Add your VF page Name here
        pageRef.getParameters().put('id', string.valueOf(obj1.Id));
        Test.setCurrentPage(pageRef);
        
        
        Show_Video_controller.UpdateVOI(obj1);
        
        Show_Video_controller.GenrateIdentityCertificate(obj1);
        
        
    }
}