force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    public void onAfterDelete(List<Quote> oldQuote, Map<Id,Quote> oldQuoteMap){
        Set<Id> v = new Set<Id>();
        for(Quote q: oldQuote){
            if(q.Application__c == true){
                v.add(q.OpportunityId);
            }
        }
        if(v.size() > 0){
            List<Opportunity> oppList = [Select Id, Loan_Amount__c from Opportunity where Id in: v];
            for(Opportunity opp: oppList){
                opp.Loan_Amount__c = 0;
                opp.Lender__c = '';
            }
            update oppList;
        }
    }
}