force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
private class QuoteTriggerHandlerTest {
     @testSetup static void setup() {
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'Green Loan'];
        Date dt = date.today();
        List<Opportunity> testOpp = new List<Opportunity>();
        for(Integer i=1; i<5; i++){
            testOpp.add(new Opportunity(RecordType = rt,
                                         Name = 'Test'+i,
                                         StageName = 'Quote',
                                         CloseDate = dt+i,
                                         Loan_Amount__c = i*100));
        }
        insert testOpp;
        Opportunity toUse = [Select Id, Loan_Amount__c From Opportunity where Name = 'Test1'];
        
        System.assert(toUse.Loan_Amount__c == 100);
        List<Quote> testQuot = new List<Quote>();
        for(Integer i=1; i<5; i++){
            testQuot.add(new Quote(Name = 'Quotetest'+i,
                                   OpportunityId = toUse.Id,
                                   Application__c = false,
                                   Lender__c = 'Test Leader',
                                   Customer_Amount__c = i*1000 ));
        }
        insert testQuot;
     }    
    
    @isTest
    static void TestDeleteApplication(){
        Test.startTest();
        Quote fetchQuo = [Select Id,Application__c from Quote where Name = 'Quotetest1'];
        fetchQuo.Application__c = true;
        update fetchQuo;
        delete fetchQuo;
        Opportunity fetchOpp = [Select Id,Loan_Amount__c from Opportunity where Name = 'Test1'];
        System.assert(fetchOpp.Loan_Amount__c == 0);
        Test.stopTest();
            
    }
}