force-app/main/default/objects/Opportunity/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateLender.cls
public class updateLender{
    
    @future
    public static void processRecords(List<ID> recordIds){
        List<Opportunity> tempList = new List<Opportunity>();
        List<Opportunity> oppList = [select Lender__c,(select Lender__c,Application__c from Quotes where Application__c = true LIMIT 1) from opportunity where Id IN: recordIds];
        for(Opportunity opp : oppList){
            if(opp.Quotes.size() > 0){
                
                    Quote q = opp.Quotes[0];
                    if(q.Lender__c != null && q.Application__c == true){
                        opp.Lender__c = q.Lender__c;
                        tempList.add(opp);
                    }
                
            }    
        }
        System.debug('===> '+tempList.size());
        update tempList;
    }
}