force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Loan_Fees__c/Loan_Fees__c.object-meta.xml
<CustomObject>
    <label>Loan Fees</label>
    <nameField>
        <label>Loan Fees</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Fees__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>Loan_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
                <default>true</default>
                <label>Priorities</label>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Current_Application_Sections__c</fullName>
    <label>Current Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Opportunity Process</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Acceptable_Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Acceptable_Loan_Purpose__c</fullName>
    <label>Acceptable Loan Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
            <value>
                <fullName>General Personal</fullName>
                <isActive>false</isActive>
                <label>General Personal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Default_Product__c.field-meta.xml
<CustomField>
    <fullName>Default_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Feature_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Feature_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Feature Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Maximum_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Loan_Amount__c</fullName>
    <label>Maximum Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Maximum_Loan_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Loan_Term_Years__c</fullName>
    <label>Maximum Loan Term (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Minimum_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Loan_Amount__c</fullName>
    <label>Minimum Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Order__c</fullName>
    <label>Product Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green Loan</fullName>
            </value>
            <value>
                <fullName>Consolidation Loan</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Car Loan</fullName>
            </value>
            <value>
                <fullName>First Home Loan</fullName>
            </value>
            <value>
                <fullName>Asset Finance</fullName>
                <isActive>false</isActive>
                <label>Asset Finance</label>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
                <isActive>false</isActive>
                <label>Debt Consolidation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Amount__c</fullName>
    <label>Customer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Gruop_Name__c.field-meta.xml
<CustomField>
    <fullName>Gruop_Name__c</fullName>
    <label>Gruop Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Motor Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_Group_Label__c.field-meta.xml
<CustomField>
    <fullName>Quote_Group_Label__c</fullName>
    <label>Quote Group Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Up_Front_Costs_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Up_Front_Costs_Applicable__c</fullName>
    <label>Up Front Costs Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchForLoanExpiryTest.cls
@istest
public class BatchForLoanExpiryTest {
    static testmethod void LoanApprovalExpiryBatchTest(){
        String recordTypeRefId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Referrer (Business)').getRecordTypeId();
        String recordTypePId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String recid = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Green Loan').getRecordTypeId();
        
        Account testAcc = new Account();
        testAcc.RecordTypeId  = recordTypeRefId;
        testAcc.Name = 'TestRef Account'; 
        insert testAcc;
        
        Account testAcc1 = new Account();
        testAcc1.RecordTypeId  = recordTypePId;
        testAcc1.FirstName = 'Test';
        testAcc1.LastName = 'Opportunity 1';
        testAcc1.Phone = '1234567890';
        testAcc1.PersonEmail = 'opp1@test.com';
        
        insert testAcc1;
        
        Account testAcc2 = new Account();
        testAcc2.RecordTypeId  = recordTypePId;
        testAcc2.FirstName = 'Test';
        testAcc2.LastName = 'Opportunity 2';
        testAcc2.Phone = '1234567890';
        testAcc2.PersonEmail = 'opp2@test.com';
        
        insert testAcc2;
        
        Contact testCon = new Contact();
        testCon.FirstName = 'TestRef';
        testCon.LastName = 'Contact';
        testCon.AccountId = testAcc.Id;
        testCon.Admin__c = true;
        testCon.Email = 'test@gmail.com';
        insert testCon;
       
        Opportunity oppty = new Opportunity ();
        oppty.applicant_1__c = testAcc1.Id;
        oppty.applicant_2__c = testAcc2.Id;  
        oppty.AccountId = testAcc1.Id;
        oppty.FinServ__ReferredByContact__c = testCon.Id;
        oppty.Contact_1__c = testCon.Id;
        oppty.name = 'test Oppty';
        oppty.StageName='Approved'; 
        oppty.CloseDate = Date.today();
        oppty.Application_Sections__c ='Own and Owe'; 
        oppty.Current_Application_Sections__c ='Who is applying';
        oppty.RecordTypeId = recid;
        oppty.Approved_Date__c = system.now().addDays(-30); 
        insert oppty; 
        
        Opportunity opp = new Opportunity ();
        opp.applicant_1__c = testAcc1.Id;
        opp.AccountId = testAcc1.Id;
        opp.FinServ__ReferredByContact__c = testCon.Id;
        opp.Contact_1__c = testCon.Id;
        opp.name = 'test opp';
        opp.StageName='Approved'; 
        opp.CloseDate = Date.today();
        opp.Application_Sections__c ='Own and Owe'; 
        opp.Current_Application_Sections__c ='Who is applying';
        opp.RecordTypeId = recid;
        opp.Approved_Date__c = system.now().addDays(-60);
        insert opp;
        
        Opportunity opp1 = new Opportunity ();
        opp1.applicant_1__c = testAcc1.Id;
        opp1.AccountId = testAcc1.Id;
        opp1.FinServ__ReferredByContact__c = testCon.Id;
        opp1.Contact_1__c = testCon.Id;
        opp1.name = 'test opp';
        opp1.StageName='Approved'; 
        opp1.CloseDate = Date.today();
        opp1.Application_Sections__c ='Own and Owe'; 
        opp1.Current_Application_Sections__c ='Who is applying';
        opp1.RecordTypeId = recid;
        opp1.Approved_Date__c = system.now().addDays(-80);
        insert opp1;  
        
        Opportunity opp2 = new Opportunity ();
        opp2.applicant_1__c = testAcc1.Id;
        opp2.AccountId = testAcc1.Id;
        opp2.FinServ__ReferredByContact__c = testCon.Id;
        opp2.Contact_1__c = testCon.Id;
        opp2.name = 'test opp';
        opp2.StageName='Approved'; 
        opp2.CloseDate = Date.today();
        opp2.Application_Sections__c ='Own and Owe'; 
        opp2.Current_Application_Sections__c ='Who is applying';
        opp2.RecordTypeId = recid;
        opp2.Approved_Date__c = system.now().addDays(-31);
        insert opp2;
        
        Opportunity opp3 = new Opportunity ();
        opp3.applicant_1__c = testAcc1.Id;
        opp3.AccountId = testAcc1.Id;
        opp3.FinServ__ReferredByContact__c = testCon.Id;
        opp3.Contact_1__c = testCon.Id;
        opp3.name = 'test opp';
        opp3.StageName='Approved'; 
        opp3.CloseDate = Date.today();
        opp3.Application_Sections__c ='Own and Owe'; 
        opp3.Current_Application_Sections__c ='Who is applying';
        opp3.RecordTypeId = recid;
        opp3.Approved_Date__c = system.now().addDays(-61);
        insert opp3;
        
        Opportunity opp4 = new Opportunity ();
        opp4.applicant_1__c = testAcc1.Id;
        opp4.AccountId = testAcc1.Id;
        opp4.Contact_1__c = testCon.Id;
        opp4.name = 'test opp55';
        opp4.StageName='Funding'; 
        opp4.CloseDate = Date.today();
        opp4.Application_Sections__c ='Own and Owe'; 
        opp4.Current_Application_Sections__c ='Who is applying';
        opp4.RecordTypeId = recid;
        opp4.Approved_Date__c = system.now().addDays(-81);
        insert opp4;
        
        List<Product2> productList = new List<Product2>();
        productList.add(New Product2(IsActive =true, Default_Product__c = true,
                                     Product_Type__c = 'Green Loan', Product_Order__c = 1,
                                     Name = 'product', Features__c='Feature1;Feature2',
                                     Acceptable_Loan_Purpose__c = 'Solar',
                                     Maximum_Loan_Term_Years__c =1,Maximum_Loan_Amount__c=80000,
                                     Minimum_Loan_Amount__c = 1000,
                                     Is_Feature_Product__c=TRUE));
        productList.add(New Product2(IsActive =true, Default_Product__c = true,
                                     Product_Type__c = 'Green Loan', Product_Order__c = 2,
                                     Name = 'product2', Features__c='Feature1;Feature2',
                                     Acceptable_Loan_Purpose__c = 'Solar',Maximum_Loan_Amount__c=80000,
                                     Minimum_Loan_Amount__c = 1000,
                                     Maximum_Loan_Term_Years__c =5));
        productList.add(New Product2(IsActive =true, Default_Product__c = true,
                                     Product_Type__c = 'Green Loan', Product_Order__c = 3,
                                     Name = 'product3', Features__c='Feature1;Feature2',
                                     Acceptable_Loan_Purpose__c = 'Solar',Maximum_Loan_Amount__c=80000,
                                     Minimum_Loan_Amount__c = 1000,
                                     Maximum_Loan_Term_Years__c =3));
        insert productList;
        list<quote> qtlist = new list<quote>();
        qtlist.add(New Quote(Name ='test quote', OpportunityId= oppty.Id, Application__c=true, Up_Front_Costs_Applicable__c = 'Yes',
                             Purpose__c= 'Solar',Gruop_Name__c='One',Quote_Group_Label__c='One', Customer_Amount__c = 35000, Loan_Term__c = 60, Product__c = productList[0].Id,
                             Interest_Rate__c = 3.99, Actual_Comparison_Rate__c = 4.99));
        qtlist.add(New Quote(Name ='test quote2', OpportunityId= opp.Id, Application__c=true, Up_Front_Costs_Applicable__c = 'Yes',
                             Purpose__c= 'Solar',Gruop_Name__c='Referral-1',Quote_Group_Label__c='Referral-1', Customer_Amount__c = 60000, Loan_Term__c = 80, Product__c = productList[1].Id,
                             Interest_Rate__c = 7.99, Actual_Comparison_Rate__c = 8.99));
        qtlist.add(New Quote(Name ='test quote3', OpportunityId= opp1.Id, Application__c=true, Up_Front_Costs_Applicable__c = 'Yes',
                             Purpose__c= 'Solar',Gruop_Name__c='Referral-1',Quote_Group_Label__c='Referral-1', Customer_Amount__c = 60000, Loan_Term__c = 80, Product__c = productList[1].Id,
                             Interest_Rate__c = 5.99, Actual_Comparison_Rate__c = 6.99));
        insert qtlist;
        
        Loan_Fees__c fee1 = New Loan_Fees__c(Amount__c = 200, Product__c = productList[0].Id);
        insert fee1;
        
        Test.startTest();
        BatchForLoanExpiry opptybatch = new BatchForLoanExpiry ();
        Database.executebatch(opptybatch,10);
        Test.stopTest();
        
    }
}