force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/FinServ__ReferredByContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Referrals</relationshipLabel>
    <relationshipName>OpportunityContactReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>FinServ__Opportunity Process</businessProcess>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/BatchForReferrersReportTest.cls
@isTest
public class BatchForReferrersReportTest {
	
    @isTest
    public static void methodOne(){
        Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referrer').getRecordTypeId();
        System.debug(devRecordTypeId);
        
        Account acc = new Account();
        acc.name = 'gdnsns';
        insert acc;
        
        
        contact con = new Contact();
        con.FirstName = 'qtrrywert';
        con.LastName = 'shnsnj';
        con.email = 'test@gmail.com';
        con.AccountId = acc.Id;
        con.Admin__c = true;
        con.RecordTypeId = devRecordTypeId;
        insert con;
        
        
        opportunity op = new Opportunity();
        op.Name = 'qwert';
        op.CloseDate = system.today();
        op.StageName = 'Approved';
        op.FinServ__ReferredByContact__c = con.Id;
        insert op;
        
        EmailTemplate emailTemplate = [SELECT Id,Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Daily_Referral_Report' ];
        
        BatchForReferrersReport obj = new BatchForReferrersReport();
        DataBase.executeBatch(obj);
        
    }
}