force-app/main/default/objects/Contact/fields/Aircall_Mobile_Format__c.field-meta.xml
<CustomField>
    <fullName>Aircall_Mobile_Format__c</fullName>
    <formula>IF(BEGINS(  MobilePhone , &quot;+61&quot;), MobilePhone,
IF(BEGINS( MobilePhone, &quot;4&quot;),&quot;+61&quot; + MobilePhone,
IF(BEGINS( MobilePhone, &quot;0&quot;), &quot;+61&quot; + TRIM(RIGHT(MobilePhone, LEN(Phone)-1 )),
IF(BEGINS( MobilePhone, &quot;+610&quot;), &quot;+61&quot; + TRIM(RIGHT(MobilePhone, LEN(Phone)-4 )),
IF(BEGINS( MobilePhone, &quot;61&quot;),&quot;+&quot; + MobilePhone,
MobilePhone)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircall Mobile Format</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aircall_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Aircall_Mobile_Number__c</fullName>
    <label>Aircall Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aircall_Phone_Format__c.field-meta.xml
<CustomField>
    <fullName>Aircall_Phone_Format__c</fullName>
    <formula>IF(BEGINS( Phone , &quot;+61&quot;), Phone,
IF(BEGINS( Phone , &quot;4&quot;),&quot;+61&quot; + Phone,
IF(BEGINS( Phone , &quot;0&quot;), &quot;+61&quot; + TRIM(RIGHT(Phone , LEN(Phone)-1 )),
IF(BEGINS( Phone , &quot;+610&quot;), &quot;+61&quot; + TRIM(RIGHT(Phone , LEN(Phone)-4 )),
IF(BEGINS( Phone , &quot;61&quot;),&quot;+&quot; + Phone,
Phone )))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircall Phone Format</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aircall_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Aircall_Phone_Number__c</fullName>
    <label>Aircall Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/BatchForUpdateContactAircallPhone.cls
public class BatchForUpdateContactAircallPhone implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
         String query = 'SELECT id,Phone,MobilePhone,Aircall_Mobile_Format__c,Aircall_Mobile_Number__c,Aircall_Phone_Format__c,Aircall_Phone_Number__c FROM Contact';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Contact> contactList){
        for(Contact con : contactList) {        
            if(con.Phone != null){
                con.Aircall_Phone_Number__c = con.Aircall_Phone_Format__c;
            }
            if(con.MobilePhone != null){
                con.Aircall_Mobile_Number__c = con.Aircall_Mobile_Format__c;
            }
        }
        try {
            update contactList;
         
        } catch(Exception e) {
            System.debug(e);
        }
    }
    public void finish(Database.BatchableContext bc){
        System.debug('Successfully Update');
    }
}