force-app/main/default/objects/Contact/fields/FinServ__MaritalStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__MaritalStatus__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Married / defacto</fullName>
            </value>
            <value>
                <fullName>Married / Defacto (to applicant 2)</fullName>
            </value>
            <value>
                <fullName>Married / Defacto (to applicant 1)</fullName>
            </value>
            <value>
                <fullName>Married / defacto (non-applicant)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employment__c/Employment__c.object-meta.xml
<CustomObject>
    <label>Employment</label>
    <nameField>
        <label>Employment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employment</relationshipLabel>
    <relationshipName>Employment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employment__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employment__c/fields/Total_Income_from_Employment__c.field-meta.xml
<CustomField>
    <fullName>Total_Income_from_Employment__c</fullName>
    <formula>IF(ISPICKVAL(Work_Overtime_Frequency__c ,&quot;Weekly&quot;), Work_Overtime_amount__c *52,
IF(ISPICKVAL(Work_Overtime_Frequency__c ,&quot;Fortnightly&quot;), Work_Overtime_amount__c *26,
IF(ISPICKVAL(Work_Overtime_Frequency__c ,&quot;Monthly&quot;), Work_Overtime_amount__c *12,
IF(ISPICKVAL(Work_Overtime_Frequency__c ,&quot;Annually&quot;), Work_Overtime_amount__c *1,
Work_Overtime_amount__c)))) +
IF(ISPICKVAL(Commission_or_Bonus_Frequency__c ,&quot;Weekly&quot;), Commission_or_Bonus_amount__c *52,
IF(ISPICKVAL(Commission_or_Bonus_Frequency__c ,&quot;Fortnightly&quot;), Commission_or_Bonus_amount__c *26,
IF(ISPICKVAL(Commission_or_Bonus_Frequency__c ,&quot;Monthly&quot;), Commission_or_Bonus_amount__c *12,
IF(ISPICKVAL(Commission_or_Bonus_Frequency__c ,&quot;Annually&quot;), Commission_or_Bonus_amount__c *1,
Commission_or_Bonus_amount__c)))) +
IF(ISPICKVAL(Allowance_Frequency__c ,&quot;Weekly&quot;), Allowance_Amount__c *52,
IF(ISPICKVAL(Allowance_Frequency__c ,&quot;Fortnightly&quot;), Allowance_Amount__c *26,
IF(ISPICKVAL(Allowance_Frequency__c ,&quot;Monthly&quot;), Allowance_Amount__c *12,
IF(ISPICKVAL(Allowance_Frequency__c ,&quot;Annually&quot;), Allowance_Amount__c *1,
Allowance_Amount__c))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Income from Employment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Access_Id__c.field-meta.xml
<CustomField>
    <fullName>Access_Id__c</fullName>
    <label>Access Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_1__c.field-meta.xml
<CustomField>
    <fullName>Applicant_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Applicant_2__c.field-meta.xml
<CustomField>
    <fullName>Applicant_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Applicant 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Application_Sections__c</fullName>
    <label>Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
                <default>true</default>
                <label>Priorities</label>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Application_Sections__c.field-meta.xml
<CustomField>
    <fullName>Current_Application_Sections__c</fullName>
    <label>Current Application Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priorities</fullName>
            </value>
            <value>
                <fullName>Loan Recommendation</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Who is applying</fullName>
            </value>
            <value>
                <fullName>Own and Owe</fullName>
            </value>
            <value>
                <fullName>Earn</fullName>
            </value>
            <value>
                <fullName>Living Expenses</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Anticipated Changes to Circumstances</fullName>
            </value>
            <value>
                <fullName>Goals &amp; Objectives</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>Mogo Bank Link</fullName>
            </value>
            <value>
                <fullName>Mogo Document Upload</fullName>
            </value>
            <value>
                <fullName>Mogo Document Error</fullName>
            </value>
            <value>
                <fullName>Standard Document Upload</fullName>
            </value>
            <value>
                <fullName>All Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Document_Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Document_Redirect_URL__c</fullName>
    <label>Document Redirect URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/LinkBankAccountController.cls
public without sharing class LinkBankAccountController{
    //private static final String BASE_URL = 'https://secure.live.mogoplus.com/clovelly/application/createApplication';
    private static final String BASE_URL = 'https://api.aulive.mogoplus.com/clovelly/application/createApplication';
    @future
    public static void myFutureMethod(String aId, String oId)
    {  
        Opportunity opp = [Select Id, Access_Id__c from Opportunity where id=:oId Limit 1];
        opp.Access_Id__c = aId;
        update opp;
    }
    @auraEnabled
    public static String makeMOGORequest(String opId){

        List<Opportunity> opp = [Select Id, Access_Id__c, Name,Applicant_1__r.PersonContactId, Applicant_1__r.FirstName, Applicant_1__r.MiddleName, Applicant_1__r.LastName from Opportunity where id=: opId];

        Contact con = [SELECT Name, FinServ__CurrentEmployer__c, 
              FinServ__Occupation__c, FinServ__MaritalStatus__c, Email,
             (SELECT Id, Name, FinServ__EmploymentStatus__c, Total_Income_from_Employment__c,Is_Primary__c
              FROM FinServ__Employment__r WHERE Is_Primary__c = true LIMIT 1)
              FROM Contact WHERE Id =: opp[0].Applicant_1__r.PersonContactId];
              
        String body = '{'+'"providerId":252,'+'"username":"ParkerLane",'+'"password":"XxmLe2kN",'+'"reference":"'+opp[0].Id+'",'+'"productType":19,'+'"token":"98vc79095332",'+'"userData": {'+'"firstName":"'+opp[0].Applicant_1__r.FirstName+'",'+'"middleName":"'+opp[0].Applicant_1__r.MiddleName+'",'+'"lastName":"'+opp[0].Applicant_1__r.LastName+'",'+'"employerName":"'+con.FinServ__Employment__r[0].Name+'",'+'"employmentType":"F",'+'"income":[{"amount":"'+con.FinServ__Employment__r[0].Total_Income_from_Employment__c+'", "type":"Main", "code":"F"}]'+'}'+'}';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(BASE_URL);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(body);        
        Map<String, Object> result = new Map<String, Object>();
        if(!Test.isRunningTest()){
            HttpResponse response = http.send(request);
            result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        }else{
            String jsonInput = '{\n'+'"hybridUrl":"102",\n'+'"reference":"Invalid45data"\n'+'}';
            result = (Map<String, Object>)JSON.deserializeUntyped(jsonInput);
        }
        System.debug(result);
        String url;

        if((String)result.get('hybridUrl') != null){
            url = (String)result.get('hybridUrl');
        }
        if((String)result.get('reference') != null){
            String apId = (String)result.get('reference');
            myFutureMethod(apId,opp[0].Id);
        }
        return url;
    }
    
    @auraEnabled
    public static void updateSection(String oppId){
        Opportunity opp = [select Id, name, Applicant_1__r.PersonContactId, Application_Sections__c, Current_Application_Sections__c, Applicant_1__r.Phone, Applicant_2__c, 
                           Applicant_2__r.PersonContactId, Applicant_2__r.Phone, Document_Redirect_URL__c 
                           FROM opportunity WHERE Id =: oppId];
        system.debug(opp);
        
        if(opp.Document_Redirect_URL__c.contains('/MogoDocument')){
            opp.Application_Sections__c = 'Mogo Document Upload';
            opp.Current_Application_Sections__c = 'Mogo Document Upload';
        }
        update opp;
    }    
}