force-app/main/default/objects/Contact/fields/Primary_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Employer_Name__c</fullName>
    <label>Primary Employer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Residential_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address_1__c</fullName>
    <label>Residential Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Residential_Address__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address__c</fullName>
    <label>Residential Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Packs_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Packs_Out_Date__c</fullName>
    <label>Packs Out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Match_Status__c.field-meta.xml
<CustomField>
    <fullName>Code_Match_Status__c</fullName>
    <label>Code Match Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Match(Success)</fullName>
            </value>
            <value>
                <fullName>Not-Match(Failed)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>Code_Not_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Code Not Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <label>Date submitted</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/matchVerification__c.field-meta.xml
<CustomField>
    <fullName>matchVerification__c</fullName>
    <formula>IF(ISPICKVAL(Code_Match_Status__c, &apos;Not-Match(Failed)&apos;), &apos;Not required&apos;, &apos;Verified&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>matchVerification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/verified_by_selfie_ID__c.field-meta.xml
<CustomField>
    <fullName>verified_by_selfie_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>verified by selfie ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <label>Date submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IdentityCertificateController.cls
public class IdentityCertificateController {
    //public string voiId = '';	
    public static opportunity opp{get; set;}
    public static contact con{get; set;}
    public static VOI_Detail__c voi{get; set;}
    public static String frontDL {get; set;}
    public static String frontDLURL {get; set;}
    
    public static String BackDL {get; set;}
    public static String BackDLURL {get; set;}
    
    public static String Passport {get; set;}
    public static String PassportURL {get; set;}
    
    public static String Snap {get; set;}
    public static String SnapURL {get; set;}
   
    public static String paksBackDate {get; set;}
    public static String paksBacktime {get; set;}
    
    public static String videoCreateDate {get; set;}
    public static String videoCreatetime {get; set;}
    
    public static String verifyDate {get; set;}
    public static String data {get; set;}
    
    public IdentityCertificateController(){
        id voiId = ApexPages.currentPage() != null ? ApexPages.currentPage().getParameters().get('id') : '';
        voi = [select Id,matchVerification__c, name,LastModifiedDate,verified_by_selfie_ID__c,Code_Match_Status__c, contact__r.name,contact__r.id,CreatedDate,Code_Not_Required__c from VOi_detail__c where Id =: voiId LIMIT 1];
        System.debug('Code_Match_Status__c ==========='+voi.Code_Match_Status__c);
        System.debug('ID =='+voi.ID);
        Voi_status__c vois = [select id, name,LastModifiedDate,Opportunity__c,Opportunity__r.id,Date_submitted__c, VOI_detail__c from VOI_Status__c WHERE VOI_detail__r.id = : voi.id LIMIT 1];
        
        List<string> stringdata = new List<string>();
        string link = '/sfc/servlet.shepherd/version/download/';
       dateTime videoCretedate;
        
        try{
            stringdata = getImageData('Passport');
            if(stringdata != null && stringdata.size() > 0){
                Passport = stringdata[1];
                PassportURL = link+Passport;   
            }   
        }catch(Exception ex){
            System.debug(ex.getMessage());
            stringdata = getImageData('DLFront');
            frontDL = stringdata[1];
            frontDLURL = link+frontDL;
            
            stringdata = getImageData('BackDL');
            BackDL = stringdata[1];
            BackDLURL = link+BackDL;
            
        }            
        
        try{
        stringdata = getImageData('video');
        videoCretedate = dateTime.valueOf(stringdata[0]);
        
        System.debug('stringdata---+'+videoCretedate);
        }Catch(Exception e){
            System.debug(e.getMessage());
            videoCretedate = system.now();
        }
        opp = [select id,Purpose__c, name,Packs_Out_Date__c from opportunity WHERE id =: vois.Opportunity__r.id  LIMIT 1];
        
        paksBacktime = monthCOnvert((vois.Date_submitted__c != null ? vois.Date_submitted__c : vois.LastModifiedDate))[0];
        
        paksBackDate = monthCOnvert((vois.Date_submitted__c != null ? vois.Date_submitted__c : vois.LastModifiedDate))[1];
        
        //-----------------------------------------------------------------------------
        
        videoCreatetime = monthCOnvert(videoCretedate)[0];
        
        videoCreateDate = monthCOnvert(videoCretedate)[1];
        
        //-----------------------------------------------------------------------------
    	Boolean isSelfi = false;
    	verifyDate = monthCOnvert(voi.LastModifiedDate)[1];
       
        try{
        stringdata = getImageData('Selfi');
        Snap = stringdata[1];
        SnapURL = link+Snap;
        }Catch(Exception ex){
            System.debug('me-'+ex);    
            isSelfi = true;
        }
       
        if(isSelfi){
            try{
                stringdata = getImageData('VideoSnap');
                Snap = stringdata[1];
                SnapURL = link+Snap;
            }Catch(Exception ex){
                System.debug('me-'+ex);    
            }
        }
       
   }
    
    
    
    public static contact getContact(){
        try{
            con = [select id,Residential_Address__c,Residential_Address_1__c, Year__c,Primary_Employer_Name__c, name from contact where id =: voi.Contact__r.id LIMIT 1];
        }Catch(Exception ex){
            System.debug('excep---'+ex.getCause() + ex.getMessage() + ex.getLineNumber());
        }
        return con;
    }
    
    public static List<string> getImageData(string docName){
        id voiId  = ApexPages.currentPage() != null ? ApexPages.currentPage().getParameters().get('id') : '';
        list<ContentVersion> CVList = new List<ContentVersion>();
        list<String> VersionDataList = new List<String>();
        List<String> Temp = new List<string>();
        Set<Id> CDId = new Set<Id>();
        string DocNameforQ = '';
        string forUpdated = '';
        System.debug('docName'+docName);
         string olderName = '';
        VOI_Detail__c vs = [Select id, contact__r.Name From VOI_Detail__c WHERE id =: voiId LIMIT 1];
        if(docName == 'DLFront'){
            DocNameforQ = 'DL Front '+vs.contact__r.Name;
            System.debug('DocNameforQ---'+DocNameforQ);
            olderName = docName;
            forUpdated = 'DL Front%';
        }
        else if(docName == 'BackDL'){
            DocNameforQ = 'DL Back '+vs.contact__r.Name;
            olderName = docName;
            forUpdated = 'DL Back%';
        }
        else if(docName == 'Selfi'){
            DocNameforQ = 'Selfie holding DL '+vs.contact__r.Name;
            olderName = docName;
        }
        else if(docName == 'Passport'){
            DocNameforQ = 'passport '+vs.contact__r.Name;
            olderName = docName;
            forUpdated = 'passport%';
        }
        else{
            DocNameforQ = docName;
        }
        System.debug('DocNameforQ'+DocNameforQ);
        for(ContentDocumentLink Cd : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: voiId]){
            CDId.add(Cd.ContentDocumentId);
        }
        System.debug('CDId--->'+CDId);
        
        CVList = [SELECT Id,createddate FROM ContentVersion WHERE ContentDocumentId = : CDId AND (Title =: DocNameforQ OR Title =: olderName OR Title Like : forUpdated) order by createddate DESC LIMIT 1];
        string st = string.valueOf(CVList[0].createddate); 
        Temp.add(st);
        for(ContentVersion Cd : CVList){
            VersionDataList.add(Cd.Id);
        }
        if(VersionDataList != null){
            if(VersionDataList.size() > 0){
                Temp.add(VersionDataList[0]);
            }    
        }
        return Temp;
    }
	
    public List<string> monthCOnvert(dateTime dat){
        
        List<string> datetimeconverted = new List<string>();
        List<string> data = string.valueOf(dat).split(' ');
        dateTime tim =  dat;
        string team = tim.format('h:mm a');
        
        datetimeconverted.add(team);
        
        integer nm = dat.month();
        
        string mnth = '';
        if(nm == 1){
            mnth = 'January';
        }
        else if(nm == 2){
            mnth = 'February';
        }
        else if(nm == 3){
            mnth = 'March';
        }
        else if(nm == 4){
            mnth = 'April';
        }
        else if(nm == 5){
            mnth = 'May'; 
        }
        else if(nm == 6){
            mnth = 'June';
        }
        else if(nm == 7){
            mnth = 'July';
        }
        else if(nm == 8){
            mnth = 'August';
        }
        else if(nm == 9){
            mnth = 'September';
        }
        else if(nm == 10){
            mnth = 'October';
        }
        else if(nm == 11){
            mnth = 'November';
        }
        else if(nm == 12){
            mnth = 'December'; 
        }
        else{
            mnth = '';
        }
        
        string st = dat.day() + ' ' + mnth + ' ' + dat.year();
        
        datetimeconverted.add(st);
        return datetimeconverted;
    }
    
  
}