force-app/main/default/objects/Contact/fields/VOI_type__c.field-meta.xml
<CustomField>
    <fullName>VOI_type__c</fullName>
    <label>VOI type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FULL</fullName>
                <default>true</default>
                <label>FULL</label>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>E-SIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 1)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Packs_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Packs_Out_Date__c</fullName>
    <label>Packs Out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/VOI_Detail__c.object-meta.xml
<CustomObject>
    <label>VOI Detail</label>
    <nameField>
        <displayFormat>VOIDT-{00000}</displayFormat>
        <label>VOI Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Detail__c/fields/Code_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>Code_Not_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Code Not Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <label>Date submitted</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Details</relationshipLabel>
    <relationshipName>VOI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/Secure_Code_Orignal__c.field-meta.xml
<CustomField>
    <fullName>Secure_Code_Orignal__c</fullName>
    <label>Secure Code Orignal</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOI_Detail__c/fields/VOI_Type__c.field-meta.xml
<CustomField>
    <fullName>VOI_Type__c</fullName>
    <label>VOI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FULL</fullName>
            </value>
            <value>
                <fullName>VOI</fullName>
            </value>
            <value>
                <fullName>E-SIGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOI_Status__c/VOI_Status__c.object-meta.xml
<CustomObject>
    <label>VOI Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>VOI Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOI Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOI_Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Date_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_submitted__c</fullName>
    <label>Date submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Detail__c.field-meta.xml
<CustomField>
    <fullName>VOI_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOI Detail</label>
    <referenceTo>VOI_Detail__c</referenceTo>
    <relationshipLabel>VOI Status</relationshipLabel>
    <relationshipName>VOI_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOI_Status__c/fields/VOI_Status__c.field-meta.xml
<CustomField>
    <fullName>VOI_Status__c</fullName>
    <label>VOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>eSign Complete</fullName>
            </value>
            <value>
                <fullName>VOI Failed, eSign Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Consolidation</fullName>
    </customValue>
    <masterLabel>Product Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IdentityCertificateControllerTest.cls
@isTest
public class IdentityCertificateControllerTest {
	
    @isTest
    public static void methodOne(){
        contact con = new contact();
        con.firstname = 'qwert';
        con.lastName = 'testing';
        con.VOI_type__c = 'VOI';
        insert con;
        
        VOI_Detail__c obj  = new VOI_Detail__c();
        obj.Secure_Code_Orignal__c = '1234';
        obj.Contact__c = con.Id;
        obj.Code_Not_Required__c = true;
        insert obj;
        
        PageReference pageRef1 = Page.IdentityVerificationCertificatePDF; // Add your VF page Name here
        pageRef1.getParameters().put('id', obj.id);
        Test.setCurrentPage(pageRef1);
        
        IdentityCertificateController.getContact();
        contact cont = [Select id, Name From contact WHERE id =: con.id LIMIT 1];
        
        ContentVersion cv=new Contentversion();
        cv.title= 'DL Front '+cont.Name;
        cv.PathOnClient ='DL Front '+cont.Name+'.jpeg';
        Blob b=Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        
        ContentVersion cv1 = new Contentversion();
        cv1.title= 'DL Back '+cont.Name;
        cv1.PathOnClient ='DL Back '+cont.Name+'.jpeg';
        Blob b1=Blob.valueOf('Unit Test Attachment Body');
        cv1.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv1;
        
        ContentVersion cv2 = new Contentversion();
        cv2.title='video';
        cv2.PathOnClient ='video.jpeg';
        Blob b2=Blob.valueOf('Unit Test Attachment Body');
        cv2.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv2;
        
        ContentVersion cv3 = new Contentversion();
        cv3.title='video';
        cv3.PathOnClient ='video.jpeg';
        Blob b3=Blob.valueOf('Unit Test Attachment Body');
        cv3.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv3;
        
        System.debug('cv'+cv.Id);
        System.debug('cv1'+cv1.Id);
        System.debug('cv2'+cv2.Id);
        
        List<ContentVersion> conDocId = new List<ContentVersion>();
        conDocId = [SELECT ContentDocumentId FROM ContentVersion LIMIT 4];
        System.debug('-'+conDocId);
        
		
        List<ContentDocumentLink> CLDList = new List<ContentDocumentLink>();
        
        for(ContentVersion cvr : conDocId){
            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.ContentDocumentId = cvr.ContentDocumentId;
            contentlink.ShareType= 'I';
            contentlink.LinkedEntityId = obj.Id; 
            contentlink.Visibility = 'AllUsers';     
            
            CLDList.add(contentlink);
        }
        
        upsert CLDList;
        
        opportunity opp = new opportunity();
        opp.name = 'test Opp';
        opp.Purpose__c = 'Home Improvement';
        opp.Packs_Out_Date__c = system.today();
        opp.Contact_1__c = con.id;
        opp.StageName = 'Working';
        opp.CloseDate = System.today();
        
        insert opp;
        
        VOI_Status__c vois = new VOI_Status__c();
        vois.Contact__c = con.id;
        vois.VOI_Detail__c = obj.Id;
        vois.Opportunity__c = opp.id;
        vois.Date_submitted__c = system.now();
        insert vois;
        
        IdentityCertificateController ICC = new IdentityCertificateController();
    }
}